package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.aiagent.agent_ast_translate.AstTranslateAgentFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin agent_ast_translate, com.aiagent.agent_ast_translate.AstTranslateAgentFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.agent_chat.ChatAgentFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin agent_chat, com.aiagent.agent_chat.ChatAgentFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.agent_sts_chat.StsChatAgentFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin agent_sts_chat, com.aiagent.agent_sts_chat.StsChatAgentFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.agent_translate.TranslateAgentFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin agent_translate, com.aiagent.agent_translate.TranslateAgentFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.agents_server.AgentsServerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin agents_server, com.aiagent.agents_server.AgentsServerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.plugin_interface.AiPluginInterfacePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin ai_plugin_interface, com.aiagent.plugin_interface.AiPluginInterfacePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.assistant_server.AssistantServerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin assistant_server, com.aiagent.assistant_server.AssistantServerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.ast_polychat.AstPolychatPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin ast_polychat, com.aiagent.ast_polychat.AstPolychatPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.ast_volcengine.AstVolcenginePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin ast_volcengine, com.aiagent.ast_volcengine.AstVolcenginePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new xyz.luan.audioplayers.AudioplayersPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin audioplayers_android, xyz.luan.audioplayers.AudioplayersPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.jielihome.jielihome.JielihomePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin device_jieli, com.jielihome.jielihome.JielihomePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.device_manager.DeviceManagerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin device_manager, com.aiagent.device_manager.DeviceManagerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.device_plugin_interface.DevicePluginInterfacePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin device_plugin_interface, com.aiagent.device_plugin_interface.DevicePluginInterfacePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.mr.flutter.plugin.filepicker.FilePickerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin file_picker, com.mr.flutter.plugin.filepicker.FilePickerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new flutter.overlay.window.flutter_overlay_window.FlutterOverlayWindowPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_overlay_window, flutter.overlay.window.flutter_overlay_window.FlutterOverlayWindowPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin flutter_plugin_android_lifecycle, io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.github.dart_lang.jni.JniPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin jni, com.github.dart_lang.jni.JniPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.github.dart_lang.jni_flutter.JniFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin jni_flutter, com.github.dart_lang.jni_flutter.JniFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.llm_openai.LlmOpenaiPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin llm_openai, com.aiagent.llm_openai.LlmOpenaiPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.llm_volcengine.LlmVolcenginePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin llm_volcengine, com.aiagent.llm_volcengine.LlmVolcenginePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.local_db.LocalDbPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin local_db, com.aiagent.local_db.LocalDbPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.mcp.McpFlutterPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin mcp, com.aiagent.mcp.McpFlutterPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin permission_handler_android, com.baseflow.permissionhandler.PermissionHandlerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new app.rive.rive.RivePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin rive_common, app.rive.rive.RivePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.service_manager.ServiceManagerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin service_manager, com.aiagent.service_manager.ServiceManagerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.fluttercommunity.plus.share.SharePlusPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin share_plus, dev.fluttercommunity.plus.share.SharePlusPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin shared_preferences_android, io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.sts_polychat.StsPolychatPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin sts_polychat, com.aiagent.sts_polychat.StsPolychatPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.sts_volcengine.StsVolcenginePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin sts_volcengine, com.aiagent.sts_volcengine.StsVolcenginePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.stt_azure.SttAzurePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin stt_azure, com.aiagent.stt_azure.SttAzurePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.translate_server.TranslateServerPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin translate_server, com.aiagent.translate_server.TranslateServerPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.translation_aliyun.TranslationAliyunPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin translation_aliyun, com.aiagent.translation_aliyun.TranslationAliyunPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.translation_azure.TranslationAzurePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin translation_azure, com.aiagent.translation_azure.TranslationAzurePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.translation_deepl.TranslationDeeplPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin translation_deepl, com.aiagent.translation_deepl.TranslationDeeplPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.translation_volcengine.TranslationVolcenginePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin translation_volcengine, com.aiagent.translation_volcengine.TranslationVolcenginePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.aiagent.tts_azure.TtsAzurePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin tts_azure, com.aiagent.tts_azure.TtsAzurePlugin", e);
    }
  }
}
