// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: agents/agents_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBVoitransAgent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AgentId            string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id"`                                  //@go_tags(`json:"agent_id"`) 智能体id
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`                                                       //@go_tags(`json:"name"`) 智能体名称
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`                                                       //@go_tags(`json:"type"`) 智能体类型
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`                                         //@go_tags(`json:"description"`) 智能体描述
	AvatarUrl          string                 `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url"`                            //@go_tags(`json:"avatar_url"`) 智能体头像url
	SupportedLanguages []string               `protobuf:"bytes,6,rep,name=supported_languages,json=supportedLanguages,proto3" json:"supported_languages"` //@go_tags(`json:"supported_languages"`) 支持的语言列表
	Variables          []*AgentVariable       `protobuf:"bytes,7,rep,name=variables,proto3" json:"variables"`                                             //@go_tags(`json:"variables"`) 智能体变量列表
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DBVoitransAgent) Reset() {
	*x = DBVoitransAgent{}
	mi := &file_agents_agents_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBVoitransAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBVoitransAgent) ProtoMessage() {}

func (x *DBVoitransAgent) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBVoitransAgent.ProtoReflect.Descriptor instead.
func (*DBVoitransAgent) Descriptor() ([]byte, []int) {
	return file_agents_agents_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBVoitransAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *DBVoitransAgent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBVoitransAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DBVoitransAgent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DBVoitransAgent) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *DBVoitransAgent) GetSupportedLanguages() []string {
	if x != nil {
		return x.SupportedLanguages
	}
	return nil
}

func (x *DBVoitransAgent) GetVariables() []*AgentVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

type AgentVariable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`                                     //@go_tags(`json:"name"`) 变量名
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`                                     //@go_tags(`json:"type"`) 变量类型
	Required      bool                   `protobuf:"varint,3,opt,name=required,proto3" json:"required"`                            //@go_tags(`json:"required"`) 是否必填
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default"` //@go_tags(`json:"default"`) 默认值
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`                       //@go_tags(`json:"description"`) 变量描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentVariable) Reset() {
	*x = AgentVariable{}
	mi := &file_agents_agents_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentVariable) ProtoMessage() {}

func (x *AgentVariable) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentVariable.ProtoReflect.Descriptor instead.
func (*AgentVariable) Descriptor() ([]byte, []int) {
	return file_agents_agents_db_proto_rawDescGZIP(), []int{1}
}

func (x *AgentVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentVariable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentVariable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *AgentVariable) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *AgentVariable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_agents_agents_db_proto protoreflect.FileDescriptor

const file_agents_agents_db_proto_rawDesc = "" +
	"\n" +
	"\x16agents/agents_db.proto\"\xf4\x01\n" +
	"\x0fDBVoitransAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x05 \x01(\tR\tavatarUrl\x12/\n" +
	"\x13supported_languages\x18\x06 \x03(\tR\x12supportedLanguages\x12,\n" +
	"\tvariables\x18\a \x03(\v2\x0e.AgentVariableR\tvariables\"\x9a\x01\n" +
	"\rAgentVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\brequired\x18\x03 \x01(\bR\brequired\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescriptionB\x06Z\x04.;pbb\x06proto3"

var (
	file_agents_agents_db_proto_rawDescOnce sync.Once
	file_agents_agents_db_proto_rawDescData []byte
)

func file_agents_agents_db_proto_rawDescGZIP() []byte {
	file_agents_agents_db_proto_rawDescOnce.Do(func() {
		file_agents_agents_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agents_agents_db_proto_rawDesc), len(file_agents_agents_db_proto_rawDesc)))
	})
	return file_agents_agents_db_proto_rawDescData
}

var file_agents_agents_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_agents_agents_db_proto_goTypes = []any{
	(*DBVoitransAgent)(nil), // 0: DBVoitransAgent
	(*AgentVariable)(nil),   // 1: AgentVariable
}
var file_agents_agents_db_proto_depIdxs = []int32{
	1, // 0: DBVoitransAgent.variables:type_name -> AgentVariable
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agents_agents_db_proto_init() }
func file_agents_agents_db_proto_init() {
	if File_agents_agents_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agents_agents_db_proto_rawDesc), len(file_agents_agents_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agents_agents_db_proto_goTypes,
		DependencyIndexes: file_agents_agents_db_proto_depIdxs,
		MessageInfos:      file_agents_agents_db_proto_msgTypes,
	}.Build()
	File_agents_agents_db_proto = out.File
	file_agents_agents_db_proto_goTypes = nil
	file_agents_agents_db_proto_depIdxs = nil
}
