// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: agents/agents_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentsGetAgentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsGetAgentsReq) Reset() {
	*x = AgentsGetAgentsReq{}
	mi := &file_agents_agents_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsGetAgentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsGetAgentsReq) ProtoMessage() {}

func (x *AgentsGetAgentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsGetAgentsReq.ProtoReflect.Descriptor instead.
func (*AgentsGetAgentsReq) Descriptor() ([]byte, []int) {
	return file_agents_agents_msg_proto_rawDescGZIP(), []int{0}
}

type AgentsGetAgentsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*DBVoitransAgent     `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents"` //@go_tags(`json:"agents"`) //智能体列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsGetAgentsResp) Reset() {
	*x = AgentsGetAgentsResp{}
	mi := &file_agents_agents_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsGetAgentsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsGetAgentsResp) ProtoMessage() {}

func (x *AgentsGetAgentsResp) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsGetAgentsResp.ProtoReflect.Descriptor instead.
func (*AgentsGetAgentsResp) Descriptor() ([]byte, []int) {
	return file_agents_agents_msg_proto_rawDescGZIP(), []int{1}
}

func (x *AgentsGetAgentsResp) GetAgents() []*DBVoitransAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type AgentsGetAgentUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id"` //@go_tags(`json:"agent_id"`) 智能体id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsGetAgentUrlReq) Reset() {
	*x = AgentsGetAgentUrlReq{}
	mi := &file_agents_agents_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsGetAgentUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsGetAgentUrlReq) ProtoMessage() {}

func (x *AgentsGetAgentUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsGetAgentUrlReq.ProtoReflect.Descriptor instead.
func (*AgentsGetAgentUrlReq) Descriptor() ([]byte, []int) {
	return file_agents_agents_msg_proto_rawDescGZIP(), []int{2}
}

func (x *AgentsGetAgentUrlReq) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentsGetAgentUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnectUrl    string                 `protobuf:"bytes,1,opt,name=connect_url,json=connectUrl,proto3" json:"connect_url"` //@go_tags(`json:"connect_url"`) 智能体连接url
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`                             //@go_tags(`json:"token"`) 访问token
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at"`    //@go_tags(`json:"expires_at"`) 过期时间
	ExpiresIn     int32                  `protobuf:"varint,4,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in"`   //@go_tags(`json:"expires_in"`) 过期秒数
	Agent         *AgentInfo             `protobuf:"bytes,5,opt,name=agent,proto3" json:"agent"`                             //@go_tags(`json:"agent"`) 智能体信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentsGetAgentUrlResp) Reset() {
	*x = AgentsGetAgentUrlResp{}
	mi := &file_agents_agents_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentsGetAgentUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentsGetAgentUrlResp) ProtoMessage() {}

func (x *AgentsGetAgentUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentsGetAgentUrlResp.ProtoReflect.Descriptor instead.
func (*AgentsGetAgentUrlResp) Descriptor() ([]byte, []int) {
	return file_agents_agents_msg_proto_rawDescGZIP(), []int{3}
}

func (x *AgentsGetAgentUrlResp) GetConnectUrl() string {
	if x != nil {
		return x.ConnectUrl
	}
	return ""
}

func (x *AgentsGetAgentUrlResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AgentsGetAgentUrlResp) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *AgentsGetAgentUrlResp) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *AgentsGetAgentUrlResp) GetAgent() *AgentInfo {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id"` //@go_tags(`json:"agent_id"`) 智能体id
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`                      //@go_tags(`json:"name"`) 智能体名称
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`                      //@go_tags(`json:"type"`) 智能体类型
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`        //@go_tags(`json:"description"`) 智能体描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agents_agents_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agents_agents_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agents_agents_msg_proto_rawDescGZIP(), []int{4}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AgentInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_agents_agents_msg_proto protoreflect.FileDescriptor

const file_agents_agents_msg_proto_rawDesc = "" +
	"\n" +
	"\x17agents/agents_msg.proto\x1a\x16agents/agents_db.proto\"\x14\n" +
	"\x12AgentsGetAgentsReq\"?\n" +
	"\x13AgentsGetAgentsResp\x12(\n" +
	"\x06agents\x18\x01 \x03(\v2\x10.DBVoitransAgentR\x06agents\"1\n" +
	"\x14AgentsGetAgentUrlReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xae\x01\n" +
	"\x15AgentsGetAgentUrlResp\x12\x1f\n" +
	"\vconnect_url\x18\x01 \x01(\tR\n" +
	"connectUrl\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x04 \x01(\x05R\texpiresIn\x12 \n" +
	"\x05agent\x18\x05 \x01(\v2\n" +
	".AgentInfoR\x05agent\"p\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionB\x06Z\x04.;pbb\x06proto3"

var (
	file_agents_agents_msg_proto_rawDescOnce sync.Once
	file_agents_agents_msg_proto_rawDescData []byte
)

func file_agents_agents_msg_proto_rawDescGZIP() []byte {
	file_agents_agents_msg_proto_rawDescOnce.Do(func() {
		file_agents_agents_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agents_agents_msg_proto_rawDesc), len(file_agents_agents_msg_proto_rawDesc)))
	})
	return file_agents_agents_msg_proto_rawDescData
}

var file_agents_agents_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agents_agents_msg_proto_goTypes = []any{
	(*AgentsGetAgentsReq)(nil),    // 0: AgentsGetAgentsReq
	(*AgentsGetAgentsResp)(nil),   // 1: AgentsGetAgentsResp
	(*AgentsGetAgentUrlReq)(nil),  // 2: AgentsGetAgentUrlReq
	(*AgentsGetAgentUrlResp)(nil), // 3: AgentsGetAgentUrlResp
	(*AgentInfo)(nil),             // 4: AgentInfo
	(*DBVoitransAgent)(nil),       // 5: DBVoitransAgent
}
var file_agents_agents_msg_proto_depIdxs = []int32{
	5, // 0: AgentsGetAgentsResp.agents:type_name -> DBVoitransAgent
	4, // 1: AgentsGetAgentUrlResp.agent:type_name -> AgentInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_agents_agents_msg_proto_init() }
func file_agents_agents_msg_proto_init() {
	if File_agents_agents_msg_proto != nil {
		return
	}
	file_agents_agents_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agents_agents_msg_proto_rawDesc), len(file_agents_agents_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agents_agents_msg_proto_goTypes,
		DependencyIndexes: file_agents_agents_msg_proto_depIdxs,
		MessageInfos:      file_agents_agents_msg_proto_msgTypes,
	}.Build()
	File_agents_agents_msg_proto = out.File
	file_agents_agents_msg_proto_goTypes = nil
	file_agents_agents_msg_proto_depIdxs = nil
}
