// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: aitools/aitools_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求历史记录
type AIToolsBochaSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      string                 `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty" gorm:"keywords"` // @go_tags(`gorm:"keywords"`) 关键词
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty" gorm:"count"`      // @go_tags(`gorm:"count"`) 返回数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolsBochaSearchReq) Reset() {
	*x = AIToolsBochaSearchReq{}
	mi := &file_aitools_aitools_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolsBochaSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolsBochaSearchReq) ProtoMessage() {}

func (x *AIToolsBochaSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_aitools_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolsBochaSearchReq.ProtoReflect.Descriptor instead.
func (*AIToolsBochaSearchReq) Descriptor() ([]byte, []int) {
	return file_aitools_aitools_msg_proto_rawDescGZIP(), []int{0}
}

func (x *AIToolsBochaSearchReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *AIToolsBochaSearchReq) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type AIToolsBochaSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DBWebSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIToolsBochaSearchResp) Reset() {
	*x = AIToolsBochaSearchResp{}
	mi := &file_aitools_aitools_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIToolsBochaSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIToolsBochaSearchResp) ProtoMessage() {}

func (x *AIToolsBochaSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_aitools_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIToolsBochaSearchResp.ProtoReflect.Descriptor instead.
func (*AIToolsBochaSearchResp) Descriptor() ([]byte, []int) {
	return file_aitools_aitools_msg_proto_rawDescGZIP(), []int{1}
}

func (x *AIToolsBochaSearchResp) GetResults() []*DBWebSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_aitools_aitools_msg_proto protoreflect.FileDescriptor

const file_aitools_aitools_msg_proto_rawDesc = "" +
	"\n" +
	"\x19aitools/aitools_msg.proto\x1a\x18aitools/aitools_db.proto\"I\n" +
	"\x15AIToolsBochaSearchReq\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\tR\bkeywords\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"F\n" +
	"\x16AIToolsBochaSearchResp\x12,\n" +
	"\aresults\x18\x01 \x03(\v2\x12.DBWebSearchResultR\aresultsB\x06Z\x04.;pbb\x06proto3"

var (
	file_aitools_aitools_msg_proto_rawDescOnce sync.Once
	file_aitools_aitools_msg_proto_rawDescData []byte
)

func file_aitools_aitools_msg_proto_rawDescGZIP() []byte {
	file_aitools_aitools_msg_proto_rawDescOnce.Do(func() {
		file_aitools_aitools_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aitools_aitools_msg_proto_rawDesc), len(file_aitools_aitools_msg_proto_rawDesc)))
	})
	return file_aitools_aitools_msg_proto_rawDescData
}

var file_aitools_aitools_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aitools_aitools_msg_proto_goTypes = []any{
	(*AIToolsBochaSearchReq)(nil),  // 0: AIToolsBochaSearchReq
	(*AIToolsBochaSearchResp)(nil), // 1: AIToolsBochaSearchResp
	(*DBWebSearchResult)(nil),      // 2: DBWebSearchResult
}
var file_aitools_aitools_msg_proto_depIdxs = []int32{
	2, // 0: AIToolsBochaSearchResp.results:type_name -> DBWebSearchResult
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aitools_aitools_msg_proto_init() }
func file_aitools_aitools_msg_proto_init() {
	if File_aitools_aitools_msg_proto != nil {
		return
	}
	file_aitools_aitools_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aitools_aitools_msg_proto_rawDesc), len(file_aitools_aitools_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aitools_aitools_msg_proto_goTypes,
		DependencyIndexes: file_aitools_aitools_msg_proto_depIdxs,
		MessageInfos:      file_aitools_aitools_msg_proto_msgTypes,
	}.Build()
	File_aitools_aitools_msg_proto = out.File
	file_aitools_aitools_msg_proto_goTypes = nil
	file_aitools_aitools_msg_proto_depIdxs = nil
}
