// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: aitools/aitools_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBWebSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBWebSearchResult) Reset() {
	*x = DBWebSearchResult{}
	mi := &file_aitools_aitools_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBWebSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBWebSearchResult) ProtoMessage() {}

func (x *DBWebSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_aitools_aitools_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBWebSearchResult.ProtoReflect.Descriptor instead.
func (*DBWebSearchResult) Descriptor() ([]byte, []int) {
	return file_aitools_aitools_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBWebSearchResult) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *DBWebSearchResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DBWebSearchResult) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DBWebSearchResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_aitools_aitools_db_proto protoreflect.FileDescriptor

const file_aitools_aitools_db_proto_rawDesc = "" +
	"\n" +
	"\x18aitools/aitools_db.proto\"x\n" +
	"\x11DBWebSearchResult\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontentB\x06Z\x04.;pbb\x06proto3"

var (
	file_aitools_aitools_db_proto_rawDescOnce sync.Once
	file_aitools_aitools_db_proto_rawDescData []byte
)

func file_aitools_aitools_db_proto_rawDescGZIP() []byte {
	file_aitools_aitools_db_proto_rawDescOnce.Do(func() {
		file_aitools_aitools_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aitools_aitools_db_proto_rawDesc), len(file_aitools_aitools_db_proto_rawDesc)))
	})
	return file_aitools_aitools_db_proto_rawDescData
}

var file_aitools_aitools_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aitools_aitools_db_proto_goTypes = []any{
	(*DBWebSearchResult)(nil), // 0: DBWebSearchResult
}
var file_aitools_aitools_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aitools_aitools_db_proto_init() }
func file_aitools_aitools_db_proto_init() {
	if File_aitools_aitools_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aitools_aitools_db_proto_rawDesc), len(file_aitools_aitools_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aitools_aitools_db_proto_goTypes,
		DependencyIndexes: file_aitools_aitools_db_proto_depIdxs,
		MessageInfos:      file_aitools_aitools_db_proto_msgTypes,
	}.Build()
	File_aitools_aitools_db_proto = out.File
	file_aitools_aitools_db_proto_goTypes = nil
	file_aitools_aitools_db_proto_depIdxs = nil
}
