// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: allhelp/allhelp_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取用户任务列表
type AllhelpGetTasksReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"` //@go_tags(`json:"status"`) 按状态筛选，-1 表示全部
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page"`     //@go_tags(`json:"page"`) 页码（从1开始）
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size"`     //@go_tags(`json:"size"`) 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpGetTasksReq) Reset() {
	*x = AllhelpGetTasksReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpGetTasksReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpGetTasksReq) ProtoMessage() {}

func (x *AllhelpGetTasksReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpGetTasksReq.ProtoReflect.Descriptor instead.
func (*AllhelpGetTasksReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{0}
}

func (x *AllhelpGetTasksReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AllhelpGetTasksReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AllhelpGetTasksReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AllhelpGetTasksResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*DBTask              `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks"`  //@go_tags(`json:"tasks"`) 任务列表
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"` //@go_tags(`json:"total"`) 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpGetTasksResp) Reset() {
	*x = AllhelpGetTasksResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpGetTasksResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpGetTasksResp) ProtoMessage() {}

func (x *AllhelpGetTasksResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpGetTasksResp.ProtoReflect.Descriptor instead.
func (*AllhelpGetTasksResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{1}
}

func (x *AllhelpGetTasksResp) GetTasks() []*DBTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *AllhelpGetTasksResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 添加任务
type AllhelpAddTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskName      string                 `protobuf:"bytes,1,opt,name=task_name,json=taskName,proto3" json:"task_name"`          //@go_tags(`json:"task_name"`) 任务标题
	TaskDesc      string                 `protobuf:"bytes,2,opt,name=task_desc,json=taskDesc,proto3" json:"task_desc"`          //@go_tags(`json:"task_desc"`) 任务描述
	TaskType      int32                  `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3" json:"task_type"`         //@go_tags(`json:"task_type"`) 任务类型
	TriggerTime   string                 `protobuf:"bytes,4,opt,name=trigger_time,json=triggerTime,proto3" json:"trigger_time"` //@go_tags(`json:"trigger_time"`) 触发时间(带时区的RFC3339字符串)
	CronExpr      string                 `protobuf:"bytes,5,opt,name=cron_expr,json=cronExpr,proto3" json:"cron_expr"`          //@go_tags(`json:"cron_expr"`) cron表达式
	Extra         string                 `protobuf:"bytes,6,opt,name=extra,proto3" json:"extra"`                                //@go_tags(`json:"extra"`) 扩展信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpAddTaskReq) Reset() {
	*x = AllhelpAddTaskReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpAddTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpAddTaskReq) ProtoMessage() {}

func (x *AllhelpAddTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpAddTaskReq.ProtoReflect.Descriptor instead.
func (*AllhelpAddTaskReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{2}
}

func (x *AllhelpAddTaskReq) GetTaskName() string {
	if x != nil {
		return x.TaskName
	}
	return ""
}

func (x *AllhelpAddTaskReq) GetTaskDesc() string {
	if x != nil {
		return x.TaskDesc
	}
	return ""
}

func (x *AllhelpAddTaskReq) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *AllhelpAddTaskReq) GetTriggerTime() string {
	if x != nil {
		return x.TriggerTime
	}
	return ""
}

func (x *AllhelpAddTaskReq) GetCronExpr() string {
	if x != nil {
		return x.CronExpr
	}
	return ""
}

func (x *AllhelpAddTaskReq) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

type AllhelpAddTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *DBTask                `protobuf:"bytes,1,opt,name=task,proto3" json:"task"` //@go_tags(`json:"task"`) 创建的任务
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpAddTaskResp) Reset() {
	*x = AllhelpAddTaskResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpAddTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpAddTaskResp) ProtoMessage() {}

func (x *AllhelpAddTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpAddTaskResp.ProtoReflect.Descriptor instead.
func (*AllhelpAddTaskResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{3}
}

func (x *AllhelpAddTaskResp) GetTask() *DBTask {
	if x != nil {
		return x.Task
	}
	return nil
}

// 取消任务
type AllhelpCancelTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id"` //@go_tags(`json:"task_id"`) 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpCancelTaskReq) Reset() {
	*x = AllhelpCancelTaskReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpCancelTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpCancelTaskReq) ProtoMessage() {}

func (x *AllhelpCancelTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpCancelTaskReq.ProtoReflect.Descriptor instead.
func (*AllhelpCancelTaskReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{4}
}

func (x *AllhelpCancelTaskReq) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AllhelpCancelTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpCancelTaskResp) Reset() {
	*x = AllhelpCancelTaskResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpCancelTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpCancelTaskResp) ProtoMessage() {}

func (x *AllhelpCancelTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpCancelTaskResp.ProtoReflect.Descriptor instead.
func (*AllhelpCancelTaskResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{5}
}

// 完成任务
type AllhelpCompleteTaskReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        uint64                 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id"` //@go_tags(`json:"task_id"`) 任务ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpCompleteTaskReq) Reset() {
	*x = AllhelpCompleteTaskReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpCompleteTaskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpCompleteTaskReq) ProtoMessage() {}

func (x *AllhelpCompleteTaskReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpCompleteTaskReq.ProtoReflect.Descriptor instead.
func (*AllhelpCompleteTaskReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{6}
}

func (x *AllhelpCompleteTaskReq) GetTaskId() uint64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type AllhelpCompleteTaskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpCompleteTaskResp) Reset() {
	*x = AllhelpCompleteTaskResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpCompleteTaskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpCompleteTaskResp) ProtoMessage() {}

func (x *AllhelpCompleteTaskResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpCompleteTaskResp.ProtoReflect.Descriptor instead.
func (*AllhelpCompleteTaskResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{7}
}

// 提交每日聊天总结（异步，立即返回 Pending 记录）
// 同一 uid+summary_date 重复提交时覆盖重算
type AllhelpSubmitChatSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SummaryDate   string                 `protobuf:"bytes,1,opt,name=summary_date,json=summaryDate,proto3" json:"summary_date"` //@go_tags(`json:"summary_date"`) 日期 YYYY-MM-DD（客户端按本地时区选择）
	Msgs          []*ChatMsg             `protobuf:"bytes,2,rep,name=msgs,proto3" json:"msgs"`                                  //@go_tags(`json:"msgs"`) 当日聊天消息列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpSubmitChatSummaryReq) Reset() {
	*x = AllhelpSubmitChatSummaryReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpSubmitChatSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpSubmitChatSummaryReq) ProtoMessage() {}

func (x *AllhelpSubmitChatSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpSubmitChatSummaryReq.ProtoReflect.Descriptor instead.
func (*AllhelpSubmitChatSummaryReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{8}
}

func (x *AllhelpSubmitChatSummaryReq) GetSummaryDate() string {
	if x != nil {
		return x.SummaryDate
	}
	return ""
}

func (x *AllhelpSubmitChatSummaryReq) GetMsgs() []*ChatMsg {
	if x != nil {
		return x.Msgs
	}
	return nil
}

type AllhelpSubmitChatSummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *DBChatSummary         `protobuf:"bytes,1,opt,name=record,proto3" json:"record"` //@go_tags(`json:"record"`) 入库记录（state=Pending）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpSubmitChatSummaryResp) Reset() {
	*x = AllhelpSubmitChatSummaryResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpSubmitChatSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpSubmitChatSummaryResp) ProtoMessage() {}

func (x *AllhelpSubmitChatSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpSubmitChatSummaryResp.ProtoReflect.Descriptor instead.
func (*AllhelpSubmitChatSummaryResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{9}
}

func (x *AllhelpSubmitChatSummaryResp) GetRecord() *DBChatSummary {
	if x != nil {
		return x.Record
	}
	return nil
}

// 按日期查询（客户端轮询）
type AllhelpGetChatSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SummaryDate   string                 `protobuf:"bytes,1,opt,name=summary_date,json=summaryDate,proto3" json:"summary_date"` //@go_tags(`json:"summary_date"`) YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpGetChatSummaryReq) Reset() {
	*x = AllhelpGetChatSummaryReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpGetChatSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpGetChatSummaryReq) ProtoMessage() {}

func (x *AllhelpGetChatSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpGetChatSummaryReq.ProtoReflect.Descriptor instead.
func (*AllhelpGetChatSummaryReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{10}
}

func (x *AllhelpGetChatSummaryReq) GetSummaryDate() string {
	if x != nil {
		return x.SummaryDate
	}
	return ""
}

type AllhelpGetChatSummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *DBChatSummary         `protobuf:"bytes,1,opt,name=record,proto3" json:"record"` //@go_tags(`json:"record"`) 记录（不存在时 record.id=0）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpGetChatSummaryResp) Reset() {
	*x = AllhelpGetChatSummaryResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpGetChatSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpGetChatSummaryResp) ProtoMessage() {}

func (x *AllhelpGetChatSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpGetChatSummaryResp.ProtoReflect.Descriptor instead.
func (*AllhelpGetChatSummaryResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{11}
}

func (x *AllhelpGetChatSummaryResp) GetRecord() *DBChatSummary {
	if x != nil {
		return x.Record
	}
	return nil
}

// 按日期范围列表
type AllhelpListChatSummariesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date"` //@go_tags(`json:"start_date"`) 含，YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date"`       //@go_tags(`json:"end_date"`) 含，YYYY-MM-DD
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page"`                           //@go_tags(`json:"page"`) 从1开始
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size"`                           //@go_tags(`json:"size"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpListChatSummariesReq) Reset() {
	*x = AllhelpListChatSummariesReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpListChatSummariesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpListChatSummariesReq) ProtoMessage() {}

func (x *AllhelpListChatSummariesReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpListChatSummariesReq.ProtoReflect.Descriptor instead.
func (*AllhelpListChatSummariesReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{12}
}

func (x *AllhelpListChatSummariesReq) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AllhelpListChatSummariesReq) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *AllhelpListChatSummariesReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AllhelpListChatSummariesReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AllhelpListChatSummariesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*DBChatSummary       `protobuf:"bytes,1,rep,name=records,proto3" json:"records"` //@go_tags(`json:"records"`)
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`    //@go_tags(`json:"total"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpListChatSummariesResp) Reset() {
	*x = AllhelpListChatSummariesResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpListChatSummariesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpListChatSummariesResp) ProtoMessage() {}

func (x *AllhelpListChatSummariesResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpListChatSummariesResp.ProtoReflect.Descriptor instead.
func (*AllhelpListChatSummariesResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{13}
}

func (x *AllhelpListChatSummariesResp) GetRecords() []*DBChatSummary {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *AllhelpListChatSummariesResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 删除指定记录
type AllhelpDelChatSummaryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id"` //@go_tags(`json:"id"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpDelChatSummaryReq) Reset() {
	*x = AllhelpDelChatSummaryReq{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpDelChatSummaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpDelChatSummaryReq) ProtoMessage() {}

func (x *AllhelpDelChatSummaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpDelChatSummaryReq.ProtoReflect.Descriptor instead.
func (*AllhelpDelChatSummaryReq) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{14}
}

func (x *AllhelpDelChatSummaryReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AllhelpDelChatSummaryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllhelpDelChatSummaryResp) Reset() {
	*x = AllhelpDelChatSummaryResp{}
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllhelpDelChatSummaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllhelpDelChatSummaryResp) ProtoMessage() {}

func (x *AllhelpDelChatSummaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_allhelp_allhelp_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllhelpDelChatSummaryResp.ProtoReflect.Descriptor instead.
func (*AllhelpDelChatSummaryResp) Descriptor() ([]byte, []int) {
	return file_allhelp_allhelp_msg_proto_rawDescGZIP(), []int{15}
}

var File_allhelp_allhelp_msg_proto protoreflect.FileDescriptor

const file_allhelp_allhelp_msg_proto_rawDesc = "" +
	"\n" +
	"\x19allhelp/allhelp_msg.proto\x1a\x18allhelp/allhelp_db.proto\"T\n" +
	"\x12AllhelpGetTasksReq\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"J\n" +
	"\x13AllhelpGetTasksResp\x12\x1d\n" +
	"\x05tasks\x18\x01 \x03(\v2\a.DBTaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc0\x01\n" +
	"\x11AllhelpAddTaskReq\x12\x1b\n" +
	"\ttask_name\x18\x01 \x01(\tR\btaskName\x12\x1b\n" +
	"\ttask_desc\x18\x02 \x01(\tR\btaskDesc\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\x05R\btaskType\x12!\n" +
	"\ftrigger_time\x18\x04 \x01(\tR\vtriggerTime\x12\x1b\n" +
	"\tcron_expr\x18\x05 \x01(\tR\bcronExpr\x12\x14\n" +
	"\x05extra\x18\x06 \x01(\tR\x05extra\"1\n" +
	"\x12AllhelpAddTaskResp\x12\x1b\n" +
	"\x04task\x18\x01 \x01(\v2\a.DBTaskR\x04task\"/\n" +
	"\x14AllhelpCancelTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\x17\n" +
	"\x15AllhelpCancelTaskResp\"1\n" +
	"\x16AllhelpCompleteTaskReq\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x04R\x06taskId\"\x19\n" +
	"\x17AllhelpCompleteTaskResp\"^\n" +
	"\x1bAllhelpSubmitChatSummaryReq\x12!\n" +
	"\fsummary_date\x18\x01 \x01(\tR\vsummaryDate\x12\x1c\n" +
	"\x04msgs\x18\x02 \x03(\v2\b.ChatMsgR\x04msgs\"F\n" +
	"\x1cAllhelpSubmitChatSummaryResp\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.DBChatSummaryR\x06record\"=\n" +
	"\x18AllhelpGetChatSummaryReq\x12!\n" +
	"\fsummary_date\x18\x01 \x01(\tR\vsummaryDate\"C\n" +
	"\x19AllhelpGetChatSummaryResp\x12&\n" +
	"\x06record\x18\x01 \x01(\v2\x0e.DBChatSummaryR\x06record\"\x7f\n" +
	"\x1bAllhelpListChatSummariesReq\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"^\n" +
	"\x1cAllhelpListChatSummariesResp\x12(\n" +
	"\arecords\x18\x01 \x03(\v2\x0e.DBChatSummaryR\arecords\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"*\n" +
	"\x18AllhelpDelChatSummaryReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x1b\n" +
	"\x19AllhelpDelChatSummaryRespB\x06Z\x04.;pbb\x06proto3"

var (
	file_allhelp_allhelp_msg_proto_rawDescOnce sync.Once
	file_allhelp_allhelp_msg_proto_rawDescData []byte
)

func file_allhelp_allhelp_msg_proto_rawDescGZIP() []byte {
	file_allhelp_allhelp_msg_proto_rawDescOnce.Do(func() {
		file_allhelp_allhelp_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_allhelp_allhelp_msg_proto_rawDesc), len(file_allhelp_allhelp_msg_proto_rawDesc)))
	})
	return file_allhelp_allhelp_msg_proto_rawDescData
}

var file_allhelp_allhelp_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_allhelp_allhelp_msg_proto_goTypes = []any{
	(*AllhelpGetTasksReq)(nil),           // 0: AllhelpGetTasksReq
	(*AllhelpGetTasksResp)(nil),          // 1: AllhelpGetTasksResp
	(*AllhelpAddTaskReq)(nil),            // 2: AllhelpAddTaskReq
	(*AllhelpAddTaskResp)(nil),           // 3: AllhelpAddTaskResp
	(*AllhelpCancelTaskReq)(nil),         // 4: AllhelpCancelTaskReq
	(*AllhelpCancelTaskResp)(nil),        // 5: AllhelpCancelTaskResp
	(*AllhelpCompleteTaskReq)(nil),       // 6: AllhelpCompleteTaskReq
	(*AllhelpCompleteTaskResp)(nil),      // 7: AllhelpCompleteTaskResp
	(*AllhelpSubmitChatSummaryReq)(nil),  // 8: AllhelpSubmitChatSummaryReq
	(*AllhelpSubmitChatSummaryResp)(nil), // 9: AllhelpSubmitChatSummaryResp
	(*AllhelpGetChatSummaryReq)(nil),     // 10: AllhelpGetChatSummaryReq
	(*AllhelpGetChatSummaryResp)(nil),    // 11: AllhelpGetChatSummaryResp
	(*AllhelpListChatSummariesReq)(nil),  // 12: AllhelpListChatSummariesReq
	(*AllhelpListChatSummariesResp)(nil), // 13: AllhelpListChatSummariesResp
	(*AllhelpDelChatSummaryReq)(nil),     // 14: AllhelpDelChatSummaryReq
	(*AllhelpDelChatSummaryResp)(nil),    // 15: AllhelpDelChatSummaryResp
	(*DBTask)(nil),                       // 16: DBTask
	(*ChatMsg)(nil),                      // 17: ChatMsg
	(*DBChatSummary)(nil),                // 18: DBChatSummary
}
var file_allhelp_allhelp_msg_proto_depIdxs = []int32{
	16, // 0: AllhelpGetTasksResp.tasks:type_name -> DBTask
	16, // 1: AllhelpAddTaskResp.task:type_name -> DBTask
	17, // 2: AllhelpSubmitChatSummaryReq.msgs:type_name -> ChatMsg
	18, // 3: AllhelpSubmitChatSummaryResp.record:type_name -> DBChatSummary
	18, // 4: AllhelpGetChatSummaryResp.record:type_name -> DBChatSummary
	18, // 5: AllhelpListChatSummariesResp.records:type_name -> DBChatSummary
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_allhelp_allhelp_msg_proto_init() }
func file_allhelp_allhelp_msg_proto_init() {
	if File_allhelp_allhelp_msg_proto != nil {
		return
	}
	file_allhelp_allhelp_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_allhelp_allhelp_msg_proto_rawDesc), len(file_allhelp_allhelp_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_allhelp_allhelp_msg_proto_goTypes,
		DependencyIndexes: file_allhelp_allhelp_msg_proto_depIdxs,
		MessageInfos:      file_allhelp_allhelp_msg_proto_msgTypes,
	}.Build()
	File_allhelp_allhelp_msg_proto = out.File
	file_allhelp_allhelp_msg_proto_goTypes = nil
	file_allhelp_allhelp_msg_proto_depIdxs = nil
}
