// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: analyze/analyze_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StatsGlobalDay 每日全局统计（每 应用×产品×区域×日 一行）
type StatsGlobalDay struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- 维度 / 复合主键 ----
	AppId     string `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id" gorm:"column:app_id;size:64;primaryKey;index:idx_app_product_day,priority:1"`              //@go_tags(`gorm:"column:app_id;size:64;primaryKey;index:idx_app_product_day,priority:1" json:"app_id"`) 应用标识(应用名称)
	ProductId uint32 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id" gorm:"column:product_id;primaryKey;index:idx_app_product_day,priority:2"` //@go_tags(`gorm:"column:product_id;primaryKey;index:idx_app_product_day,priority:2" json:"product_id"`) 产品ID(无产品填0)
	Region    string `protobuf:"bytes,3,opt,name=region,proto3" json:"region" gorm:"column:region;size:16;primaryKey"`                         //@go_tags(`gorm:"column:region;size:16;primaryKey" json:"region"`) 区域代码(cn/us/...)
	StatDay   uint32 `protobuf:"varint,4,opt,name=stat_day,json=statDay,proto3" json:"stat_day" gorm:"column:stat_day;primaryKey;index:idx_app_product_day,priority:3"`       //@go_tags(`gorm:"column:stat_day;primaryKey;index:idx_app_product_day,priority:3" json:"stat_day"`) 统计日 YYYYMMDD
	// ---- 用户 ----
	LoginUserCount  int64 `protobuf:"varint,10,opt,name=login_user_count,json=loginUserCount,proto3" json:"login_user_count" gorm:"column:login_user_count"`    //@go_tags(`gorm:"column:login_user_count" json:"login_user_count"`) 登录用户数(当日去重)
	LoginCount      int64 `protobuf:"varint,11,opt,name=login_count,json=loginCount,proto3" json:"login_count" gorm:"column:login_count"`                  //@go_tags(`gorm:"column:login_count" json:"login_count"`) 登录次数
	NewUserCount    int64 `protobuf:"varint,12,opt,name=new_user_count,json=newUserCount,proto3" json:"new_user_count" gorm:"column:new_user_count"`          //@go_tags(`gorm:"column:new_user_count" json:"new_user_count"`) 新增注册用户数
	ActiveUserCount int64 `protobuf:"varint,13,opt,name=active_user_count,json=activeUserCount,proto3" json:"active_user_count" gorm:"column:active_user_count"` //@go_tags(`gorm:"column:active_user_count" json:"active_user_count"`) 活跃用户数(当日去重)
	// ---- 设备 ----
	ActiveDeviceCount int64 `protobuf:"varint,20,opt,name=active_device_count,json=activeDeviceCount,proto3" json:"active_device_count" gorm:"column:active_device_count"` //@go_tags(`gorm:"column:active_device_count" json:"active_device_count"`) 激活设备数
	BindDeviceCount   int64 `protobuf:"varint,21,opt,name=bind_device_count,json=bindDeviceCount,proto3" json:"bind_device_count" gorm:"column:bind_device_count"`       //@go_tags(`gorm:"column:bind_device_count" json:"bind_device_count"`) 绑定账号设备数
	// ---- 二维码(公码) ----
	QrActiveCount int64 `protobuf:"varint,22,opt,name=qr_active_count,json=qrActiveCount,proto3" json:"qr_active_count" gorm:"column:qr_active_count"` //@go_tags(`gorm:"column:qr_active_count" json:"qr_active_count"`) 二维码(公码)激活次数(只到应用×区域,product_id=0)
	// ---- 订单 / 支付 ----
	OrderCreateCount  int64 `protobuf:"varint,30,opt,name=order_create_count,json=orderCreateCount,proto3" json:"order_create_count" gorm:"column:order_create_count"`    //@go_tags(`gorm:"column:order_create_count" json:"order_create_count"`) 创建订单数
	OrderPaidCount    int64 `protobuf:"varint,31,opt,name=order_paid_count,json=orderPaidCount,proto3" json:"order_paid_count" gorm:"column:order_paid_count"`          //@go_tags(`gorm:"column:order_paid_count" json:"order_paid_count"`) 完成订单数
	OrderFailedCount  int64 `protobuf:"varint,32,opt,name=order_failed_count,json=orderFailedCount,proto3" json:"order_failed_count" gorm:"column:order_failed_count"`    //@go_tags(`gorm:"column:order_failed_count" json:"order_failed_count"`) 失败订单数
	OrderCreateAmount int64 `protobuf:"varint,33,opt,name=order_create_amount,json=orderCreateAmount,proto3" json:"order_create_amount" gorm:"column:order_create_amount"` //@go_tags(`gorm:"column:order_create_amount" json:"order_create_amount"`) 预计累计订单金额(所有创建订单,分)
	OrderPaidAmount   int64 `protobuf:"varint,34,opt,name=order_paid_amount,json=orderPaidAmount,proto3" json:"order_paid_amount" gorm:"column:order_paid_amount"`       //@go_tags(`gorm:"column:order_paid_amount" json:"order_paid_amount"`) 实际累计订单金额(已支付,分)
	PayUserCount      int64 `protobuf:"varint,35,opt,name=pay_user_count,json=payUserCount,proto3" json:"pay_user_count" gorm:"column:pay_user_count"`                //@go_tags(`gorm:"column:pay_user_count" json:"pay_user_count"`) 付费用户数(当日去重)
	// ---- 资源发放 ----
	GrantVipDay      int64 `protobuf:"varint,40,opt,name=grant_vip_day,json=grantVipDay,proto3" json:"grant_vip_day" gorm:"column:grant_vip_day"`                //@go_tags(`gorm:"column:grant_vip_day" json:"grant_vip_day"`) 发放VIP天数
	GrantAiIntegral  int64 `protobuf:"varint,41,opt,name=grant_ai_integral,json=grantAiIntegral,proto3" json:"grant_ai_integral" gorm:"column:grant_ai_integral"`    //@go_tags(`gorm:"column:grant_ai_integral" json:"grant_ai_integral"`) 发放AI积分
	GrantTradeSecond int64 `protobuf:"varint,42,opt,name=grant_trade_second,json=grantTradeSecond,proto3" json:"grant_trade_second" gorm:"column:grant_trade_second"` //@go_tags(`gorm:"column:grant_trade_second" json:"grant_trade_second"`) 发放翻译时长(秒)
	GrantMeetSecond  int64 `protobuf:"varint,43,opt,name=grant_meet_second,json=grantMeetSecond,proto3" json:"grant_meet_second" gorm:"column:grant_meet_second"`    //@go_tags(`gorm:"column:grant_meet_second" json:"grant_meet_second"`) 发放会议时长(秒)
	// ---- 功能消耗 ----
	AiChatCount int64 `protobuf:"varint,50,opt,name=ai_chat_count,json=aiChatCount,proto3" json:"ai_chat_count" gorm:"column:ai_chat_count"` //@go_tags(`gorm:"column:ai_chat_count" json:"ai_chat_count"`) AI聊天次数
	AiUpToken   int64 `protobuf:"varint,51,opt,name=ai_up_token,json=aiUpToken,proto3" json:"ai_up_token" gorm:"column:ai_up_token"`       //@go_tags(`gorm:"column:ai_up_token" json:"ai_up_token"`) AI上行token
	AiDownToken int64 `protobuf:"varint,52,opt,name=ai_down_token,json=aiDownToken,proto3" json:"ai_down_token" gorm:"column:ai_down_token"` //@go_tags(`gorm:"column:ai_down_token" json:"ai_down_token"`) AI下行token
	TradeCount  int64 `protobuf:"varint,53,opt,name=trade_count,json=tradeCount,proto3" json:"trade_count" gorm:"column:trade_count"`      //@go_tags(`gorm:"column:trade_count" json:"trade_count"`) 翻译次数
	TradeSecond int64 `protobuf:"varint,54,opt,name=trade_second,json=tradeSecond,proto3" json:"trade_second" gorm:"column:trade_second"`   //@go_tags(`gorm:"column:trade_second" json:"trade_second"`) 累计翻译使用时长(秒)
	TradeWords  int64 `protobuf:"varint,55,opt,name=trade_words,json=tradeWords,proto3" json:"trade_words" gorm:"column:trade_words"`      //@go_tags(`gorm:"column:trade_words" json:"trade_words"`) 翻译字数
	MeetCount   int64 `protobuf:"varint,56,opt,name=meet_count,json=meetCount,proto3" json:"meet_count" gorm:"column:meet_count"`         //@go_tags(`gorm:"column:meet_count" json:"meet_count"`) 会议次数
	MeetSecond  int64 `protobuf:"varint,57,opt,name=meet_second,json=meetSecond,proto3" json:"meet_second" gorm:"column:meet_second"`      //@go_tags(`gorm:"column:meet_second" json:"meet_second"`) 累计会议使用时长(秒)
	// ---- 元信息 ----
	UpdateTime    int64 `protobuf:"varint,99,opt,name=update_time,json=updateTime,proto3" json:"update_time" gorm:"column:update_time"` //@go_tags(`gorm:"column:update_time" json:"update_time"`) 最后更新时间(unix秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsGlobalDay) Reset() {
	*x = StatsGlobalDay{}
	mi := &file_analyze_analyze_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsGlobalDay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsGlobalDay) ProtoMessage() {}

func (x *StatsGlobalDay) ProtoReflect() protoreflect.Message {
	mi := &file_analyze_analyze_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsGlobalDay.ProtoReflect.Descriptor instead.
func (*StatsGlobalDay) Descriptor() ([]byte, []int) {
	return file_analyze_analyze_db_proto_rawDescGZIP(), []int{0}
}

func (x *StatsGlobalDay) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StatsGlobalDay) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *StatsGlobalDay) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *StatsGlobalDay) GetStatDay() uint32 {
	if x != nil {
		return x.StatDay
	}
	return 0
}

func (x *StatsGlobalDay) GetLoginUserCount() int64 {
	if x != nil {
		return x.LoginUserCount
	}
	return 0
}

func (x *StatsGlobalDay) GetLoginCount() int64 {
	if x != nil {
		return x.LoginCount
	}
	return 0
}

func (x *StatsGlobalDay) GetNewUserCount() int64 {
	if x != nil {
		return x.NewUserCount
	}
	return 0
}

func (x *StatsGlobalDay) GetActiveUserCount() int64 {
	if x != nil {
		return x.ActiveUserCount
	}
	return 0
}

func (x *StatsGlobalDay) GetActiveDeviceCount() int64 {
	if x != nil {
		return x.ActiveDeviceCount
	}
	return 0
}

func (x *StatsGlobalDay) GetBindDeviceCount() int64 {
	if x != nil {
		return x.BindDeviceCount
	}
	return 0
}

func (x *StatsGlobalDay) GetQrActiveCount() int64 {
	if x != nil {
		return x.QrActiveCount
	}
	return 0
}

func (x *StatsGlobalDay) GetOrderCreateCount() int64 {
	if x != nil {
		return x.OrderCreateCount
	}
	return 0
}

func (x *StatsGlobalDay) GetOrderPaidCount() int64 {
	if x != nil {
		return x.OrderPaidCount
	}
	return 0
}

func (x *StatsGlobalDay) GetOrderFailedCount() int64 {
	if x != nil {
		return x.OrderFailedCount
	}
	return 0
}

func (x *StatsGlobalDay) GetOrderCreateAmount() int64 {
	if x != nil {
		return x.OrderCreateAmount
	}
	return 0
}

func (x *StatsGlobalDay) GetOrderPaidAmount() int64 {
	if x != nil {
		return x.OrderPaidAmount
	}
	return 0
}

func (x *StatsGlobalDay) GetPayUserCount() int64 {
	if x != nil {
		return x.PayUserCount
	}
	return 0
}

func (x *StatsGlobalDay) GetGrantVipDay() int64 {
	if x != nil {
		return x.GrantVipDay
	}
	return 0
}

func (x *StatsGlobalDay) GetGrantAiIntegral() int64 {
	if x != nil {
		return x.GrantAiIntegral
	}
	return 0
}

func (x *StatsGlobalDay) GetGrantTradeSecond() int64 {
	if x != nil {
		return x.GrantTradeSecond
	}
	return 0
}

func (x *StatsGlobalDay) GetGrantMeetSecond() int64 {
	if x != nil {
		return x.GrantMeetSecond
	}
	return 0
}

func (x *StatsGlobalDay) GetAiChatCount() int64 {
	if x != nil {
		return x.AiChatCount
	}
	return 0
}

func (x *StatsGlobalDay) GetAiUpToken() int64 {
	if x != nil {
		return x.AiUpToken
	}
	return 0
}

func (x *StatsGlobalDay) GetAiDownToken() int64 {
	if x != nil {
		return x.AiDownToken
	}
	return 0
}

func (x *StatsGlobalDay) GetTradeCount() int64 {
	if x != nil {
		return x.TradeCount
	}
	return 0
}

func (x *StatsGlobalDay) GetTradeSecond() int64 {
	if x != nil {
		return x.TradeSecond
	}
	return 0
}

func (x *StatsGlobalDay) GetTradeWords() int64 {
	if x != nil {
		return x.TradeWords
	}
	return 0
}

func (x *StatsGlobalDay) GetMeetCount() int64 {
	if x != nil {
		return x.MeetCount
	}
	return 0
}

func (x *StatsGlobalDay) GetMeetSecond() int64 {
	if x != nil {
		return x.MeetSecond
	}
	return 0
}

func (x *StatsGlobalDay) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_analyze_analyze_db_proto protoreflect.FileDescriptor

const file_analyze_analyze_db_proto_rawDesc = "" +
	"\n" +
	"\x18analyze/analyze_db.proto\x1a\n" +
	"enum.proto\"\xfa\b\n" +
	"\x0eStatsGlobalDay\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x19\n" +
	"\bstat_day\x18\x04 \x01(\rR\astatDay\x12(\n" +
	"\x10login_user_count\x18\n" +
	" \x01(\x03R\x0eloginUserCount\x12\x1f\n" +
	"\vlogin_count\x18\v \x01(\x03R\n" +
	"loginCount\x12$\n" +
	"\x0enew_user_count\x18\f \x01(\x03R\fnewUserCount\x12*\n" +
	"\x11active_user_count\x18\r \x01(\x03R\x0factiveUserCount\x12.\n" +
	"\x13active_device_count\x18\x14 \x01(\x03R\x11activeDeviceCount\x12*\n" +
	"\x11bind_device_count\x18\x15 \x01(\x03R\x0fbindDeviceCount\x12&\n" +
	"\x0fqr_active_count\x18\x16 \x01(\x03R\rqrActiveCount\x12,\n" +
	"\x12order_create_count\x18\x1e \x01(\x03R\x10orderCreateCount\x12(\n" +
	"\x10order_paid_count\x18\x1f \x01(\x03R\x0eorderPaidCount\x12,\n" +
	"\x12order_failed_count\x18  \x01(\x03R\x10orderFailedCount\x12.\n" +
	"\x13order_create_amount\x18! \x01(\x03R\x11orderCreateAmount\x12*\n" +
	"\x11order_paid_amount\x18\" \x01(\x03R\x0forderPaidAmount\x12$\n" +
	"\x0epay_user_count\x18# \x01(\x03R\fpayUserCount\x12\"\n" +
	"\rgrant_vip_day\x18( \x01(\x03R\vgrantVipDay\x12*\n" +
	"\x11grant_ai_integral\x18) \x01(\x03R\x0fgrantAiIntegral\x12,\n" +
	"\x12grant_trade_second\x18* \x01(\x03R\x10grantTradeSecond\x12*\n" +
	"\x11grant_meet_second\x18+ \x01(\x03R\x0fgrantMeetSecond\x12\"\n" +
	"\rai_chat_count\x182 \x01(\x03R\vaiChatCount\x12\x1e\n" +
	"\vai_up_token\x183 \x01(\x03R\taiUpToken\x12\"\n" +
	"\rai_down_token\x184 \x01(\x03R\vaiDownToken\x12\x1f\n" +
	"\vtrade_count\x185 \x01(\x03R\n" +
	"tradeCount\x12!\n" +
	"\ftrade_second\x186 \x01(\x03R\vtradeSecond\x12\x1f\n" +
	"\vtrade_words\x187 \x01(\x03R\n" +
	"tradeWords\x12\x1d\n" +
	"\n" +
	"meet_count\x188 \x01(\x03R\tmeetCount\x12\x1f\n" +
	"\vmeet_second\x189 \x01(\x03R\n" +
	"meetSecond\x12\x1f\n" +
	"\vupdate_time\x18c \x01(\x03R\n" +
	"updateTimeB\x06Z\x04.;pbb\x06proto3"

var (
	file_analyze_analyze_db_proto_rawDescOnce sync.Once
	file_analyze_analyze_db_proto_rawDescData []byte
)

func file_analyze_analyze_db_proto_rawDescGZIP() []byte {
	file_analyze_analyze_db_proto_rawDescOnce.Do(func() {
		file_analyze_analyze_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analyze_analyze_db_proto_rawDesc), len(file_analyze_analyze_db_proto_rawDesc)))
	})
	return file_analyze_analyze_db_proto_rawDescData
}

var file_analyze_analyze_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_analyze_analyze_db_proto_goTypes = []any{
	(*StatsGlobalDay)(nil), // 0: StatsGlobalDay
}
var file_analyze_analyze_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analyze_analyze_db_proto_init() }
func file_analyze_analyze_db_proto_init() {
	if File_analyze_analyze_db_proto != nil {
		return
	}
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analyze_analyze_db_proto_rawDesc), len(file_analyze_analyze_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analyze_analyze_db_proto_goTypes,
		DependencyIndexes: file_analyze_analyze_db_proto_depIdxs,
		MessageInfos:      file_analyze_analyze_db_proto_msgTypes,
	}.Build()
	File_analyze_analyze_db_proto = out.File
	file_analyze_analyze_db_proto_goTypes = nil
	file_analyze_analyze_db_proto_depIdxs = nil
}
