// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: api/api_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Identity int32

const (
	Identity_Identity_Null Identity = 0
	Identity_Admin         Identity = 1 //超管权限（唯一可管理后台账号）
	Identity_Manager       Identity = 2 //管理员权限（除账号管理外全部权限，不受工厂/产品限制）
	Identity_Agent         Identity = 3 //代理权限（外部公司，按勾选下发页面/工厂/产品）
	Identity_Operator      Identity = 4 //运营权限（公司内部，按勾选下发页面/工厂/产品）
)

// Enum value maps for Identity.
var (
	Identity_name = map[int32]string{
		0: "Identity_Null",
		1: "Admin",
		2: "Manager",
		3: "Agent",
		4: "Operator",
	}
	Identity_value = map[string]int32{
		"Identity_Null": 0,
		"Admin":         1,
		"Manager":       2,
		"Agent":         3,
		"Operator":      4,
	}
)

func (x Identity) Enum() *Identity {
	p := new(Identity)
	*p = x
	return p
}

func (x Identity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Identity) Descriptor() protoreflect.EnumDescriptor {
	return file_api_api_db_proto_enumTypes[0].Descriptor()
}

func (Identity) Type() protoreflect.EnumType {
	return &file_api_api_db_proto_enumTypes[0]
}

func (x Identity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Identity.Descriptor instead.
func (Identity) EnumDescriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{0}
}

// 后台账号
type DBAdminUser struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Account    string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty" gorm:"primary_key"`                  //@go_tags(`gorm:"primary_key"`) 账号
	Password   string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`                //@go_tags(`json:"password"`) 密码
	Identity   Identity               `protobuf:"varint,3,opt,name=identity,proto3,enum=Identity" json:"identity"` //@go_tags(`json:"identity"`) 身份
	Access     string                 `protobuf:"bytes,5,opt,name=access,proto3" json:"access"`                    //@go_tags(`json:"access"`) 权限列表,分割
	Factoryids string                 `protobuf:"bytes,6,opt,name=factoryids,proto3" json:"factoryids"`            //@go_tags(`json:"factoryids"`) 所属工厂列表,分割
	Productids string                 `protobuf:"bytes,7,opt,name=productids,proto3" json:"productids"`            //@go_tags(`json:"productids"`) 所属产品列表,分割（代理用）
	// 资源点池（超管以外，赠送资源时从池中扣减；超管不受限）
	VipdayBalance         int64 `protobuf:"varint,8,opt,name=vipday_balance,json=vipdayBalance,proto3" json:"vipday_balance" gorm:"vipday_balance"`                         //@go_tags(`gorm:"vipday_balance" json:"vipday_balance"`) VIP天数余额
	AichatintegralBalance int64 `protobuf:"varint,9,opt,name=aichatintegral_balance,json=aichatintegralBalance,proto3" json:"aichatintegral_balance" gorm:"aichatintegral_balance"` //@go_tags(`gorm:"aichatintegral_balance" json:"aichatintegral_balance"`) AI资源点余额
	TradesecondBalance    int64 `protobuf:"varint,10,opt,name=tradesecond_balance,json=tradesecondBalance,proto3" json:"tradesecond_balance" gorm:"tradesecond_balance"`         //@go_tags(`gorm:"tradesecond_balance" json:"tradesecond_balance"`) 翻译时长余额(秒)
	MeetsecondBalance     int64 `protobuf:"varint,11,opt,name=meetsecond_balance,json=meetsecondBalance,proto3" json:"meetsecond_balance" gorm:"meetsecond_balance"`            //@go_tags(`gorm:"meetsecond_balance" json:"meetsecond_balance"`) 会议时长余额(秒)
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DBAdminUser) Reset() {
	*x = DBAdminUser{}
	mi := &file_api_api_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBAdminUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBAdminUser) ProtoMessage() {}

func (x *DBAdminUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBAdminUser.ProtoReflect.Descriptor instead.
func (*DBAdminUser) Descriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBAdminUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBAdminUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DBAdminUser) GetIdentity() Identity {
	if x != nil {
		return x.Identity
	}
	return Identity_Identity_Null
}

func (x *DBAdminUser) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *DBAdminUser) GetFactoryids() string {
	if x != nil {
		return x.Factoryids
	}
	return ""
}

func (x *DBAdminUser) GetProductids() string {
	if x != nil {
		return x.Productids
	}
	return ""
}

func (x *DBAdminUser) GetVipdayBalance() int64 {
	if x != nil {
		return x.VipdayBalance
	}
	return 0
}

func (x *DBAdminUser) GetAichatintegralBalance() int64 {
	if x != nil {
		return x.AichatintegralBalance
	}
	return 0
}

func (x *DBAdminUser) GetTradesecondBalance() int64 {
	if x != nil {
		return x.TradesecondBalance
	}
	return 0
}

func (x *DBAdminUser) GetMeetsecondBalance() int64 {
	if x != nil {
		return x.MeetsecondBalance
	}
	return 0
}

// 后台账号资源点流水（超管→管理员/代理/运营）
type DBAdminResourceLog struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;autoIncrement"`                                     //@go_tags(`gorm:"primaryKey;autoIncrement"`) 自增主键
	Ts             int64                  `protobuf:"varint,2,opt,name=ts,proto3" json:"ts" gorm:"ts;index"`                                     //@go_tags(`gorm:"ts;index" json:"ts"`) 时间戳
	FromAccount    string                 `protobuf:"bytes,3,opt,name=from_account,json=fromAccount,proto3" json:"from_account" gorm:"from_account:50;index"` //@go_tags(`gorm:"from_account:50;index" json:"from_account"`) 发起人账号（超管）
	ToAccount      string                 `protobuf:"bytes,4,opt,name=to_account,json=toAccount,proto3" json:"to_account" gorm:"to_account:50;index"`       //@go_tags(`gorm:"to_account:50;index" json:"to_account"`) 接收人账号
	Vipday         int64                  `protobuf:"varint,5,opt,name=vipday,proto3" json:"vipday" gorm:"vipday"`                             //@go_tags(`gorm:"vipday" json:"vipday"`) 赠送的VIP天数
	Aichatintegral int64                  `protobuf:"varint,6,opt,name=aichatintegral,proto3" json:"aichatintegral" gorm:"aichatintegral"`             //@go_tags(`gorm:"aichatintegral" json:"aichatintegral"`) 赠送的AI资源点
	Tradesecond    int64                  `protobuf:"varint,7,opt,name=tradesecond,proto3" json:"tradesecond" gorm:"tradesecond"`                   //@go_tags(`gorm:"tradesecond" json:"tradesecond"`) 赠送的翻译秒数
	Meetsecond     int64                  `protobuf:"varint,8,opt,name=meetsecond,proto3" json:"meetsecond" gorm:"meetsecond"`                     //@go_tags(`gorm:"meetsecond" json:"meetsecond"`) 赠送的会议秒数
	Remark         string                 `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark" gorm:"remark"`                              //@go_tags(`gorm:"remark" json:"remark"`) 备注
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DBAdminResourceLog) Reset() {
	*x = DBAdminResourceLog{}
	mi := &file_api_api_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBAdminResourceLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBAdminResourceLog) ProtoMessage() {}

func (x *DBAdminResourceLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBAdminResourceLog.ProtoReflect.Descriptor instead.
func (*DBAdminResourceLog) Descriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBAdminResourceLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBAdminResourceLog) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *DBAdminResourceLog) GetFromAccount() string {
	if x != nil {
		return x.FromAccount
	}
	return ""
}

func (x *DBAdminResourceLog) GetToAccount() string {
	if x != nil {
		return x.ToAccount
	}
	return ""
}

func (x *DBAdminResourceLog) GetVipday() int64 {
	if x != nil {
		return x.Vipday
	}
	return 0
}

func (x *DBAdminResourceLog) GetAichatintegral() int64 {
	if x != nil {
		return x.Aichatintegral
	}
	return 0
}

func (x *DBAdminResourceLog) GetTradesecond() int64 {
	if x != nil {
		return x.Tradesecond
	}
	return 0
}

func (x *DBAdminResourceLog) GetMeetsecond() int64 {
	if x != nil {
		return x.Meetsecond
	}
	return 0
}

func (x *DBAdminResourceLog) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 产品激活/绑定统计（重建统计时全量扫描 userdevice 落库，仪表盘读取）
type DBProductStat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Productid      uint32                 `protobuf:"varint,1,opt,name=productid,proto3" json:"productid" gorm:"productid;primaryKey;autoIncrement:false"`                                   //@go_tags(`gorm:"productid;primaryKey;autoIncrement:false" json:"productid"`) 产品ID
	ActivatedCount int64                  `protobuf:"varint,2,opt,name=activated_count,json=activatedCount,proto3" json:"activated_count" gorm:"activated_count"`   //@go_tags(`gorm:"activated_count" json:"activated_count"`) 激活设备数（userdevice 行数）
	BoundUserCount int64                  `protobuf:"varint,3,opt,name=bound_user_count,json=boundUserCount,proto3" json:"bound_user_count" gorm:"bound_user_count"` //@go_tags(`gorm:"bound_user_count" json:"bound_user_count"`) 绑定用户数（去重 uid）
	UpdateTime     int64                  `protobuf:"varint,4,opt,name=update_time,json=updateTime,proto3" json:"update_time" gorm:"update_time"`               //@go_tags(`gorm:"update_time" json:"update_time"`) 最近重建时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DBProductStat) Reset() {
	*x = DBProductStat{}
	mi := &file_api_api_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBProductStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBProductStat) ProtoMessage() {}

func (x *DBProductStat) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBProductStat.ProtoReflect.Descriptor instead.
func (*DBProductStat) Descriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{2}
}

func (x *DBProductStat) GetProductid() uint32 {
	if x != nil {
		return x.Productid
	}
	return 0
}

func (x *DBProductStat) GetActivatedCount() int64 {
	if x != nil {
		return x.ActivatedCount
	}
	return 0
}

func (x *DBProductStat) GetBoundUserCount() int64 {
	if x != nil {
		return x.BoundUserCount
	}
	return 0
}

func (x *DBProductStat) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

// 后台操作日志
type DBConsoleLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primary_key;AUTO_INCREMENT"`                                //@go_tags(`gorm:"primary_key;AUTO_INCREMENT"`) 自增主键
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty" gorm:"index:idx_account"`                       //@go_tags(`gorm:"index:idx_account"`) 操作人账号
	ApiName       string                 `protobuf:"bytes,3,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty" gorm:"index:idx_api"`        //@go_tags(`gorm:"index:idx_api"`) 接口名称
	Request       string                 `protobuf:"bytes,4,opt,name=request,proto3" json:"request,omitempty" gorm:"type:text"`                       //@go_tags(`gorm:"type:text"`) 请求参数JSON
	Response      string                 `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty" gorm:"type:text"`                     //@go_tags(`gorm:"type:text"`) 响应结果JSON
	Code          int32                  `protobuf:"varint,6,opt,name=code,proto3" json:"code,omitempty"`                            // 响应状态码 0=成功
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`                                 // 操作IP
	CostMs        int64                  `protobuf:"varint,8,opt,name=cost_ms,json=costMs,proto3" json:"cost_ms,omitempty"`          // 耗时毫秒
	CreatedAt     int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"index:idx_time"` //@go_tags(`gorm:"index:idx_time"`) 操作时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBConsoleLog) Reset() {
	*x = DBConsoleLog{}
	mi := &file_api_api_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBConsoleLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBConsoleLog) ProtoMessage() {}

func (x *DBConsoleLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_api_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBConsoleLog.ProtoReflect.Descriptor instead.
func (*DBConsoleLog) Descriptor() ([]byte, []int) {
	return file_api_api_db_proto_rawDescGZIP(), []int{3}
}

func (x *DBConsoleLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBConsoleLog) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *DBConsoleLog) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *DBConsoleLog) GetRequest() string {
	if x != nil {
		return x.Request
	}
	return ""
}

func (x *DBConsoleLog) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *DBConsoleLog) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DBConsoleLog) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DBConsoleLog) GetCostMs() int64 {
	if x != nil {
		return x.CostMs
	}
	return 0
}

func (x *DBConsoleLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_api_api_db_proto protoreflect.FileDescriptor

const file_api_api_db_proto_rawDesc = "" +
	"\n" +
	"\x10api/api_db.proto\"\x80\x03\n" +
	"\vDBAdminUser\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\bidentity\x18\x03 \x01(\x0e2\t.IdentityR\bidentity\x12\x16\n" +
	"\x06access\x18\x05 \x01(\tR\x06access\x12\x1e\n" +
	"\n" +
	"factoryids\x18\x06 \x01(\tR\n" +
	"factoryids\x12\x1e\n" +
	"\n" +
	"productids\x18\a \x01(\tR\n" +
	"productids\x12%\n" +
	"\x0evipday_balance\x18\b \x01(\x03R\rvipdayBalance\x125\n" +
	"\x16aichatintegral_balance\x18\t \x01(\x03R\x15aichatintegralBalance\x12/\n" +
	"\x13tradesecond_balance\x18\n" +
	" \x01(\x03R\x12tradesecondBalance\x12-\n" +
	"\x12meetsecond_balance\x18\v \x01(\x03R\x11meetsecondBalance\"\x90\x02\n" +
	"\x12DBAdminResourceLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x0e\n" +
	"\x02ts\x18\x02 \x01(\x03R\x02ts\x12!\n" +
	"\ffrom_account\x18\x03 \x01(\tR\vfromAccount\x12\x1d\n" +
	"\n" +
	"to_account\x18\x04 \x01(\tR\ttoAccount\x12\x16\n" +
	"\x06vipday\x18\x05 \x01(\x03R\x06vipday\x12&\n" +
	"\x0eaichatintegral\x18\x06 \x01(\x03R\x0eaichatintegral\x12 \n" +
	"\vtradesecond\x18\a \x01(\x03R\vtradesecond\x12\x1e\n" +
	"\n" +
	"meetsecond\x18\b \x01(\x03R\n" +
	"meetsecond\x12\x16\n" +
	"\x06remark\x18\t \x01(\tR\x06remark\"\xa1\x01\n" +
	"\rDBProductStat\x12\x1c\n" +
	"\tproductid\x18\x01 \x01(\rR\tproductid\x12'\n" +
	"\x0factivated_count\x18\x02 \x01(\x03R\x0eactivatedCount\x12(\n" +
	"\x10bound_user_count\x18\x03 \x01(\x03R\x0eboundUserCount\x12\x1f\n" +
	"\vupdate_time\x18\x04 \x01(\x03R\n" +
	"updateTime\"\xe5\x01\n" +
	"\fDBConsoleLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x19\n" +
	"\bapi_name\x18\x03 \x01(\tR\aapiName\x12\x18\n" +
	"\arequest\x18\x04 \x01(\tR\arequest\x12\x1a\n" +
	"\bresponse\x18\x05 \x01(\tR\bresponse\x12\x12\n" +
	"\x04code\x18\x06 \x01(\x05R\x04code\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\x12\x17\n" +
	"\acost_ms\x18\b \x01(\x03R\x06costMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt*N\n" +
	"\bIdentity\x12\x11\n" +
	"\rIdentity_Null\x10\x00\x12\t\n" +
	"\x05Admin\x10\x01\x12\v\n" +
	"\aManager\x10\x02\x12\t\n" +
	"\x05Agent\x10\x03\x12\f\n" +
	"\bOperator\x10\x04B\x06Z\x04.;pbb\x06proto3"

var (
	file_api_api_db_proto_rawDescOnce sync.Once
	file_api_api_db_proto_rawDescData []byte
)

func file_api_api_db_proto_rawDescGZIP() []byte {
	file_api_api_db_proto_rawDescOnce.Do(func() {
		file_api_api_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_api_db_proto_rawDesc), len(file_api_api_db_proto_rawDesc)))
	})
	return file_api_api_db_proto_rawDescData
}

var file_api_api_db_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_api_db_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_api_db_proto_goTypes = []any{
	(Identity)(0),              // 0: Identity
	(*DBAdminUser)(nil),        // 1: DBAdminUser
	(*DBAdminResourceLog)(nil), // 2: DBAdminResourceLog
	(*DBProductStat)(nil),      // 3: DBProductStat
	(*DBConsoleLog)(nil),       // 4: DBConsoleLog
}
var file_api_api_db_proto_depIdxs = []int32{
	0, // 0: DBAdminUser.identity:type_name -> Identity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_api_db_proto_init() }
func file_api_api_db_proto_init() {
	if File_api_api_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_api_db_proto_rawDesc), len(file_api_api_db_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_api_db_proto_goTypes,
		DependencyIndexes: file_api_api_db_proto_depIdxs,
		EnumInfos:         file_api_api_db_proto_enumTypes,
		MessageInfos:      file_api_api_db_proto_msgTypes,
	}.Build()
	File_api_api_db_proto = out.File
	file_api_api_db_proto_goTypes = nil
	file_api_api_db_proto_depIdxs = nil
}
