// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: auth/auth_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenReq) Reset() {
	*x = AuthTokenReq{}
	mi := &file_auth_auth_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenReq) ProtoMessage() {}

func (x *AuthTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenReq.ProtoReflect.Descriptor instead.
func (*AuthTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{0}
}

type AuthTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokenResp) Reset() {
	*x = AuthTokenResp{}
	mi := &file_auth_auth_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokenResp) ProtoMessage() {}

func (x *AuthTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokenResp.ProtoReflect.Descriptor instead.
func (*AuthTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{1}
}

func (x *AuthTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取阿里云的临时 token
type AuthAliTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAliTokenReq) Reset() {
	*x = AuthAliTokenReq{}
	mi := &file_auth_auth_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAliTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAliTokenReq) ProtoMessage() {}

func (x *AuthAliTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAliTokenReq.ProtoReflect.Descriptor instead.
func (*AuthAliTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{2}
}

type AuthAliTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appkey        string                 `protobuf:"bytes,1,opt,name=appkey,proto3" json:"appkey,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthAliTokenResp) Reset() {
	*x = AuthAliTokenResp{}
	mi := &file_auth_auth_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthAliTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthAliTokenResp) ProtoMessage() {}

func (x *AuthAliTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthAliTokenResp.ProtoReflect.Descriptor instead.
func (*AuthAliTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{3}
}

func (x *AuthAliTokenResp) GetAppkey() string {
	if x != nil {
		return x.Appkey
	}
	return ""
}

func (x *AuthAliTokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 获取阿里云的临时 token
type AuthTencentyunCosStsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTencentyunCosStsReq) Reset() {
	*x = AuthTencentyunCosStsReq{}
	mi := &file_auth_auth_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTencentyunCosStsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTencentyunCosStsReq) ProtoMessage() {}

func (x *AuthTencentyunCosStsReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTencentyunCosStsReq.ProtoReflect.Descriptor instead.
func (*AuthTencentyunCosStsReq) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{4}
}

type AuthTencentyunCosStsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tmpsecretid   string                 `protobuf:"bytes,1,opt,name=tmpsecretid,proto3" json:"tmpsecretid,omitempty"`
	Tmpsecretkey  string                 `protobuf:"bytes,2,opt,name=tmpsecretkey,proto3" json:"tmpsecretkey,omitempty"`
	Sessiontoken  string                 `protobuf:"bytes,3,opt,name=sessiontoken,proto3" json:"sessiontoken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTencentyunCosStsResp) Reset() {
	*x = AuthTencentyunCosStsResp{}
	mi := &file_auth_auth_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTencentyunCosStsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTencentyunCosStsResp) ProtoMessage() {}

func (x *AuthTencentyunCosStsResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTencentyunCosStsResp.ProtoReflect.Descriptor instead.
func (*AuthTencentyunCosStsResp) Descriptor() ([]byte, []int) {
	return file_auth_auth_msg_proto_rawDescGZIP(), []int{5}
}

func (x *AuthTencentyunCosStsResp) GetTmpsecretid() string {
	if x != nil {
		return x.Tmpsecretid
	}
	return ""
}

func (x *AuthTencentyunCosStsResp) GetTmpsecretkey() string {
	if x != nil {
		return x.Tmpsecretkey
	}
	return ""
}

func (x *AuthTencentyunCosStsResp) GetSessiontoken() string {
	if x != nil {
		return x.Sessiontoken
	}
	return ""
}

var File_auth_auth_msg_proto protoreflect.FileDescriptor

const file_auth_auth_msg_proto_rawDesc = "" +
	"\n" +
	"\x13auth/auth_msg.proto\"\x0e\n" +
	"\fAuthTokenReq\"%\n" +
	"\rAuthTokenResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x11\n" +
	"\x0fAuthAliTokenReq\"@\n" +
	"\x10AuthAliTokenResp\x12\x16\n" +
	"\x06appkey\x18\x01 \x01(\tR\x06appkey\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x19\n" +
	"\x17AuthTencentyunCosStsReq\"\x84\x01\n" +
	"\x18AuthTencentyunCosStsResp\x12 \n" +
	"\vtmpsecretid\x18\x01 \x01(\tR\vtmpsecretid\x12\"\n" +
	"\ftmpsecretkey\x18\x02 \x01(\tR\ftmpsecretkey\x12\"\n" +
	"\fsessiontoken\x18\x03 \x01(\tR\fsessiontokenB\x06Z\x04.;pbb\x06proto3"

var (
	file_auth_auth_msg_proto_rawDescOnce sync.Once
	file_auth_auth_msg_proto_rawDescData []byte
)

func file_auth_auth_msg_proto_rawDescGZIP() []byte {
	file_auth_auth_msg_proto_rawDescOnce.Do(func() {
		file_auth_auth_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_msg_proto_rawDesc), len(file_auth_auth_msg_proto_rawDesc)))
	})
	return file_auth_auth_msg_proto_rawDescData
}

var file_auth_auth_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_auth_auth_msg_proto_goTypes = []any{
	(*AuthTokenReq)(nil),             // 0: AuthTokenReq
	(*AuthTokenResp)(nil),            // 1: AuthTokenResp
	(*AuthAliTokenReq)(nil),          // 2: AuthAliTokenReq
	(*AuthAliTokenResp)(nil),         // 3: AuthAliTokenResp
	(*AuthTencentyunCosStsReq)(nil),  // 4: AuthTencentyunCosStsReq
	(*AuthTencentyunCosStsResp)(nil), // 5: AuthTencentyunCosStsResp
}
var file_auth_auth_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_auth_msg_proto_init() }
func file_auth_auth_msg_proto_init() {
	if File_auth_auth_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_msg_proto_rawDesc), len(file_auth_auth_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_auth_msg_proto_goTypes,
		DependencyIndexes: file_auth_auth_msg_proto_depIdxs,
		MessageInfos:      file_auth_auth_msg_proto_msgTypes,
	}.Build()
	File_auth_auth_msg_proto = out.File
	file_auth_auth_msg_proto_goTypes = nil
	file_auth_auth_msg_proto_depIdxs = nil
}
