// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: bailian/bailian_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 设备端上送的注册请求 —— 原样转发给 POP
type BailianDeviceRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId" binding:"required"`             //@go_tags(`json:"appId" binding:"required"`) 产品标识
	DeviceName    string                 `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName"`   //@go_tags(`json:"deviceName"`) 设备唯一标识（可选，透传用）
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce" binding:"required"`             //@go_tags(`json:"nonce" binding:"required"`) 16 字节随机数 32 字符
	RequestTime   string                 `protobuf:"bytes,4,opt,name=requestTime,proto3" json:"requestTime" binding:"required"` //@go_tags(`json:"requestTime" binding:"required"`) 毫秒时间戳字符串
	SdkVersion    string                 `protobuf:"bytes,5,opt,name=sdkVersion,proto3" json:"sdkVersion"`   //@go_tags(`json:"sdkVersion"`) 设备端 SDK 版本
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature" binding:"required"`     //@go_tags(`json:"signature" binding:"required"`) 设备端签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BailianDeviceRegisterReq) Reset() {
	*x = BailianDeviceRegisterReq{}
	mi := &file_bailian_bailian_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BailianDeviceRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BailianDeviceRegisterReq) ProtoMessage() {}

func (x *BailianDeviceRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_bailian_bailian_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BailianDeviceRegisterReq.ProtoReflect.Descriptor instead.
func (*BailianDeviceRegisterReq) Descriptor() ([]byte, []int) {
	return file_bailian_bailian_msg_proto_rawDescGZIP(), []int{0}
}

func (x *BailianDeviceRegisterReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BailianDeviceRegisterReq) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *BailianDeviceRegisterReq) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *BailianDeviceRegisterReq) GetRequestTime() string {
	if x != nil {
		return x.RequestTime
	}
	return ""
}

func (x *BailianDeviceRegisterReq) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *BailianDeviceRegisterReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// 透传给设备端：结构必须与 POP 返回的 data 字段一致，设备端 SDK 解签
type BailianDeviceRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce"`               //@go_tags(`json:"nonce"`)
	ResponseTime  string                 `protobuf:"bytes,2,opt,name=responseTime,proto3" json:"responseTime"` //@go_tags(`json:"responseTime"`)
	AppId         string                 `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId"`               //@go_tags(`json:"appId"`)
	DeviceName    string                 `protobuf:"bytes,4,opt,name=deviceName,proto3" json:"deviceName"`     //@go_tags(`json:"deviceName"`)
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature"`       //@go_tags(`json:"signature"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BailianDeviceRegisterResp) Reset() {
	*x = BailianDeviceRegisterResp{}
	mi := &file_bailian_bailian_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BailianDeviceRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BailianDeviceRegisterResp) ProtoMessage() {}

func (x *BailianDeviceRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_bailian_bailian_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BailianDeviceRegisterResp.ProtoReflect.Descriptor instead.
func (*BailianDeviceRegisterResp) Descriptor() ([]byte, []int) {
	return file_bailian_bailian_msg_proto_rawDescGZIP(), []int{1}
}

func (x *BailianDeviceRegisterResp) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *BailianDeviceRegisterResp) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

func (x *BailianDeviceRegisterResp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BailianDeviceRegisterResp) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *BailianDeviceRegisterResp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// 设备端上送的获取令牌请求 —— 原样转发给 POP，tokenKey 由服务端补注
type BailianGetTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId" binding:"required"`             //@go_tags(`json:"appId" binding:"required"`)
	DeviceName    string                 `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName" binding:"required"`   //@go_tags(`json:"deviceName" binding:"required"`)
	Nonce         string                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce"`             //@go_tags(`json:"nonce"`) 可选，部分版本设备 SDK 不下发
	PayMode       string                 `protobuf:"bytes,4,opt,name=payMode,proto3" json:"payMode"`         //@go_tags(`json:"payMode"`) 固定 "LICENSE"
	RequestTime   string                 `protobuf:"bytes,5,opt,name=requestTime,proto3" json:"requestTime" binding:"required"` //@go_tags(`json:"requestTime" binding:"required"`)
	SdkVersion    string                 `protobuf:"bytes,6,opt,name=sdkVersion,proto3" json:"sdkVersion"`   //@go_tags(`json:"sdkVersion"`)
	TokenType     string                 `protobuf:"bytes,7,opt,name=tokenType,proto3" json:"tokenType" binding:"required"`     //@go_tags(`json:"tokenType" binding:"required"`) 固定 "MMI"
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature" binding:"required"`     //@go_tags(`json:"signature" binding:"required"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BailianGetTokenReq) Reset() {
	*x = BailianGetTokenReq{}
	mi := &file_bailian_bailian_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BailianGetTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BailianGetTokenReq) ProtoMessage() {}

func (x *BailianGetTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_bailian_bailian_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BailianGetTokenReq.ProtoReflect.Descriptor instead.
func (*BailianGetTokenReq) Descriptor() ([]byte, []int) {
	return file_bailian_bailian_msg_proto_rawDescGZIP(), []int{2}
}

func (x *BailianGetTokenReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BailianGetTokenReq) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *BailianGetTokenReq) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *BailianGetTokenReq) GetPayMode() string {
	if x != nil {
		return x.PayMode
	}
	return ""
}

func (x *BailianGetTokenReq) GetRequestTime() string {
	if x != nil {
		return x.RequestTime
	}
	return ""
}

func (x *BailianGetTokenReq) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *BailianGetTokenReq) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BailianGetTokenReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type BailianGetTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce"`               //@go_tags(`json:"nonce"`)
	ResponseTime  string                 `protobuf:"bytes,2,opt,name=responseTime,proto3" json:"responseTime"` //@go_tags(`json:"responseTime"`)
	AppId         string                 `protobuf:"bytes,3,opt,name=appId,proto3" json:"appId"`               //@go_tags(`json:"appId"`)
	DeviceName    string                 `protobuf:"bytes,4,opt,name=deviceName,proto3" json:"deviceName"`     //@go_tags(`json:"deviceName"`)
	RequestIp     string                 `protobuf:"bytes,5,opt,name=requestIp,proto3" json:"requestIp"`       //@go_tags(`json:"requestIp"`)
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature"`       //@go_tags(`json:"signature"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BailianGetTokenResp) Reset() {
	*x = BailianGetTokenResp{}
	mi := &file_bailian_bailian_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BailianGetTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BailianGetTokenResp) ProtoMessage() {}

func (x *BailianGetTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_bailian_bailian_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BailianGetTokenResp.ProtoReflect.Descriptor instead.
func (*BailianGetTokenResp) Descriptor() ([]byte, []int) {
	return file_bailian_bailian_msg_proto_rawDescGZIP(), []int{3}
}

func (x *BailianGetTokenResp) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *BailianGetTokenResp) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

func (x *BailianGetTokenResp) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BailianGetTokenResp) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *BailianGetTokenResp) GetRequestIp() string {
	if x != nil {
		return x.RequestIp
	}
	return ""
}

func (x *BailianGetTokenResp) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_bailian_bailian_msg_proto protoreflect.FileDescriptor

const file_bailian_bailian_msg_proto_rawDesc = "" +
	"\n" +
	"\x19bailian/bailian_msg.proto\"\xc6\x01\n" +
	"\x18BailianDeviceRegisterReq\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12 \n" +
	"\vrequestTime\x18\x04 \x01(\tR\vrequestTime\x12\x1e\n" +
	"\n" +
	"sdkVersion\x18\x05 \x01(\tR\n" +
	"sdkVersion\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\"\xa9\x01\n" +
	"\x19BailianDeviceRegisterResp\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\"\n" +
	"\fresponseTime\x18\x02 \x01(\tR\fresponseTime\x12\x14\n" +
	"\x05appId\x18\x03 \x01(\tR\x05appId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\"\xf8\x01\n" +
	"\x12BailianGetTokenReq\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x02 \x01(\tR\n" +
	"deviceName\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\tR\x05nonce\x12\x18\n" +
	"\apayMode\x18\x04 \x01(\tR\apayMode\x12 \n" +
	"\vrequestTime\x18\x05 \x01(\tR\vrequestTime\x12\x1e\n" +
	"\n" +
	"sdkVersion\x18\x06 \x01(\tR\n" +
	"sdkVersion\x12\x1c\n" +
	"\ttokenType\x18\a \x01(\tR\ttokenType\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\"\xc1\x01\n" +
	"\x13BailianGetTokenResp\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\x12\"\n" +
	"\fresponseTime\x18\x02 \x01(\tR\fresponseTime\x12\x14\n" +
	"\x05appId\x18\x03 \x01(\tR\x05appId\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\trequestIp\x18\x05 \x01(\tR\trequestIp\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignatureB\x06Z\x04.;pbb\x06proto3"

var (
	file_bailian_bailian_msg_proto_rawDescOnce sync.Once
	file_bailian_bailian_msg_proto_rawDescData []byte
)

func file_bailian_bailian_msg_proto_rawDescGZIP() []byte {
	file_bailian_bailian_msg_proto_rawDescOnce.Do(func() {
		file_bailian_bailian_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bailian_bailian_msg_proto_rawDesc), len(file_bailian_bailian_msg_proto_rawDesc)))
	})
	return file_bailian_bailian_msg_proto_rawDescData
}

var file_bailian_bailian_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bailian_bailian_msg_proto_goTypes = []any{
	(*BailianDeviceRegisterReq)(nil),  // 0: BailianDeviceRegisterReq
	(*BailianDeviceRegisterResp)(nil), // 1: BailianDeviceRegisterResp
	(*BailianGetTokenReq)(nil),        // 2: BailianGetTokenReq
	(*BailianGetTokenResp)(nil),       // 3: BailianGetTokenResp
}
var file_bailian_bailian_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bailian_bailian_msg_proto_init() }
func file_bailian_bailian_msg_proto_init() {
	if File_bailian_bailian_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bailian_bailian_msg_proto_rawDesc), len(file_bailian_bailian_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bailian_bailian_msg_proto_goTypes,
		DependencyIndexes: file_bailian_bailian_msg_proto_depIdxs,
		MessageInfos:      file_bailian_bailian_msg_proto_msgTypes,
	}.Build()
	File_bailian_bailian_msg_proto = out.File
	file_bailian_bailian_msg_proto_goTypes = nil
	file_bailian_bailian_msg_proto_depIdxs = nil
}
