// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: comm.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=Code,proto3,enum=ErrorCode" json:"Code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorData) Reset() {
	*x = ErrorData{}
	mi := &file_comm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorData) ProtoMessage() {}

func (x *ErrorData) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorData.ProtoReflect.Descriptor instead.
func (*ErrorData) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorData) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_Success
}

func (x *ErrorData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// RPC 默认请求和回应
type Rpc_EmptyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rpc_EmptyReq) Reset() {
	*x = Rpc_EmptyReq{}
	mi := &file_comm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rpc_EmptyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_EmptyReq) ProtoMessage() {}

func (x *Rpc_EmptyReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_EmptyReq.ProtoReflect.Descriptor instead.
func (*Rpc_EmptyReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{1}
}

type Rpc_EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rpc_EmptyResp) Reset() {
	*x = Rpc_EmptyResp{}
	mi := &file_comm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rpc_EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_EmptyResp) ProtoMessage() {}

func (x *Rpc_EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_EmptyResp.ProtoReflect.Descriptor instead.
func (*Rpc_EmptyResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{2}
}

// 网关Http 路由请求
type Rpc_GatewayHttpRouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgName       string                 `protobuf:"bytes,1,opt,name=MsgName,proto3" json:"MsgName,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,2,rep,name=Meta,proto3" json:"Meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Message       []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rpc_GatewayHttpRouteReq) Reset() {
	*x = Rpc_GatewayHttpRouteReq{}
	mi := &file_comm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rpc_GatewayHttpRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteReq) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteReq.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteReq) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{3}
}

func (x *Rpc_GatewayHttpRouteReq) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteReq) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Rpc_GatewayHttpRouteReq) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type Rpc_GatewayHttpRouteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   string                 `protobuf:"bytes,1,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
	Encrypted     bool                   `protobuf:"varint,3,opt,name=Encrypted,proto3" json:"Encrypted,omitempty"` //业务服务上报：该响应需要加密，实际加密动作由网关模块执行
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rpc_GatewayHttpRouteResp) Reset() {
	*x = Rpc_GatewayHttpRouteResp{}
	mi := &file_comm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rpc_GatewayHttpRouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rpc_GatewayHttpRouteResp) ProtoMessage() {}

func (x *Rpc_GatewayHttpRouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_comm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rpc_GatewayHttpRouteResp.ProtoReflect.Descriptor instead.
func (*Rpc_GatewayHttpRouteResp) Descriptor() ([]byte, []int) {
	return file_comm_proto_rawDescGZIP(), []int{4}
}

func (x *Rpc_GatewayHttpRouteResp) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Rpc_GatewayHttpRouteResp) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Rpc_GatewayHttpRouteResp) GetEncrypted() bool {
	if x != nil {
		return x.Encrypted
	}
	return false
}

var File_comm_proto protoreflect.FileDescriptor

const file_comm_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"comm.proto\x1a\x0ferrorcode.proto\"E\n" +
	"\tErrorData\x12\x1e\n" +
	"\x04Code\x18\x01 \x01(\x0e2\n" +
	".ErrorCodeR\x04Code\x12\x18\n" +
	"\aMessage\x18\x02 \x01(\tR\aMessage\"\x0e\n" +
	"\fRpc_EmptyReq\"\x0f\n" +
	"\rRpc_EmptyResp\"\xbe\x01\n" +
	"\x17Rpc_GatewayHttpRouteReq\x12\x18\n" +
	"\aMsgName\x18\x01 \x01(\tR\aMsgName\x126\n" +
	"\x04Meta\x18\x02 \x03(\v2\".Rpc_GatewayHttpRouteReq.MetaEntryR\x04Meta\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\x18Rpc_GatewayHttpRouteResp\x12 \n" +
	"\vContentType\x18\x01 \x01(\tR\vContentType\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\fR\x04Body\x12\x1c\n" +
	"\tEncrypted\x18\x03 \x01(\bR\tEncryptedB\x06Z\x04.;pbb\x06proto3"

var (
	file_comm_proto_rawDescOnce sync.Once
	file_comm_proto_rawDescData []byte
)

func file_comm_proto_rawDescGZIP() []byte {
	file_comm_proto_rawDescOnce.Do(func() {
		file_comm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)))
	})
	return file_comm_proto_rawDescData
}

var file_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_comm_proto_goTypes = []any{
	(*ErrorData)(nil),                // 0: ErrorData
	(*Rpc_EmptyReq)(nil),             // 1: Rpc_EmptyReq
	(*Rpc_EmptyResp)(nil),            // 2: Rpc_EmptyResp
	(*Rpc_GatewayHttpRouteReq)(nil),  // 3: Rpc_GatewayHttpRouteReq
	(*Rpc_GatewayHttpRouteResp)(nil), // 4: Rpc_GatewayHttpRouteResp
	nil,                              // 5: Rpc_GatewayHttpRouteReq.MetaEntry
	(ErrorCode)(0),                   // 6: ErrorCode
}
var file_comm_proto_depIdxs = []int32{
	6, // 0: ErrorData.Code:type_name -> ErrorCode
	5, // 1: Rpc_GatewayHttpRouteReq.Meta:type_name -> Rpc_GatewayHttpRouteReq.MetaEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_comm_proto_init() }
func file_comm_proto_init() {
	if File_comm_proto != nil {
		return
	}
	file_errorcode_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comm_proto_rawDesc), len(file_comm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comm_proto_goTypes,
		DependencyIndexes: file_comm_proto_depIdxs,
		MessageInfos:      file_comm_proto_msgTypes,
	}.Build()
	File_comm_proto = out.File
	file_comm_proto_goTypes = nil
	file_comm_proto_depIdxs = nil
}
