// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: echomeet/echomeet_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 转写服务类型
type TranscribeService int32

const (
	TranscribeService_TranscribeService_Unknown   TranscribeService = 0 // 未知（兼容旧数据）
	TranscribeService_TranscribeService_ByteDance TranscribeService = 1 // 字节跳动
	TranscribeService_TranscribeService_Ali       TranscribeService = 2 // 阿里云 DashScope
	TranscribeService_TranscribeService_Auto      TranscribeService = 3 // 自动按语言路由
	TranscribeService_TranscribeService_Google    TranscribeService = 4 // Google Cloud
	TranscribeService_TranscribeService_Microsoft TranscribeService = 5 // Azure
)

// Enum value maps for TranscribeService.
var (
	TranscribeService_name = map[int32]string{
		0: "TranscribeService_Unknown",
		1: "TranscribeService_ByteDance",
		2: "TranscribeService_Ali",
		3: "TranscribeService_Auto",
		4: "TranscribeService_Google",
		5: "TranscribeService_Microsoft",
	}
	TranscribeService_value = map[string]int32{
		"TranscribeService_Unknown":   0,
		"TranscribeService_ByteDance": 1,
		"TranscribeService_Ali":       2,
		"TranscribeService_Auto":      3,
		"TranscribeService_Google":    4,
		"TranscribeService_Microsoft": 5,
	}
)

func (x TranscribeService) Enum() *TranscribeService {
	p := new(TranscribeService)
	*p = x
	return p
}

func (x TranscribeService) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TranscribeService) Descriptor() protoreflect.EnumDescriptor {
	return file_echomeet_echomeet_db_proto_enumTypes[0].Descriptor()
}

func (TranscribeService) Type() protoreflect.EnumType {
	return &file_echomeet_echomeet_db_proto_enumTypes[0]
}

func (x TranscribeService) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TranscribeService.Descriptor instead.
func (TranscribeService) EnumDescriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{0}
}

type DBEchoMeetRecordState int32

const (
	DBEchoMeetRecordState_Unknow            DBEchoMeetRecordState = 0     //@go_tags(`gorm:"DBEchoMeetRecordState_Unknow"`) 未知状态
	DBEchoMeetRecordState_AwaitTranscribing DBEchoMeetRecordState = 1     //@go_tags(`gorm:"DBEchoMeetRecordState_AwaitingTranscribing"`) 等待转写中
	DBEchoMeetRecordState_Transcribing      DBEchoMeetRecordState = 2     //@go_tags(`gorm:"DBEchoMeetRecordState_Transcribing"`) 听写中
	DBEchoMeetRecordState_AwaitSummarizing  DBEchoMeetRecordState = 3     //@go_tags(`gorm:"DBEchoMeetRecordState_AwaitingSummarizing"`) 等待总结中
	DBEchoMeetRecordState_Summarizing       DBEchoMeetRecordState = 4     //@go_tags(`gorm:"DBEchoMeetRecordState_Summarizing"`) 总结中
	DBEchoMeetRecordState_Completed         DBEchoMeetRecordState = 5     //@go_tags(`gorm:"DBEchoMeetRecordState_Completed"`) 已完成
	DBEchoMeetRecordState_Readed            DBEchoMeetRecordState = 6     //@go_tags(`gorm:"DBEchoMeetRecordState_Readed"`) 已阅
	DBEchoMeetRecordState_TranscribeFail    DBEchoMeetRecordState = 10002 //@go_tags(`gorm:"DBEchoMeetRecordState_TranscribeFail"`) 转写失败
	DBEchoMeetRecordState_SummarizFail      DBEchoMeetRecordState = 10001 //@go_tags(`gorm:"DBEchoMeetRecordState_SummarizFail"`) 总结失败
)

// Enum value maps for DBEchoMeetRecordState.
var (
	DBEchoMeetRecordState_name = map[int32]string{
		0:     "Unknow",
		1:     "AwaitTranscribing",
		2:     "Transcribing",
		3:     "AwaitSummarizing",
		4:     "Summarizing",
		5:     "Completed",
		6:     "Readed",
		10002: "TranscribeFail",
		10001: "SummarizFail",
	}
	DBEchoMeetRecordState_value = map[string]int32{
		"Unknow":            0,
		"AwaitTranscribing": 1,
		"Transcribing":      2,
		"AwaitSummarizing":  3,
		"Summarizing":       4,
		"Completed":         5,
		"Readed":            6,
		"TranscribeFail":    10002,
		"SummarizFail":      10001,
	}
)

func (x DBEchoMeetRecordState) Enum() *DBEchoMeetRecordState {
	p := new(DBEchoMeetRecordState)
	*p = x
	return p
}

func (x DBEchoMeetRecordState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DBEchoMeetRecordState) Descriptor() protoreflect.EnumDescriptor {
	return file_echomeet_echomeet_db_proto_enumTypes[1].Descriptor()
}

func (DBEchoMeetRecordState) Type() protoreflect.EnumType {
	return &file_echomeet_echomeet_db_proto_enumTypes[1]
}

func (x DBEchoMeetRecordState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DBEchoMeetRecordState.Descriptor instead.
func (DBEchoMeetRecordState) EnumDescriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{1}
}

// 会议记录模板
type DBEchoMeetTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"id;primaryKey;autoIncrement json:"`                  //@go_tags(`gorm:"id;primaryKey;autoIncrement json:"id"`) id
	Tid           string                 `protobuf:"bytes,2,opt,name=tid,proto3" json:"tid,omitempty" gorm:"tid;index"`                 //@go_tags(`gorm:"tid;index"`) 模板id
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty" gorm:"source;index"`           //@go_tags(`gorm:"source;index"`) 来源
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty" gorm:"title"`             //@go_tags(`gorm:"title"`) 标题
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty" gorm:"description"` //@go_tags(`gorm:"description"`) 描述
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty" gorm:"language;index"`       //@go_tags(`gorm:"language;index"`) 语言
	Ttype         string                 `protobuf:"bytes,7,opt,name=ttype,proto3" json:"ttype,omitempty" gorm:"ttype;index"`             //@go_tags(`gorm:"ttype;index"`) 类型
	Tags          string                 `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty" gorm:"tags"`               //@go_tags(`gorm:"tags"`) 标签
	Icon          string                 `protobuf:"bytes,9,opt,name=icon,proto3" json:"icon,omitempty" gorm:"icon"`               //@go_tags(`gorm:"icon"`) 图标
	Outline       string                 `protobuf:"bytes,10,opt,name=outline,proto3" json:"outline,omitempty" gorm:"outline"`        //@go_tags(`gorm:"outline"`) 大纲
	Template      string                 `protobuf:"bytes,11,opt,name=template,proto3" json:"template,omitempty" gorm:"template"`      //@go_tags(`gorm:"template"`) 模板
	Sort          int32                  `protobuf:"varint,12,opt,name=sort,proto3" json:"sort,omitempty" gorm:"sort;index"`             //@go_tags(`gorm:"sort;index"`) 显示优先级，数值越大越靠前
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBEchoMeetTemplate) Reset() {
	*x = DBEchoMeetTemplate{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBEchoMeetTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEchoMeetTemplate) ProtoMessage() {}

func (x *DBEchoMeetTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEchoMeetTemplate.ProtoReflect.Descriptor instead.
func (*DBEchoMeetTemplate) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBEchoMeetTemplate) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBEchoMeetTemplate) GetTid() string {
	if x != nil {
		return x.Tid
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetTtype() string {
	if x != nil {
		return x.Ttype
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetOutline() string {
	if x != nil {
		return x.Outline
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *DBEchoMeetTemplate) GetSort() int32 {
	if x != nil {
		return x.Sort
	}
	return 0
}

// 会议记录数据结构
type DBEchoMeetRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"id:50;primaryKey;autoIncrement json:"`                                                              //@go_tags(`gorm:"id:50;primaryKey;autoIncrement json:"id"`) 索引id
	Uid                  string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" gorm:"uid;index"`                                                             //@go_tags(`gorm:"uid;index" json:"uid"`) 用户ID
	State                DBEchoMeetRecordState  `protobuf:"varint,3,opt,name=state,proto3,enum=DBEchoMeetRecordState" json:"state" gorm:"state;index"`                             //@go_tags(`gorm:"state;index" json:"state"`) 状态
	Creationtime         int64                  `protobuf:"varint,4,opt,name=creationtime,proto3" json:"creationtime" gorm:"creationtime;index"`                                          //@go_tags(`gorm:"creationtime;index" json:"creationtime"`) 時間
	Rtype                string                 `protobuf:"bytes,5,opt,name=rtype,proto3" json:"rtype" gorm:"rtype;index"`                                                         //@go_tags(`gorm:"rtype;index" json:"rtype"`) 类型
	Filepath             string                 `protobuf:"bytes,6,opt,name=filepath,proto3" json:"filepath" gorm:"filepath"`                                                   //@go_tags(`gorm:"filepath" json:"filepath"`) 本地音频文件路径
	Audiourl             string                 `protobuf:"bytes,7,opt,name=audiourl,proto3" json:"audiourl" gorm:"audiourl"`                                                   //@go_tags(`gorm:"audiourl" json:"audiourl"`) 音频url
	Title                string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title" gorm:"title"`                                                         //@go_tags(`gorm:"title" json:"title"`) 标题
	Address              string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address" gorm:"address"`                                                     //@go_tags(`gorm:"address" json:"address"`) 地址
	Personnel            string                 `protobuf:"bytes,10,opt,name=personnel,proto3" json:"personnel" gorm:"personnel"`                                                //@go_tags(`gorm:"personnel" json:"personnel"`) 成员
	Tasktype             int32                  `protobuf:"varint,11,opt,name=tasktype,proto3" json:"tasktype" gorm:"tasktype"`                                                 //@go_tags(`gorm:"tasktype" json:"tasktype"`) 任务类型
	Taskid               string                 `protobuf:"bytes,12,opt,name=taskid,proto3" json:"taskid" gorm:"taskid"`                                                      //@go_tags(`gorm:"taskid" json:"taskid"`) 任务id
	Logid                string                 `protobuf:"bytes,13,opt,name=logid,proto3" json:"logid" gorm:"logid"`                                                        //@go_tags(`gorm:"logid" json:"logid"`) 日志id
	Isdistinguishspeaker bool                   `protobuf:"varint,14,opt,name=isdistinguishspeaker,proto3" json:"isdistinguishspeaker" gorm:"isdistinguishspeaker"`                         //@go_tags(`gorm:"isdistinguishspeaker" json:"isdistinguishspeaker"`) 是否区分说话人
	Templateid           uint64                 `protobuf:"varint,15,opt,name=templateid,proto3" json:"templateid" gorm:"templateid"`                                             //@go_tags(`gorm:"templateid" json:"templateid"`) 模板id
	Formlanguage         string                 `protobuf:"bytes,16,opt,name=formlanguage,proto3" json:"formlanguage" gorm:"formlanguage"`                                          //@go_tags(`gorm:"formlanguage" json:"formlanguage"`) 语言
	Tolanguage           string                 `protobuf:"bytes,17,opt,name=tolanguage,proto3" json:"tolanguage" gorm:"tolanguage"`                                              //@go_tags(`gorm:"tolanguage" json:"tolanguage"`) 目标语言
	Seconds              int32                  `protobuf:"varint,18,opt,name=seconds,proto3" json:"seconds" gorm:"seconds"`                                                   //@go_tags(`gorm:"seconds" json:"seconds"`) 时长
	Size                 int64                  `protobuf:"varint,19,opt,name=size,proto3" json:"size" gorm:"column:size;type:bigint"`                                                         //@go_tags(`gorm:"column:size;type:bigint" json:"size"`) 文件大小
	Original             string                 `protobuf:"bytes,20,opt,name=original,proto3" json:"original" gorm:"original"`                                                  //@go_tags(`gorm:"original" json:"original"`) 听写内容
	Translate            string                 `protobuf:"bytes,21,opt,name=translate,proto3" json:"translate" gorm:"translate"`                                                //@go_tags(`gorm:"translate" json:"translate"`) 翻译
	Overview             string                 `protobuf:"bytes,22,opt,name=overview,proto3" json:"overview" gorm:"overview"`                                                  //@go_tags(`gorm:"overview" json:"overview"`) 短总结
	Summary              string                 `protobuf:"bytes,23,opt,name=summary,proto3" json:"summary" gorm:"summary"`                                                    //@go_tags(`gorm:"summary" json:"summary"`) 总结
	ServiceType          TranscribeService      `protobuf:"varint,24,opt,name=service_type,json=serviceType,proto3,enum=TranscribeService" json:"service_type" gorm:"service_type"` //@go_tags(`gorm:"service_type" json:"service_type"`) 转写服务类型
	Starttime            int64                  `protobuf:"varint,25,opt,name=starttime,proto3" json:"starttime" gorm:"starttime"`                                               //@go_tags(`gorm:"starttime" json:"starttime"`) 处理开始时间 unix 秒
	Processduration      int64                  `protobuf:"varint,26,opt,name=processduration,proto3" json:"processduration" gorm:"processduration"`                                   //@go_tags(`gorm:"processduration" json:"processduration"`) 处理耗时 秒
	Lastquerytime        int64                  `protobuf:"varint,27,opt,name=lastquerytime,proto3" json:"lastquerytime" gorm:"lastquerytime"`                                       //@go_tags(`gorm:"lastquerytime" json:"lastquerytime"`) 上一次主动查询第三方服务的 unix 秒，用于限制查询频率
	Remark               string                 `protobuf:"bytes,28,opt,name=remark,proto3" json:"remark" gorm:"remark"`                                                      //@go_tags(`gorm:"remark" json:"remark"`) 用户备注（创建记录时填写，参与AI总结）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DBEchoMeetRecord) Reset() {
	*x = DBEchoMeetRecord{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBEchoMeetRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBEchoMeetRecord) ProtoMessage() {}

func (x *DBEchoMeetRecord) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBEchoMeetRecord.ProtoReflect.Descriptor instead.
func (*DBEchoMeetRecord) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBEchoMeetRecord) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBEchoMeetRecord) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBEchoMeetRecord) GetState() DBEchoMeetRecordState {
	if x != nil {
		return x.State
	}
	return DBEchoMeetRecordState_Unknow
}

func (x *DBEchoMeetRecord) GetCreationtime() int64 {
	if x != nil {
		return x.Creationtime
	}
	return 0
}

func (x *DBEchoMeetRecord) GetRtype() string {
	if x != nil {
		return x.Rtype
	}
	return ""
}

func (x *DBEchoMeetRecord) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *DBEchoMeetRecord) GetAudiourl() string {
	if x != nil {
		return x.Audiourl
	}
	return ""
}

func (x *DBEchoMeetRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DBEchoMeetRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DBEchoMeetRecord) GetPersonnel() string {
	if x != nil {
		return x.Personnel
	}
	return ""
}

func (x *DBEchoMeetRecord) GetTasktype() int32 {
	if x != nil {
		return x.Tasktype
	}
	return 0
}

func (x *DBEchoMeetRecord) GetTaskid() string {
	if x != nil {
		return x.Taskid
	}
	return ""
}

func (x *DBEchoMeetRecord) GetLogid() string {
	if x != nil {
		return x.Logid
	}
	return ""
}

func (x *DBEchoMeetRecord) GetIsdistinguishspeaker() bool {
	if x != nil {
		return x.Isdistinguishspeaker
	}
	return false
}

func (x *DBEchoMeetRecord) GetTemplateid() uint64 {
	if x != nil {
		return x.Templateid
	}
	return 0
}

func (x *DBEchoMeetRecord) GetFormlanguage() string {
	if x != nil {
		return x.Formlanguage
	}
	return ""
}

func (x *DBEchoMeetRecord) GetTolanguage() string {
	if x != nil {
		return x.Tolanguage
	}
	return ""
}

func (x *DBEchoMeetRecord) GetSeconds() int32 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *DBEchoMeetRecord) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DBEchoMeetRecord) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *DBEchoMeetRecord) GetTranslate() string {
	if x != nil {
		return x.Translate
	}
	return ""
}

func (x *DBEchoMeetRecord) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *DBEchoMeetRecord) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *DBEchoMeetRecord) GetServiceType() TranscribeService {
	if x != nil {
		return x.ServiceType
	}
	return TranscribeService_TranscribeService_Unknown
}

func (x *DBEchoMeetRecord) GetStarttime() int64 {
	if x != nil {
		return x.Starttime
	}
	return 0
}

func (x *DBEchoMeetRecord) GetProcessduration() int64 {
	if x != nil {
		return x.Processduration
	}
	return 0
}

func (x *DBEchoMeetRecord) GetLastquerytime() int64 {
	if x != nil {
		return x.Lastquerytime
	}
	return 0
}

func (x *DBEchoMeetRecord) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ContextStruct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetingid     uint64                 `protobuf:"varint,1,opt,name=Meetingid,proto3" json:"meetingid"` //@go_tags(`json:"meetingid"`) 会议id
	Content       string                 `protobuf:"bytes,2,opt,name=Content,proto3" json:"content"`      //@go_tags(`json:"content"`) 内容
	Starttime     int64                  `protobuf:"varint,3,opt,name=Starttime,proto3" json:"starttime"` //@go_tags(`json:"starttime"`) 开始时间
	Endtime       int64                  `protobuf:"varint,4,opt,name=Endtime,proto3" json:"endtime"`     //@go_tags(`json:"endtime"`) 结束时间
	Speaker       string                 `protobuf:"bytes,5,opt,name=Speaker,proto3" json:"speaker"`      //@go_tags(`json:"speaker"`) 说话人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextStruct) Reset() {
	*x = ContextStruct{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextStruct) ProtoMessage() {}

func (x *ContextStruct) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextStruct.ProtoReflect.Descriptor instead.
func (*ContextStruct) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{2}
}

func (x *ContextStruct) GetMeetingid() uint64 {
	if x != nil {
		return x.Meetingid
	}
	return 0
}

func (x *ContextStruct) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ContextStruct) GetStarttime() int64 {
	if x != nil {
		return x.Starttime
	}
	return 0
}

func (x *ContextStruct) GetEndtime() int64 {
	if x != nil {
		return x.Endtime
	}
	return 0
}

func (x *ContextStruct) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

// 单个字词的识别结果
type Word struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confidence    float32                `protobuf:"fixed32,1,opt,name=confidence,proto3" json:"confidence,omitempty"`               // 置信度
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                             // 字词文本
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 开始时间（ms）
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间（ms）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Word) Reset() {
	*x = Word{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{3}
}

func (x *Word) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Word) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Word) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Word) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 分句的附加信息（声道、说话人）
type UtteranceAdditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"` // 声道ID
	Speaker       string                 `protobuf:"bytes,2,opt,name=speaker,proto3" json:"speaker,omitempty"`                      // 说话人ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtteranceAdditions) Reset() {
	*x = UtteranceAdditions{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtteranceAdditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtteranceAdditions) ProtoMessage() {}

func (x *UtteranceAdditions) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtteranceAdditions.ProtoReflect.Descriptor instead.
func (*UtteranceAdditions) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{4}
}

func (x *UtteranceAdditions) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *UtteranceAdditions) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

// 分句识别结果
type Utterance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []*Word                `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`                           // 分句下的字词列表
	Additions     *UtteranceAdditions    `protobuf:"bytes,2,opt,name=additions,proto3" json:"additions,omitempty"`                   // 附加信息
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`                             // 分句文本
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // 分句开始时间（ms）
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 分句结束时间（ms）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Utterance) Reset() {
	*x = Utterance{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Utterance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Utterance) ProtoMessage() {}

func (x *Utterance) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Utterance.ProtoReflect.Descriptor instead.
func (*Utterance) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{5}
}

func (x *Utterance) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

func (x *Utterance) GetAdditions() *UtteranceAdditions {
	if x != nil {
		return x.Additions
	}
	return nil
}

func (x *Utterance) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Utterance) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Utterance) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

// 识别结果的附加信息（总时长）
type ResultAdditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      string                 `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"` // 音频总时长（ms）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultAdditions) Reset() {
	*x = ResultAdditions{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultAdditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultAdditions) ProtoMessage() {}

func (x *ResultAdditions) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultAdditions.ProtoReflect.Descriptor instead.
func (*ResultAdditions) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{6}
}

func (x *ResultAdditions) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

// 核心识别结果
type RecognitionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`             // 完整识别文本
	Utterances    []*Utterance           `protobuf:"bytes,2,rep,name=utterances,proto3" json:"utterances,omitempty"` // 分句列表
	Additions     *ResultAdditions       `protobuf:"bytes,3,opt,name=additions,proto3" json:"additions,omitempty"`   // 结果附加信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognitionResult) Reset() {
	*x = RecognitionResult{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionResult) ProtoMessage() {}

func (x *RecognitionResult) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionResult.ProtoReflect.Descriptor instead.
func (*RecognitionResult) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{7}
}

func (x *RecognitionResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RecognitionResult) GetUtterances() []*Utterance {
	if x != nil {
		return x.Utterances
	}
	return nil
}

func (x *RecognitionResult) GetAdditions() *ResultAdditions {
	if x != nil {
		return x.Additions
	}
	return nil
}

// 音频基础信息
type AudioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      int64                  `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"` // 音频时长（ms）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioInfo) Reset() {
	*x = AudioInfo{}
	mi := &file_echomeet_echomeet_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioInfo) ProtoMessage() {}

func (x *AudioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_echomeet_echomeet_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioInfo.ProtoReflect.Descriptor instead.
func (*AudioInfo) Descriptor() ([]byte, []int) {
	return file_echomeet_echomeet_db_proto_rawDescGZIP(), []int{8}
}

func (x *AudioInfo) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_echomeet_echomeet_db_proto protoreflect.FileDescriptor

const file_echomeet_echomeet_db_proto_rawDesc = "" +
	"\n" +
	"\x1aechomeet/echomeet_db.proto\"\xaa\x02\n" +
	"\x12DBEchoMeetTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03tid\x18\x02 \x01(\tR\x03tid\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12\x14\n" +
	"\x05ttype\x18\a \x01(\tR\x05ttype\x12\x12\n" +
	"\x04tags\x18\b \x01(\tR\x04tags\x12\x12\n" +
	"\x04icon\x18\t \x01(\tR\x04icon\x12\x18\n" +
	"\aoutline\x18\n" +
	" \x01(\tR\aoutline\x12\x1a\n" +
	"\btemplate\x18\v \x01(\tR\btemplate\x12\x12\n" +
	"\x04sort\x18\f \x01(\x05R\x04sort\"\xdf\x06\n" +
	"\x10DBEchoMeetRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.DBEchoMeetRecordStateR\x05state\x12\"\n" +
	"\fcreationtime\x18\x04 \x01(\x03R\fcreationtime\x12\x14\n" +
	"\x05rtype\x18\x05 \x01(\tR\x05rtype\x12\x1a\n" +
	"\bfilepath\x18\x06 \x01(\tR\bfilepath\x12\x1a\n" +
	"\baudiourl\x18\a \x01(\tR\baudiourl\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x1c\n" +
	"\tpersonnel\x18\n" +
	" \x01(\tR\tpersonnel\x12\x1a\n" +
	"\btasktype\x18\v \x01(\x05R\btasktype\x12\x16\n" +
	"\x06taskid\x18\f \x01(\tR\x06taskid\x12\x14\n" +
	"\x05logid\x18\r \x01(\tR\x05logid\x122\n" +
	"\x14isdistinguishspeaker\x18\x0e \x01(\bR\x14isdistinguishspeaker\x12\x1e\n" +
	"\n" +
	"templateid\x18\x0f \x01(\x04R\n" +
	"templateid\x12\"\n" +
	"\fformlanguage\x18\x10 \x01(\tR\fformlanguage\x12\x1e\n" +
	"\n" +
	"tolanguage\x18\x11 \x01(\tR\n" +
	"tolanguage\x12\x18\n" +
	"\aseconds\x18\x12 \x01(\x05R\aseconds\x12\x12\n" +
	"\x04size\x18\x13 \x01(\x03R\x04size\x12\x1a\n" +
	"\boriginal\x18\x14 \x01(\tR\boriginal\x12\x1c\n" +
	"\ttranslate\x18\x15 \x01(\tR\ttranslate\x12\x1a\n" +
	"\boverview\x18\x16 \x01(\tR\boverview\x12\x18\n" +
	"\asummary\x18\x17 \x01(\tR\asummary\x125\n" +
	"\fservice_type\x18\x18 \x01(\x0e2\x12.TranscribeServiceR\vserviceType\x12\x1c\n" +
	"\tstarttime\x18\x19 \x01(\x03R\tstarttime\x12(\n" +
	"\x0fprocessduration\x18\x1a \x01(\x03R\x0fprocessduration\x12$\n" +
	"\rlastquerytime\x18\x1b \x01(\x03R\rlastquerytime\x12\x16\n" +
	"\x06remark\x18\x1c \x01(\tR\x06remark\"\x99\x01\n" +
	"\rContextStruct\x12\x1c\n" +
	"\tMeetingid\x18\x01 \x01(\x04R\tMeetingid\x12\x18\n" +
	"\aContent\x18\x02 \x01(\tR\aContent\x12\x1c\n" +
	"\tStarttime\x18\x03 \x01(\x03R\tStarttime\x12\x18\n" +
	"\aEndtime\x18\x04 \x01(\x03R\aEndtime\x12\x18\n" +
	"\aSpeaker\x18\x05 \x01(\tR\aSpeaker\"t\n" +
	"\x04Word\x12\x1e\n" +
	"\n" +
	"confidence\x18\x01 \x01(\x02R\n" +
	"confidence\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\"M\n" +
	"\x12UtteranceAdditions\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x18\n" +
	"\aspeaker\x18\x02 \x01(\tR\aspeaker\"\xa9\x01\n" +
	"\tUtterance\x12\x1b\n" +
	"\x05words\x18\x01 \x03(\v2\x05.WordR\x05words\x121\n" +
	"\tadditions\x18\x02 \x01(\v2\x13.UtteranceAdditionsR\tadditions\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\"-\n" +
	"\x0fResultAdditions\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\tR\bduration\"\x83\x01\n" +
	"\x11RecognitionResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12*\n" +
	"\n" +
	"utterances\x18\x02 \x03(\v2\n" +
	".UtteranceR\n" +
	"utterances\x12.\n" +
	"\tadditions\x18\x03 \x01(\v2\x10.ResultAdditionsR\tadditions\"'\n" +
	"\tAudioInfo\x12\x1a\n" +
	"\bduration\x18\x01 \x01(\x03R\bduration*\xc9\x01\n" +
	"\x11TranscribeService\x12\x1d\n" +
	"\x19TranscribeService_Unknown\x10\x00\x12\x1f\n" +
	"\x1bTranscribeService_ByteDance\x10\x01\x12\x19\n" +
	"\x15TranscribeService_Ali\x10\x02\x12\x1a\n" +
	"\x16TranscribeService_Auto\x10\x03\x12\x1c\n" +
	"\x18TranscribeService_Google\x10\x04\x12\x1f\n" +
	"\x1bTranscribeService_Microsoft\x10\x05*\xb6\x01\n" +
	"\x15DBEchoMeetRecordState\x12\n" +
	"\n" +
	"\x06Unknow\x10\x00\x12\x15\n" +
	"\x11AwaitTranscribing\x10\x01\x12\x10\n" +
	"\fTranscribing\x10\x02\x12\x14\n" +
	"\x10AwaitSummarizing\x10\x03\x12\x0f\n" +
	"\vSummarizing\x10\x04\x12\r\n" +
	"\tCompleted\x10\x05\x12\n" +
	"\n" +
	"\x06Readed\x10\x06\x12\x13\n" +
	"\x0eTranscribeFail\x10\x92N\x12\x11\n" +
	"\fSummarizFail\x10\x91NB\x06Z\x04.;pbb\x06proto3"

var (
	file_echomeet_echomeet_db_proto_rawDescOnce sync.Once
	file_echomeet_echomeet_db_proto_rawDescData []byte
)

func file_echomeet_echomeet_db_proto_rawDescGZIP() []byte {
	file_echomeet_echomeet_db_proto_rawDescOnce.Do(func() {
		file_echomeet_echomeet_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echomeet_echomeet_db_proto_rawDesc), len(file_echomeet_echomeet_db_proto_rawDesc)))
	})
	return file_echomeet_echomeet_db_proto_rawDescData
}

var file_echomeet_echomeet_db_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_echomeet_echomeet_db_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_echomeet_echomeet_db_proto_goTypes = []any{
	(TranscribeService)(0),     // 0: TranscribeService
	(DBEchoMeetRecordState)(0), // 1: DBEchoMeetRecordState
	(*DBEchoMeetTemplate)(nil), // 2: DBEchoMeetTemplate
	(*DBEchoMeetRecord)(nil),   // 3: DBEchoMeetRecord
	(*ContextStruct)(nil),      // 4: ContextStruct
	(*Word)(nil),               // 5: Word
	(*UtteranceAdditions)(nil), // 6: UtteranceAdditions
	(*Utterance)(nil),          // 7: Utterance
	(*ResultAdditions)(nil),    // 8: ResultAdditions
	(*RecognitionResult)(nil),  // 9: RecognitionResult
	(*AudioInfo)(nil),          // 10: AudioInfo
}
var file_echomeet_echomeet_db_proto_depIdxs = []int32{
	1, // 0: DBEchoMeetRecord.state:type_name -> DBEchoMeetRecordState
	0, // 1: DBEchoMeetRecord.service_type:type_name -> TranscribeService
	5, // 2: Utterance.words:type_name -> Word
	6, // 3: Utterance.additions:type_name -> UtteranceAdditions
	7, // 4: RecognitionResult.utterances:type_name -> Utterance
	8, // 5: RecognitionResult.additions:type_name -> ResultAdditions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_echomeet_echomeet_db_proto_init() }
func file_echomeet_echomeet_db_proto_init() {
	if File_echomeet_echomeet_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echomeet_echomeet_db_proto_rawDesc), len(file_echomeet_echomeet_db_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echomeet_echomeet_db_proto_goTypes,
		DependencyIndexes: file_echomeet_echomeet_db_proto_depIdxs,
		EnumInfos:         file_echomeet_echomeet_db_proto_enumTypes,
		MessageInfos:      file_echomeet_echomeet_db_proto_msgTypes,
	}.Build()
	File_echomeet_echomeet_db_proto = out.File
	file_echomeet_echomeet_db_proto_goTypes = nil
	file_echomeet_echomeet_db_proto_depIdxs = nil
}
