// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: enum.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SginTyoe int32

const (
	// 邮箱登录
	// @Description 邮箱登录
	// @example
	SginTyoe_Mail SginTyoe = 0 //手机登录
	// 手机登录
	// @Description 手机登录
	// @example
	SginTyoe_Phone SginTyoe = 1 //手机登录
	// 微信登录
	// @Description 微信登录
	// @example
	SginTyoe_WXChat SginTyoe = 2 //微信登录
	// google登录
	// @Description google登录
	// @example
	SginTyoe_Google SginTyoe = 3 //google登录
	// facebook登录
	// @Description facebook登录
	// @example
	SginTyoe_FaceBook SginTyoe = 4 //facebook登录
	// firebase 登录
	// @Description
	// @example
	SginTyoe_Apple SginTyoe = 5 //Apple 登陆
	// 游客登录
	// @Description
	// @example
	SginTyoe_Tourists SginTyoe = 6 //游客登录
)

// Enum value maps for SginTyoe.
var (
	SginTyoe_name = map[int32]string{
		0: "Mail",
		1: "Phone",
		2: "WXChat",
		3: "Google",
		4: "FaceBook",
		5: "Apple",
		6: "Tourists",
	}
	SginTyoe_value = map[string]int32{
		"Mail":     0,
		"Phone":    1,
		"WXChat":   2,
		"Google":   3,
		"FaceBook": 4,
		"Apple":    5,
		"Tourists": 6,
	}
)

func (x SginTyoe) Enum() *SginTyoe {
	p := new(SginTyoe)
	*p = x
	return p
}

func (x SginTyoe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SginTyoe) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (SginTyoe) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x SginTyoe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SginTyoe.Descriptor instead.
func (SginTyoe) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type UserState int32

const (
	// 未知状态
	// @Description 未知状态
	// @example
	UserState_Normal UserState = 0 //正常状态
	// 禁用状态
	// @Description 禁用状态
	// @example
	UserState_Disabled UserState = 1 //禁用状态
	// 已注销状态（自助注销，可重新登录复活）
	// @Description 已注销状态
	// @example
	UserState_Cancelled UserState = 2 //已注销状态
)

// Enum value maps for UserState.
var (
	UserState_name = map[int32]string{
		0: "Normal",
		1: "Disabled",
		2: "Cancelled",
	}
	UserState_value = map[string]int32{
		"Normal":    0,
		"Disabled":  1,
		"Cancelled": 2,
	}
)

func (x UserState) Enum() *UserState {
	p := new(UserState)
	*p = x
	return p
}

func (x UserState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserState) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (UserState) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x UserState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserState.Descriptor instead.
func (UserState) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

// 设备类型
type DeviceType int32

const (
	// 未知设备
	// @Description 未知设备
	// @example
	DeviceType_DeviceTypeUnknown DeviceType = 0 //未知设备
	// 经典蓝牙耳机
	// @Description 经典蓝牙耳机
	// @example
	DeviceType_Classic_bluetooth_Headset DeviceType = 1 //经典蓝牙耳机
	// Ble蓝牙耳机
	// @Description Ble蓝牙耳机
	// @example
	DeviceType_BLE_Bluetooth_Double_Headset DeviceType = 2 //Ble蓝牙耳机 双端
	// Ble蓝牙耳机
	// @Description Ble蓝牙耳机
	// @example
	DeviceType_BLE_Bluetooth_Single_Headset DeviceType = 3 //Ble蓝牙耳机 单端
	// 智能录音笔
	// @Description 智能录音笔
	// @example
	DeviceType_Smart_Voice_Recorder DeviceType = 4 //智能录音笔
	// 智能眼镜
	// @Description 智能眼镜
	// @example
	DeviceType_SmartEye DeviceType = 5
	// 激活码卡片
	// @Description 激活码卡片
	// @example
	DeviceType_ActivationCard DeviceType = 6 //激活码卡片
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DeviceTypeUnknown",
		1: "Classic_bluetooth_Headset",
		2: "BLE_Bluetooth_Double_Headset",
		3: "BLE_Bluetooth_Single_Headset",
		4: "Smart_Voice_Recorder",
		5: "SmartEye",
		6: "ActivationCard",
	}
	DeviceType_value = map[string]int32{
		"DeviceTypeUnknown":            0,
		"Classic_bluetooth_Headset":    1,
		"BLE_Bluetooth_Double_Headset": 2,
		"BLE_Bluetooth_Single_Headset": 3,
		"Smart_Voice_Recorder":         4,
		"SmartEye":                     5,
		"ActivationCard":               6,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[2].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[2]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{2}
}

// 使用量类型
type UsageType int32

const (
	// / 未知使用量类型
	UsageType_UsageNull UsageType = 0
	// 翻译
	// @Description 翻译
	// @example
	UsageType_Trade UsageType = 1 //翻译
	// 会议
	// @Description 会议
	// @example
	UsageType_Meet UsageType = 2 //会议
	// 智能体
	// @Description 智能体
	// @example
	UsageType_AI UsageType = 3 //智能体
	// 购买VIP时长
	// @Description 购买VIP时长
	// @example
	UsageType_VIP UsageType = 4 //购买VIP时长
)

// Enum value maps for UsageType.
var (
	UsageType_name = map[int32]string{
		0: "UsageNull",
		1: "Trade",
		2: "Meet",
		3: "AI",
		4: "VIP",
	}
	UsageType_value = map[string]int32{
		"UsageNull": 0,
		"Trade":     1,
		"Meet":      2,
		"AI":        3,
		"VIP":       4,
	}
)

func (x UsageType) Enum() *UsageType {
	p := new(UsageType)
	*p = x
	return p
}

func (x UsageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsageType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[3].Descriptor()
}

func (UsageType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[3]
}

func (x UsageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsageType.Descriptor instead.
func (UsageType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{3}
}

type UserLogType int32

const (
	// 未知日志类型
	// @Description 未知日志类型
	// @example
	UserLogType_UserLogTypeUnknown UserLogType = 0 //未知日志类型
	// 重置购买日志类型
	// @Description 重置购买日志类型
	// @example
	UserLogType_Pay UserLogType = 1 //重置购买日志类型
	// 活动奖励日志类型
	// @Description 活动奖励日志类型
	// @example
	UserLogType_ActivityReward UserLogType = 2 //活动奖励日志类型
	// 管理员赠送日志类型
	// @Description 管理员赠送日志类型
	// @example
	UserLogType_AdminGive UserLogType = 3 //管理员赠送日志类型
	// / 用户消耗
	// @Description 用户消耗
	// @example
	UserLogType_UserConsume UserLogType = 4 //用户消耗
)

// Enum value maps for UserLogType.
var (
	UserLogType_name = map[int32]string{
		0: "UserLogTypeUnknown",
		1: "Pay",
		2: "ActivityReward",
		3: "AdminGive",
		4: "UserConsume",
	}
	UserLogType_value = map[string]int32{
		"UserLogTypeUnknown": 0,
		"Pay":                1,
		"ActivityReward":     2,
		"AdminGive":          3,
		"UserConsume":        4,
	}
)

func (x UserLogType) Enum() *UserLogType {
	p := new(UserLogType)
	*p = x
	return p
}

func (x UserLogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserLogType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[4].Descriptor()
}

func (UserLogType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[4]
}

func (x UserLogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserLogType.Descriptor instead.
func (UserLogType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{4}
}

// MCP服务类型
// @Description MCP服务类型
// @example
type MCPServerType int32

const (
	MCPServerType_Http MCPServerType = 0
	MCPServerType_SEE  MCPServerType = 1
)

// Enum value maps for MCPServerType.
var (
	MCPServerType_name = map[int32]string{
		0: "Http",
		1: "SEE",
	}
	MCPServerType_value = map[string]int32{
		"Http": 0,
		"SEE":  1,
	}
)

func (x MCPServerType) Enum() *MCPServerType {
	p := new(MCPServerType)
	*p = x
	return p
}

func (x MCPServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MCPServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[5].Descriptor()
}

func (MCPServerType) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[5]
}

func (x MCPServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MCPServerType.Descriptor instead.
func (MCPServerType) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{5}
}

// 智能体来源
// @Description 智能体来源
// @example
type AgentSource int32

const (
	// 内置智能体
	// @Description 内置智能体
	// @example
	AgentSource_AgentSourceBuiltin AgentSource = 0 //内置智能体
	// PolyChat 平台智能体
	// @Description PolyChat 平台智能体
	// @example
	AgentSource_AgentSourcePolyChat AgentSource = 1 //PolyChat 平台
	// 阿里云平台智能体
	// @Description 阿里云平台智能体
	// @example
	AgentSource_AgentSourceAliyun AgentSource = 2 //阿里云平台
	// 火山平台智能体
	// @Description 火山平台智能体
	// @example
	AgentSource_AgentSourceVolcano AgentSource = 3 //火山平台
)

// Enum value maps for AgentSource.
var (
	AgentSource_name = map[int32]string{
		0: "AgentSourceBuiltin",
		1: "AgentSourcePolyChat",
		2: "AgentSourceAliyun",
		3: "AgentSourceVolcano",
	}
	AgentSource_value = map[string]int32{
		"AgentSourceBuiltin":  0,
		"AgentSourcePolyChat": 1,
		"AgentSourceAliyun":   2,
		"AgentSourceVolcano":  3,
	}
)

func (x AgentSource) Enum() *AgentSource {
	p := new(AgentSource)
	*p = x
	return p
}

func (x AgentSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentSource) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[6].Descriptor()
}

func (AgentSource) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[6]
}

func (x AgentSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentSource.Descriptor instead.
func (AgentSource) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{6}
}

// 区域枚举，用于根据区域适配服务配置
type Region int32

const (
	// 未知区域
	// @Description 未知区域
	// @example
	Region_RegionUnknown Region = 0 //未知区域
	// 中国（独立处理）
	// @Description 中国
	// @example
	Region_RegionChina Region = 1 //中国
	// 美国（独立处理）
	// @Description 美国
	// @example
	Region_RegionUSA Region = 2 //美国
	// 东亚（日韩蒙等，不含中国）
	// @Description 东亚
	// @example
	Region_RegionEastAsia Region = 3 //东亚
	// 东南亚
	// @Description 东南亚
	// @example
	Region_RegionSoutheastAsia Region = 4 //东南亚
	// 南亚
	// @Description 南亚
	// @example
	Region_RegionSouthAsia Region = 5 //南亚
	// 西亚/中东
	// @Description 西亚/中东
	// @example
	Region_RegionMiddleEast Region = 6 //西亚/中东
	// 欧洲
	// @Description 欧洲
	// @example
	Region_RegionEurope Region = 7 //欧洲
	// 俄罗斯（独立处理）
	// @Description 俄罗斯
	// @example
	Region_RegionRussia Region = 8 //俄罗斯
	// 非洲
	// @Description 非洲
	// @example
	Region_RegionAfrica Region = 9 //非洲
	// 南美洲
	// @Description 南美洲
	// @example
	Region_RegionSouthAmerica Region = 10 //南美洲
	// 北美洲（加拿大、墨西哥等，不含美国）
	// @Description 北美洲
	// @example
	Region_RegionNorthAmerica Region = 11 //北美洲
	// 大洋洲
	// @Description 大洋洲
	// @example
	Region_RegionOceania Region = 12 //大洋洲
	// 巴西（独立处理）
	// @Description 巴西
	// @example
	Region_RegionBrazil Region = 13 //巴西
	// 印度（独立处理）
	// @Description 印度
	// @example
	Region_RegionIndia Region = 14 //印度
)

// Enum value maps for Region.
var (
	Region_name = map[int32]string{
		0:  "RegionUnknown",
		1:  "RegionChina",
		2:  "RegionUSA",
		3:  "RegionEastAsia",
		4:  "RegionSoutheastAsia",
		5:  "RegionSouthAsia",
		6:  "RegionMiddleEast",
		7:  "RegionEurope",
		8:  "RegionRussia",
		9:  "RegionAfrica",
		10: "RegionSouthAmerica",
		11: "RegionNorthAmerica",
		12: "RegionOceania",
		13: "RegionBrazil",
		14: "RegionIndia",
	}
	Region_value = map[string]int32{
		"RegionUnknown":       0,
		"RegionChina":         1,
		"RegionUSA":           2,
		"RegionEastAsia":      3,
		"RegionSoutheastAsia": 4,
		"RegionSouthAsia":     5,
		"RegionMiddleEast":    6,
		"RegionEurope":        7,
		"RegionRussia":        8,
		"RegionAfrica":        9,
		"RegionSouthAmerica":  10,
		"RegionNorthAmerica":  11,
		"RegionOceania":       12,
		"RegionBrazil":        13,
		"RegionIndia":         14,
	}
)

func (x Region) Enum() *Region {
	p := new(Region)
	*p = x
	return p
}

func (x Region) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Region) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[7].Descriptor()
}

func (Region) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[7]
}

func (x Region) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Region.Descriptor instead.
func (Region) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{7}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto*^\n" +
	"\bSginTyoe\x12\b\n" +
	"\x04Mail\x10\x00\x12\t\n" +
	"\x05Phone\x10\x01\x12\n" +
	"\n" +
	"\x06WXChat\x10\x02\x12\n" +
	"\n" +
	"\x06Google\x10\x03\x12\f\n" +
	"\bFaceBook\x10\x04\x12\t\n" +
	"\x05Apple\x10\x05\x12\f\n" +
	"\bTourists\x10\x06*4\n" +
	"\tUserState\x12\n" +
	"\n" +
	"\x06Normal\x10\x00\x12\f\n" +
	"\bDisabled\x10\x01\x12\r\n" +
	"\tCancelled\x10\x02*\xc2\x01\n" +
	"\n" +
	"DeviceType\x12\x15\n" +
	"\x11DeviceTypeUnknown\x10\x00\x12\x1d\n" +
	"\x19Classic_bluetooth_Headset\x10\x01\x12 \n" +
	"\x1cBLE_Bluetooth_Double_Headset\x10\x02\x12 \n" +
	"\x1cBLE_Bluetooth_Single_Headset\x10\x03\x12\x18\n" +
	"\x14Smart_Voice_Recorder\x10\x04\x12\f\n" +
	"\bSmartEye\x10\x05\x12\x12\n" +
	"\x0eActivationCard\x10\x06*@\n" +
	"\tUsageType\x12\r\n" +
	"\tUsageNull\x10\x00\x12\t\n" +
	"\x05Trade\x10\x01\x12\b\n" +
	"\x04Meet\x10\x02\x12\x06\n" +
	"\x02AI\x10\x03\x12\a\n" +
	"\x03VIP\x10\x04*b\n" +
	"\vUserLogType\x12\x16\n" +
	"\x12UserLogTypeUnknown\x10\x00\x12\a\n" +
	"\x03Pay\x10\x01\x12\x12\n" +
	"\x0eActivityReward\x10\x02\x12\r\n" +
	"\tAdminGive\x10\x03\x12\x0f\n" +
	"\vUserConsume\x10\x04*\"\n" +
	"\rMCPServerType\x12\b\n" +
	"\x04Http\x10\x00\x12\a\n" +
	"\x03SEE\x10\x01*m\n" +
	"\vAgentSource\x12\x16\n" +
	"\x12AgentSourceBuiltin\x10\x00\x12\x17\n" +
	"\x13AgentSourcePolyChat\x10\x01\x12\x15\n" +
	"\x11AgentSourceAliyun\x10\x02\x12\x16\n" +
	"\x12AgentSourceVolcano\x10\x03*\xaf\x02\n" +
	"\x06Region\x12\x11\n" +
	"\rRegionUnknown\x10\x00\x12\x0f\n" +
	"\vRegionChina\x10\x01\x12\r\n" +
	"\tRegionUSA\x10\x02\x12\x12\n" +
	"\x0eRegionEastAsia\x10\x03\x12\x17\n" +
	"\x13RegionSoutheastAsia\x10\x04\x12\x13\n" +
	"\x0fRegionSouthAsia\x10\x05\x12\x14\n" +
	"\x10RegionMiddleEast\x10\x06\x12\x10\n" +
	"\fRegionEurope\x10\a\x12\x10\n" +
	"\fRegionRussia\x10\b\x12\x10\n" +
	"\fRegionAfrica\x10\t\x12\x16\n" +
	"\x12RegionSouthAmerica\x10\n" +
	"\x12\x16\n" +
	"\x12RegionNorthAmerica\x10\v\x12\x11\n" +
	"\rRegionOceania\x10\f\x12\x10\n" +
	"\fRegionBrazil\x10\r\x12\x0f\n" +
	"\vRegionIndia\x10\x0eB\x06Z\x04.;pbb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_enum_proto_goTypes = []any{
	(SginTyoe)(0),      // 0: SginTyoe
	(UserState)(0),     // 1: UserState
	(DeviceType)(0),    // 2: DeviceType
	(UsageType)(0),     // 3: UsageType
	(UserLogType)(0),   // 4: UserLogType
	(MCPServerType)(0), // 5: MCPServerType
	(AgentSource)(0),   // 6: AgentSource
	(Region)(0),        // 7: Region
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
