// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: music/music_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求播放链接
type MusicUrlReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicUrlReq) Reset() {
	*x = MusicUrlReq{}
	mi := &file_music_music_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicUrlReq) ProtoMessage() {}

func (x *MusicUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_music_music_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicUrlReq.ProtoReflect.Descriptor instead.
func (*MusicUrlReq) Descriptor() ([]byte, []int) {
	return file_music_music_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MusicUrlReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type MusicUrlResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Ts            int64                  `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicUrlResp) Reset() {
	*x = MusicUrlResp{}
	mi := &file_music_music_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicUrlResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicUrlResp) ProtoMessage() {}

func (x *MusicUrlResp) ProtoReflect() protoreflect.Message {
	mi := &file_music_music_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicUrlResp.ProtoReflect.Descriptor instead.
func (*MusicUrlResp) Descriptor() ([]byte, []int) {
	return file_music_music_msg_proto_rawDescGZIP(), []int{1}
}

func (x *MusicUrlResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MusicUrlResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MusicUrlResp) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// 搜索音乐
type MusicSearchReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      string                 `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty" gorm:"keywords"`      // @go_tags(`gorm:"keywords"`) 关键词
	Searchtype    int32                  `protobuf:"varint,2,opt,name=searchtype,proto3" json:"searchtype,omitempty" gorm:"searchtype"` // @go_tags(`gorm:"searchtype"`) 搜索类型 0:歌曲 1:歌单
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty" gorm:"limit"`           // @go_tags(`gorm:"limit"`) 返回
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty" gorm:"offset"`         // @go_tags(`gorm:"offset"`) 偏移
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicSearchReq) Reset() {
	*x = MusicSearchReq{}
	mi := &file_music_music_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicSearchReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicSearchReq) ProtoMessage() {}

func (x *MusicSearchReq) ProtoReflect() protoreflect.Message {
	mi := &file_music_music_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicSearchReq.ProtoReflect.Descriptor instead.
func (*MusicSearchReq) Descriptor() ([]byte, []int) {
	return file_music_music_msg_proto_rawDescGZIP(), []int{2}
}

func (x *MusicSearchReq) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *MusicSearchReq) GetSearchtype() int32 {
	if x != nil {
		return x.Searchtype
	}
	return 0
}

func (x *MusicSearchReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MusicSearchReq) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MusicSearchResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Musics        []*DBMusic             `protobuf:"bytes,1,rep,name=musics,proto3" json:"musics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MusicSearchResp) Reset() {
	*x = MusicSearchResp{}
	mi := &file_music_music_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MusicSearchResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MusicSearchResp) ProtoMessage() {}

func (x *MusicSearchResp) ProtoReflect() protoreflect.Message {
	mi := &file_music_music_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MusicSearchResp.ProtoReflect.Descriptor instead.
func (*MusicSearchResp) Descriptor() ([]byte, []int) {
	return file_music_music_msg_proto_rawDescGZIP(), []int{3}
}

func (x *MusicSearchResp) GetMusics() []*DBMusic {
	if x != nil {
		return x.Musics
	}
	return nil
}

var File_music_music_msg_proto protoreflect.FileDescriptor

const file_music_music_msg_proto_rawDesc = "" +
	"\n" +
	"\x15music/music_msg.proto\x1a\x14music/music_db.proto\"\x1d\n" +
	"\vMusicUrlReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\fMusicUrlResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x0e\n" +
	"\x02ts\x18\x03 \x01(\x03R\x02ts\"z\n" +
	"\x0eMusicSearchReq\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\tR\bkeywords\x12\x1e\n" +
	"\n" +
	"searchtype\x18\x02 \x01(\x05R\n" +
	"searchtype\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"3\n" +
	"\x0fMusicSearchResp\x12 \n" +
	"\x06musics\x18\x01 \x03(\v2\b.DBMusicR\x06musicsB\x06Z\x04.;pbb\x06proto3"

var (
	file_music_music_msg_proto_rawDescOnce sync.Once
	file_music_music_msg_proto_rawDescData []byte
)

func file_music_music_msg_proto_rawDescGZIP() []byte {
	file_music_music_msg_proto_rawDescOnce.Do(func() {
		file_music_music_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_music_music_msg_proto_rawDesc), len(file_music_music_msg_proto_rawDesc)))
	})
	return file_music_music_msg_proto_rawDescData
}

var file_music_music_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_music_music_msg_proto_goTypes = []any{
	(*MusicUrlReq)(nil),     // 0: MusicUrlReq
	(*MusicUrlResp)(nil),    // 1: MusicUrlResp
	(*MusicSearchReq)(nil),  // 2: MusicSearchReq
	(*MusicSearchResp)(nil), // 3: MusicSearchResp
	(*DBMusic)(nil),         // 4: DBMusic
}
var file_music_music_msg_proto_depIdxs = []int32{
	4, // 0: MusicSearchResp.musics:type_name -> DBMusic
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_music_music_msg_proto_init() }
func file_music_music_msg_proto_init() {
	if File_music_music_msg_proto != nil {
		return
	}
	file_music_music_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_music_music_msg_proto_rawDesc), len(file_music_music_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_music_music_msg_proto_goTypes,
		DependencyIndexes: file_music_music_msg_proto_depIdxs,
		MessageInfos:      file_music_music_msg_proto_msgTypes,
	}.Build()
	File_music_music_msg_proto = out.File
	file_music_music_msg_proto_goTypes = nil
	file_music_music_msg_proto_depIdxs = nil
}
