// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: music/music_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBMusic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Singer        string                 `protobuf:"bytes,4,opt,name=singer,proto3" json:"singer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBMusic) Reset() {
	*x = DBMusic{}
	mi := &file_music_music_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBMusic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBMusic) ProtoMessage() {}

func (x *DBMusic) ProtoReflect() protoreflect.Message {
	mi := &file_music_music_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBMusic.ProtoReflect.Descriptor instead.
func (*DBMusic) Descriptor() ([]byte, []int) {
	return file_music_music_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBMusic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DBMusic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DBMusic) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DBMusic) GetSinger() string {
	if x != nil {
		return x.Singer
	}
	return ""
}

var File_music_music_db_proto protoreflect.FileDescriptor

const file_music_music_db_proto_rawDesc = "" +
	"\n" +
	"\x14music/music_db.proto\"[\n" +
	"\aDBMusic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06singer\x18\x04 \x01(\tR\x06singerB\x06Z\x04.;pbb\x06proto3"

var (
	file_music_music_db_proto_rawDescOnce sync.Once
	file_music_music_db_proto_rawDescData []byte
)

func file_music_music_db_proto_rawDescGZIP() []byte {
	file_music_music_db_proto_rawDescOnce.Do(func() {
		file_music_music_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_music_music_db_proto_rawDesc), len(file_music_music_db_proto_rawDesc)))
	})
	return file_music_music_db_proto_rawDescData
}

var file_music_music_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_music_music_db_proto_goTypes = []any{
	(*DBMusic)(nil), // 0: DBMusic
}
var file_music_music_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_music_music_db_proto_init() }
func file_music_music_db_proto_init() {
	if File_music_music_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_music_music_db_proto_rawDesc), len(file_music_music_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_music_music_db_proto_goTypes,
		DependencyIndexes: file_music_music_db_proto_depIdxs,
		MessageInfos:      file_music_music_db_proto_msgTypes,
	}.Build()
	File_music_music_db_proto = out.File
	file_music_music_db_proto_goTypes = nil
	file_music_music_db_proto_depIdxs = nil
}
