// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: pay/pay_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 读取商品列表
type PayGetGoodssReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayGetGoodssReq) Reset() {
	*x = PayGetGoodssReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayGetGoodssReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayGetGoodssReq) ProtoMessage() {}

func (x *PayGetGoodssReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayGetGoodssReq.ProtoReflect.Descriptor instead.
func (*PayGetGoodssReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{0}
}

type PayGetGoodssResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Goodss        []*DBGoods             `protobuf:"bytes,1,rep,name=goodss,proto3" json:"goodss,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayGetGoodssResp) Reset() {
	*x = PayGetGoodssResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayGetGoodssResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayGetGoodssResp) ProtoMessage() {}

func (x *PayGetGoodssResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayGetGoodssResp.ProtoReflect.Descriptor instead.
func (*PayGetGoodssResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{1}
}

func (x *PayGetGoodssResp) GetGoodss() []*DBGoods {
	if x != nil {
		return x.Goodss
	}
	return nil
}

// 读取用户订单信息
type PayGetOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page"` //@go_tags(`json:"page"`) 页码（从1开始）
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"` //@go_tags(`json:"size"`) 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayGetOrderListReq) Reset() {
	*x = PayGetOrderListReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayGetOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayGetOrderListReq) ProtoMessage() {}

func (x *PayGetOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayGetOrderListReq.ProtoReflect.Descriptor instead.
func (*PayGetOrderListReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{2}
}

func (x *PayGetOrderListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PayGetOrderListReq) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PayGetOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orderss       []*DBPayOrder          `protobuf:"bytes,1,rep,name=orderss,proto3" json:"orderss,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"` //@go_tags(`json:"total"`) 总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayGetOrderListResp) Reset() {
	*x = PayGetOrderListResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayGetOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayGetOrderListResp) ProtoMessage() {}

func (x *PayGetOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayGetOrderListResp.ProtoReflect.Descriptor instead.
func (*PayGetOrderListResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{3}
}

func (x *PayGetOrderListResp) GetOrderss() []*DBPayOrder {
	if x != nil {
		return x.Orderss
	}
	return nil
}

func (x *PayGetOrderListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// 支付相关接口----------------------------------------------------------------
// 创建支付订单
type PayCreatePayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id" binding:"required"`                                 //@go_tags(`json:"product_id" binding:"required"`) 商品ID
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name" binding:"required"`                           //@go_tags(`json:"product_name" binding:"required"`) 商品名称
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount" binding:"required,min=1"`                                                       //@go_tags(`json:"amount" binding:"required,min=1"`) 订单金额(分)
	PaymentMethod PaymentMethod          `protobuf:"varint,5,opt,name=payment_method,json=paymentMethod,proto3,enum=PaymentMethod" json:"payment_method" binding:"required"` //@go_tags(`json:"payment_method" binding:"required"`) 支付方式
	ClientIp      string                 `protobuf:"bytes,6,opt,name=client_ip,json=clientIp,proto3" json:"client_ip"`                                    //@go_tags(`json:"client_ip"`) 客户端IP
	ExtraData     string                 `protobuf:"bytes,7,opt,name=extra_data,json=extraData,proto3" json:"extra_data"`                                 //@go_tags(`json:"extra_data"`) 扩展数据
	NotifyUrl     string                 `protobuf:"bytes,8,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url" binding:"required,url"`                                 //@go_tags(`json:"notify_url" binding:"required,url"`) 异步通知地址（支付结果回调）
	ReturnUrl     string                 `protobuf:"bytes,9,opt,name=return_url,json=returnUrl,proto3" json:"return_url" binding:"required,url"`                                 //@go_tags(`json:"return_url" binding:"required,url"`) 返回地址（支付成功后跳转）
	CancelUrl     string                 `protobuf:"bytes,10,opt,name=cancel_url,json=cancelUrl,proto3" json:"cancel_url" binding:"required,url"`                                //@go_tags(`json:"cancel_url" binding:"required,url"`) 取消地址（支付失败后跳转）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCreatePayOrderReq) Reset() {
	*x = PayCreatePayOrderReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCreatePayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCreatePayOrderReq) ProtoMessage() {}

func (x *PayCreatePayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCreatePayOrderReq.ProtoReflect.Descriptor instead.
func (*PayCreatePayOrderReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{4}
}

func (x *PayCreatePayOrderReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PayCreatePayOrderReq) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_UnknownPaymentMethod
}

func (x *PayCreatePayOrderReq) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetReturnUrl() string {
	if x != nil {
		return x.ReturnUrl
	}
	return ""
}

func (x *PayCreatePayOrderReq) GetCancelUrl() string {
	if x != nil {
		return x.CancelUrl
	}
	return ""
}

type PayCreatePayOrderResp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Orderid         string                 `protobuf:"bytes,1,opt,name=orderid,proto3" json:"order_id"`                                          //@go_tags(`json:"order_id"`) 订单ID
	ProductId       string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id" binding:"required"`                     //@go_tags(`json:"product_id" binding:"required"`) 商品ID
	ProductName     string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name" binding:"required"`               //@go_tags(`json:"product_name" binding:"required"`) 商品名称
	PayParams       *AppPayParams          `protobuf:"bytes,5,opt,name=pay_params,json=payParams,proto3" json:"pay_params"`                     //@go_tags(`json:"pay_params"`) 支付参数
	AlipayPayParams string                 `protobuf:"bytes,6,opt,name=alipay_pay_params,json=alipayPayParams,proto3" json:"alipay_pay_params"` //@go_tags(`json:"alipay_pay_params"`) 支付宝支付参数
	PaypalPayParams string                 `protobuf:"bytes,7,opt,name=paypal_pay_params,json=paypalPayParams,proto3" json:"paypal_pay_params"` //@go_tags(`json:"paypal_pay_params"`) PayPal 支付参数
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayCreatePayOrderResp) Reset() {
	*x = PayCreatePayOrderResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCreatePayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCreatePayOrderResp) ProtoMessage() {}

func (x *PayCreatePayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCreatePayOrderResp.ProtoReflect.Descriptor instead.
func (*PayCreatePayOrderResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{5}
}

func (x *PayCreatePayOrderResp) GetOrderid() string {
	if x != nil {
		return x.Orderid
	}
	return ""
}

func (x *PayCreatePayOrderResp) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PayCreatePayOrderResp) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *PayCreatePayOrderResp) GetPayParams() *AppPayParams {
	if x != nil {
		return x.PayParams
	}
	return nil
}

func (x *PayCreatePayOrderResp) GetAlipayPayParams() string {
	if x != nil {
		return x.AlipayPayParams
	}
	return ""
}

func (x *PayCreatePayOrderResp) GetPaypalPayParams() string {
	if x != nil {
		return x.PaypalPayParams
	}
	return ""
}

// 查询订单星系
type PayAskOrCancelReq struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Orderid string                 `protobuf:"bytes,1,opt,name=orderid,proto3" json:"order_id"` //@go_tags(`json:"order_id"`) 订单ID
	// 以下字段用于 Apple/Google 主动校验（客户端发起查询时一并传入）
	AppleReceiptData      string `protobuf:"bytes,2,opt,name=apple_receipt_data,json=appleReceiptData,proto3" json:"apple_receipt_data"`                   //@go_tags(`json:"apple_receipt_data"`) 苹果收据数据或交易ID
	AppleUseTransactionId bool   `protobuf:"varint,3,opt,name=apple_use_transaction_id,json=appleUseTransactionId,proto3" json:"apple_use_transaction_id"` //@go_tags(`json:"apple_use_transaction_id"`) 是否按交易ID校验
	GooglePackageName     string `protobuf:"bytes,5,opt,name=google_package_name,json=googlePackageName,proto3" json:"google_package_name"`                //@go_tags(`json:"google_package_name"`) 谷歌包名
	GoogleProductId       string `protobuf:"bytes,6,opt,name=google_product_id,json=googleProductId,proto3" json:"google_product_id"`                      //@go_tags(`json:"google_product_id"`) 谷歌商品/订阅ID
	GooglePurchaseToken   string `protobuf:"bytes,7,opt,name=google_purchase_token,json=googlePurchaseToken,proto3" json:"google_purchase_token"`          //@go_tags(`json:"google_purchase_token"`) 谷歌购买Token
	GoogleIsSubscription  bool   `protobuf:"varint,8,opt,name=google_is_subscription,json=googleIsSubscription,proto3" json:"google_is_subscription"`      //@go_tags(`json:"google_is_subscription"`) 是否订阅类型
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PayAskOrCancelReq) Reset() {
	*x = PayAskOrCancelReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayAskOrCancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayAskOrCancelReq) ProtoMessage() {}

func (x *PayAskOrCancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayAskOrCancelReq.ProtoReflect.Descriptor instead.
func (*PayAskOrCancelReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{6}
}

func (x *PayAskOrCancelReq) GetOrderid() string {
	if x != nil {
		return x.Orderid
	}
	return ""
}

func (x *PayAskOrCancelReq) GetAppleReceiptData() string {
	if x != nil {
		return x.AppleReceiptData
	}
	return ""
}

func (x *PayAskOrCancelReq) GetAppleUseTransactionId() bool {
	if x != nil {
		return x.AppleUseTransactionId
	}
	return false
}

func (x *PayAskOrCancelReq) GetGooglePackageName() string {
	if x != nil {
		return x.GooglePackageName
	}
	return ""
}

func (x *PayAskOrCancelReq) GetGoogleProductId() string {
	if x != nil {
		return x.GoogleProductId
	}
	return ""
}

func (x *PayAskOrCancelReq) GetGooglePurchaseToken() string {
	if x != nil {
		return x.GooglePurchaseToken
	}
	return ""
}

func (x *PayAskOrCancelReq) GetGoogleIsSubscription() bool {
	if x != nil {
		return x.GoogleIsSubscription
	}
	return false
}

type PayPayOrderAskResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *DBPayOrder            `protobuf:"bytes,1,opt,name=order,proto3" json:"order"` //@go_tags(`json:"order"`) 订单ID
	User          *DBUser                `protobuf:"bytes,2,opt,name=user,proto3" json:"user"`   //@go_tags(`json:"user"`) 用户信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPayOrderAskResp) Reset() {
	*x = PayPayOrderAskResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPayOrderAskResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPayOrderAskResp) ProtoMessage() {}

func (x *PayPayOrderAskResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPayOrderAskResp.ProtoReflect.Descriptor instead.
func (*PayPayOrderAskResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{7}
}

func (x *PayPayOrderAskResp) GetOrder() *DBPayOrder {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PayPayOrderAskResp) GetUser() *DBUser {
	if x != nil {
		return x.User
	}
	return nil
}

type PayWeChatNotifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                         // 通知ID（微信生成的唯一标识）
	CreateTime    string                 `protobuf:"bytes,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`       // 通知创建时间（格式：yyyy-MM-dd'T'HH:mm:ss+TIMEZONE）
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"` // 通知类型（固定为"transaction"）
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`          // 事件类型（如"TRANSACTION.SUCCESS"）
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`                               // 通知摘要（如"支付成功"）
	Resource      *Resource              `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`                             // 加密的核心资源数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWeChatNotifyReq) Reset() {
	*x = PayWeChatNotifyReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWeChatNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWeChatNotifyReq) ProtoMessage() {}

func (x *PayWeChatNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWeChatNotifyReq.ProtoReflect.Descriptor instead.
func (*PayWeChatNotifyReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{8}
}

func (x *PayWeChatNotifyReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PayWeChatNotifyReq) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *PayWeChatNotifyReq) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *PayWeChatNotifyReq) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PayWeChatNotifyReq) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *PayWeChatNotifyReq) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type PayWeChatNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayWeChatNotifyResp) Reset() {
	*x = PayWeChatNotifyResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayWeChatNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayWeChatNotifyResp) ProtoMessage() {}

func (x *PayWeChatNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayWeChatNotifyResp.ProtoReflect.Descriptor instead.
func (*PayWeChatNotifyResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{9}
}

// 加密资源结构（包含需解密的核心交易数据）
type Resource struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Algorithm      string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                                 // 加密算法（固定为"AEAD_AES_256_GCM"）
	Ciphertext     string                 `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`                               // 加密后的交易数据（base64编码）
	AssociatedData string                 `protobuf:"bytes,3,opt,name=associated_data,json=associatedData,proto3" json:"associated_data,omitempty"` // 附加数据（解密时使用）
	Nonce          string                 `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`                                         // 随机串（解密时使用）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_pay_pay_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{10}
}

func (x *Resource) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Resource) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *Resource) GetAssociatedData() string {
	if x != nil {
		return x.AssociatedData
	}
	return ""
}

func (x *Resource) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

// 解密后的核心交易数据（对应 ciphertext 解密结果）
type WxPayTransaction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 订单基础信息
	OutTradeNo     string `protobuf:"bytes,1,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no,omitempty"`             // 商户订单号（系统生成的订单ID）
	TransactionId  string `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`      // 微信支付订单号（微信生成）
	Mchid          string `protobuf:"bytes,3,opt,name=mchid,proto3" json:"mchid,omitempty"`                                           // 商户号
	Appid          string `protobuf:"bytes,4,opt,name=appid,proto3" json:"appid,omitempty"`                                           // 应用ID
	TradeType      string `protobuf:"bytes,5,opt,name=trade_type,json=tradeType,proto3" json:"trade_type,omitempty"`                  // 交易类型（App支付为"APP"）
	TradeState     string `protobuf:"bytes,6,opt,name=trade_state,json=tradeState,proto3" json:"trade_state,omitempty"`               // 支付状态（核心字段，如"SUCCESS"）
	TradeStateDesc string `protobuf:"bytes,7,opt,name=trade_state_desc,json=tradeStateDesc,proto3" json:"trade_state_desc,omitempty"` // 支付状态描述
	// 金额信息
	Amount *Amount `protobuf:"bytes,8,opt,name=amount,proto3" json:"amount,omitempty"` // 金额详情
	// 支付者信息
	Payer *Payer `protobuf:"bytes,9,opt,name=payer,proto3" json:"payer,omitempty"` // 支付者信息
	// 时间信息
	SuccessTime string `protobuf:"bytes,10,opt,name=success_time,json=successTime,proto3" json:"success_time,omitempty"` // 支付成功时间（仅支付成功时存在）
	CreateTime  string `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`    // 订单创建时间
	CloseTime   string `protobuf:"bytes,12,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`       // 订单关闭时间（仅关闭时存在）
	// 附加信息
	Attach        string `protobuf:"bytes,13,opt,name=attach,proto3" json:"attach,omitempty"`                           // 附加数据（下单时传入）
	NotifyUrl     string `protobuf:"bytes,14,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url,omitempty"`    // 回调通知地址
	NotifyTime    string `protobuf:"bytes,15,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"` // 回调通知时间
	NotifyId      string `protobuf:"bytes,16,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`       // 回调通知ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WxPayTransaction) Reset() {
	*x = WxPayTransaction{}
	mi := &file_pay_pay_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WxPayTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxPayTransaction) ProtoMessage() {}

func (x *WxPayTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxPayTransaction.ProtoReflect.Descriptor instead.
func (*WxPayTransaction) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{11}
}

func (x *WxPayTransaction) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *WxPayTransaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *WxPayTransaction) GetMchid() string {
	if x != nil {
		return x.Mchid
	}
	return ""
}

func (x *WxPayTransaction) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *WxPayTransaction) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *WxPayTransaction) GetTradeState() string {
	if x != nil {
		return x.TradeState
	}
	return ""
}

func (x *WxPayTransaction) GetTradeStateDesc() string {
	if x != nil {
		return x.TradeStateDesc
	}
	return ""
}

func (x *WxPayTransaction) GetAmount() *Amount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *WxPayTransaction) GetPayer() *Payer {
	if x != nil {
		return x.Payer
	}
	return nil
}

func (x *WxPayTransaction) GetSuccessTime() string {
	if x != nil {
		return x.SuccessTime
	}
	return ""
}

func (x *WxPayTransaction) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *WxPayTransaction) GetCloseTime() string {
	if x != nil {
		return x.CloseTime
	}
	return ""
}

func (x *WxPayTransaction) GetAttach() string {
	if x != nil {
		return x.Attach
	}
	return ""
}

func (x *WxPayTransaction) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *WxPayTransaction) GetNotifyTime() string {
	if x != nil {
		return x.NotifyTime
	}
	return ""
}

func (x *WxPayTransaction) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

// 金额详情
type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                     // 订单总金额（分）
	PayerTotal    int64                  `protobuf:"varint,2,opt,name=payer_total,json=payerTotal,proto3" json:"payer_total,omitempty"`         // 支付金额（用户实际支付）
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`                                // 货币类型（默认"CNY"）
	PayerCurrency string                 `protobuf:"bytes,4,opt,name=payer_currency,json=payerCurrency,proto3" json:"payer_currency,omitempty"` // 用户支付的货币类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_pay_pay_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{12}
}

func (x *Amount) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Amount) GetPayerTotal() int64 {
	if x != nil {
		return x.PayerTotal
	}
	return 0
}

func (x *Amount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Amount) GetPayerCurrency() string {
	if x != nil {
		return x.PayerCurrency
	}
	return ""
}

// 支付者信息
type Payer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Openid        string                 `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"` // 用户唯一标识（App支付可能为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payer) Reset() {
	*x = Payer{}
	mi := &file_pay_pay_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payer) ProtoMessage() {}

func (x *Payer) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payer.ProtoReflect.Descriptor instead.
func (*Payer) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{13}
}

func (x *Payer) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

// 支付宝异步通知参数
type PayAlipayNotifyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id"`                              //@go_tags(`json:"app_id"`) 支付宝分配的appid
	AuthAppId      string                 `protobuf:"bytes,2,opt,name=auth_app_id,json=authAppId,proto3" json:"auth_app_id"`                //@go_tags(`json:"auth_app_id"`) 授权方的appid（若无则与app_id一致）
	BuyerId        string                 `protobuf:"bytes,3,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id"`                        //@go_tags(`json:"buyer_id"`) 买家支付宝用户ID
	BuyerLogonId   string                 `protobuf:"bytes,4,opt,name=buyer_logon_id,json=buyerLogonId,proto3" json:"buyer_logon_id"`       //@go_tags(`json:"buyer_logon_id"`) 买家支付宝账号（脱敏）
	BuyerPayAmount string                 `protobuf:"bytes,5,opt,name=buyer_pay_amount,json=buyerPayAmount,proto3" json:"buyer_pay_amount"` //@go_tags(`json:"buyer_pay_amount"`) 买家实付金额
	Charset        string                 `protobuf:"bytes,6,opt,name=charset,proto3" json:"charset"`                                       //@go_tags(`json:"charset"`) 编码格式（如utf-8）
	FundBillList   string                 `protobuf:"bytes,7,opt,name=fund_bill_list,json=fundBillList,proto3" json:"fund_bill_list"`       //@go_tags(`json:"fund_bill_list"`) 支付方式明细（JSON字符串，如[{"amount":"0.01","fundChannel":"ALIPAYACCOUNT"}]）
	GmtCreate      string                 `protobuf:"bytes,8,opt,name=gmt_create,json=gmtCreate,proto3" json:"gmt_create"`                  //@go_tags(`json:"gmt_create"`) 交易创建时间
	GmtPayment     string                 `protobuf:"bytes,9,opt,name=gmt_payment,json=gmtPayment,proto3" json:"gmt_payment"`               //@go_tags(`json:"gmt_payment"`) 支付时间
	InvoiceAmount  string                 `protobuf:"bytes,10,opt,name=invoice_amount,json=invoiceAmount,proto3" json:"invoice_amount"`     //@go_tags(`json:"invoice_amount"`) 可开票金额
	NotifyId       string                 `protobuf:"bytes,11,opt,name=notify_id,json=notifyId,proto3" json:"notify_id"`                    //@go_tags(`json:"notify_id"`) 通知ID（唯一）
	NotifyTime     string                 `protobuf:"bytes,12,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time"`              //@go_tags(`json:"notify_time"`) 通知发送时间
	NotifyType     string                 `protobuf:"bytes,13,opt,name=notify_type,json=notifyType,proto3" json:"notify_type"`              //@go_tags(`json:"notify_type"`) 通知类型（如trade_status_sync）
	OutTradeNo     string                 `protobuf:"bytes,14,opt,name=out_trade_no,json=outTradeNo,proto3" json:"out_trade_no"`            //@go_tags(`json:"out_trade_no"`) 商户订单号（你的系统订单号）
	PointAmount    string                 `protobuf:"bytes,15,opt,name=point_amount,json=pointAmount,proto3" json:"point_amount"`           //@go_tags(`json:"point_amount"`) 积分支付金额
	ReceiptAmount  string                 `protobuf:"bytes,16,opt,name=receipt_amount,json=receiptAmount,proto3" json:"receipt_amount"`     //@go_tags(`json:"receipt_amount"`) 商家实收金额
	SellerEmail    string                 `protobuf:"bytes,17,opt,name=seller_email,json=sellerEmail,proto3" json:"seller_email"`           //@go_tags(`json:"seller_email"`) 卖家支付宝账号
	SellerId       string                 `protobuf:"bytes,18,opt,name=seller_id,json=sellerId,proto3" json:"seller_id"`                    //@go_tags(`json:"seller_id"`) 卖家支付宝用户ID
	Sign           string                 `protobuf:"bytes,19,opt,name=sign,proto3" json:"sign"`                                            //@go_tags(`json:"sign"`) 签名
	SignType       string                 `protobuf:"bytes,20,opt,name=sign_type,json=signType,proto3" json:"sign_type"`                    //@go_tags(`json:"sign_type"`) 签名类型（如RSA2）
	Subject        string                 `protobuf:"bytes,21,opt,name=subject,proto3" json:"subject"`                                      //@go_tags(`json:"subject"`) 订单标题
	TotalAmount    string                 `protobuf:"bytes,22,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount"`           //@go_tags(`json:"total_amount"`) 订单总金额
	TradeNo        string                 `protobuf:"bytes,23,opt,name=trade_no,json=tradeNo,proto3" json:"trade_no"`                       //@go_tags(`json:"trade_no"`) 支付宝交易号
	TradeStatus    string                 `protobuf:"bytes,24,opt,name=trade_status,json=tradeStatus,proto3" json:"trade_status"`           //@go_tags(`json:"trade_status"`) 交易状态（TRADE_SUCCESS表示成功）
	Version        string                 `protobuf:"bytes,25,opt,name=version,proto3" json:"version"`                                      //@go_tags(`json:"version"`) 版本号（如1.0）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PayAlipayNotifyReq) Reset() {
	*x = PayAlipayNotifyReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayAlipayNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayAlipayNotifyReq) ProtoMessage() {}

func (x *PayAlipayNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayAlipayNotifyReq.ProtoReflect.Descriptor instead.
func (*PayAlipayNotifyReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{14}
}

func (x *PayAlipayNotifyReq) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetAuthAppId() string {
	if x != nil {
		return x.AuthAppId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetBuyerId() string {
	if x != nil {
		return x.BuyerId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetBuyerLogonId() string {
	if x != nil {
		return x.BuyerLogonId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetBuyerPayAmount() string {
	if x != nil {
		return x.BuyerPayAmount
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetFundBillList() string {
	if x != nil {
		return x.FundBillList
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetGmtCreate() string {
	if x != nil {
		return x.GmtCreate
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetGmtPayment() string {
	if x != nil {
		return x.GmtPayment
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetInvoiceAmount() string {
	if x != nil {
		return x.InvoiceAmount
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetNotifyId() string {
	if x != nil {
		return x.NotifyId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetNotifyTime() string {
	if x != nil {
		return x.NotifyTime
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetNotifyType() string {
	if x != nil {
		return x.NotifyType
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetOutTradeNo() string {
	if x != nil {
		return x.OutTradeNo
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetPointAmount() string {
	if x != nil {
		return x.PointAmount
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetReceiptAmount() string {
	if x != nil {
		return x.ReceiptAmount
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetSellerEmail() string {
	if x != nil {
		return x.SellerEmail
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetSignType() string {
	if x != nil {
		return x.SignType
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetTotalAmount() string {
	if x != nil {
		return x.TotalAmount
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetTradeNo() string {
	if x != nil {
		return x.TradeNo
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetTradeStatus() string {
	if x != nil {
		return x.TradeStatus
	}
	return ""
}

func (x *PayAlipayNotifyReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PayAlipayNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayAlipayNotifyResp) Reset() {
	*x = PayAlipayNotifyResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayAlipayNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayAlipayNotifyResp) ProtoMessage() {}

func (x *PayAlipayNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayAlipayNotifyResp.ProtoReflect.Descriptor instead.
func (*PayAlipayNotifyResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{15}
}

// PayPal 异步通知参数（包含验签所需头和原始 body）
type PayPayPalNotifyReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransmissionId   string                 `protobuf:"bytes,1,opt,name=transmission_id,json=transmissionId,proto3" json:"transmission_id"`       //@go_tags(`json:"transmission_id"`) PayPal-Transmission-Id
	TransmissionTime string                 `protobuf:"bytes,2,opt,name=transmission_time,json=transmissionTime,proto3" json:"transmission_time"` //@go_tags(`json:"transmission_time"`) PayPal-Transmission-Time
	CertUrl          string                 `protobuf:"bytes,3,opt,name=cert_url,json=certUrl,proto3" json:"cert_url"`                            //@go_tags(`json:"cert_url"`) PayPal-Cert-Url
	AuthAlgo         string                 `protobuf:"bytes,4,opt,name=auth_algo,json=authAlgo,proto3" json:"auth_algo"`                         //@go_tags(`json:"auth_algo"`) PayPal-Auth-Algo
	TransmissionSig  string                 `protobuf:"bytes,5,opt,name=transmission_sig,json=transmissionSig,proto3" json:"transmission_sig"`    //@go_tags(`json:"transmission_sig"`) PayPal-Transmission-Sig
	WebhookId        string                 `protobuf:"bytes,6,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id"`                      //@go_tags(`json:"webhook_id"`) Webhook-Id（配置的 WebhookID）
	Body             string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body"`                                                 //@go_tags(`json:"body"`) 原始 JSON 通知体
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PayPayPalNotifyReq) Reset() {
	*x = PayPayPalNotifyReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPayPalNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPayPalNotifyReq) ProtoMessage() {}

func (x *PayPayPalNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPayPalNotifyReq.ProtoReflect.Descriptor instead.
func (*PayPayPalNotifyReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{16}
}

func (x *PayPayPalNotifyReq) GetTransmissionId() string {
	if x != nil {
		return x.TransmissionId
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetTransmissionTime() string {
	if x != nil {
		return x.TransmissionTime
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetCertUrl() string {
	if x != nil {
		return x.CertUrl
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetAuthAlgo() string {
	if x != nil {
		return x.AuthAlgo
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetTransmissionSig() string {
	if x != nil {
		return x.TransmissionSig
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *PayPayPalNotifyReq) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type PayPayPalNotifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code"`       //@go_tags(`json:"code"`) 返回码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` //@go_tags(`json:"message"`) 返回消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayPayPalNotifyResp) Reset() {
	*x = PayPayPalNotifyResp{}
	mi := &file_pay_pay_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayPayPalNotifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayPayPalNotifyResp) ProtoMessage() {}

func (x *PayPayPalNotifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayPayPalNotifyResp.ProtoReflect.Descriptor instead.
func (*PayPayPalNotifyResp) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{17}
}

func (x *PayPayPalNotifyResp) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PayPayPalNotifyResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Apple IAP 异步通知参数（由网关层解析 JSON/values 后封装为 PB）
type PayAppleIAPNotifyReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uid              string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid"`                                                      //@go_tags(`json:"uid"`) 用户ID
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id"`                               //@go_tags(`json:"order_id"`) 订单ID
	ProductId        string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id"`                         //@go_tags(`json:"product_id"`) 商品ID或订阅ID
	ReceiptData      string                 `protobuf:"bytes,4,opt,name=receipt_data,json=receiptData,proto3" json:"receipt_data"`                   //@go_tags(`json:"receipt_data"`) 收据数据或交易ID
	UseTransactionId bool                   `protobuf:"varint,5,opt,name=use_transaction_id,json=useTransactionId,proto3" json:"use_transaction_id"` //@go_tags(`json:"use_transaction_id"`) 是否使用交易ID模式校验
	Sandbox          bool                   `protobuf:"varint,6,opt,name=sandbox,proto3" json:"sandbox"`                                             //@go_tags(`json:"sandbox"`) 是否沙箱环境
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PayAppleIAPNotifyReq) Reset() {
	*x = PayAppleIAPNotifyReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayAppleIAPNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayAppleIAPNotifyReq) ProtoMessage() {}

func (x *PayAppleIAPNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayAppleIAPNotifyReq.ProtoReflect.Descriptor instead.
func (*PayAppleIAPNotifyReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{18}
}

func (x *PayAppleIAPNotifyReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PayAppleIAPNotifyReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayAppleIAPNotifyReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PayAppleIAPNotifyReq) GetReceiptData() string {
	if x != nil {
		return x.ReceiptData
	}
	return ""
}

func (x *PayAppleIAPNotifyReq) GetUseTransactionId() bool {
	if x != nil {
		return x.UseTransactionId
	}
	return false
}

func (x *PayAppleIAPNotifyReq) GetSandbox() bool {
	if x != nil {
		return x.Sandbox
	}
	return false
}

// Google IAP 异步通知参数（由网关层解析 JSON/values 后封装为 PB）
type PayGoogleIAPNotifyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid"`                                              //@go_tags(`json:"uid"`) 用户ID
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id"`                       //@go_tags(`json:"order_id"`) 订单ID
	PackageName    string                 `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name"`           //@go_tags(`json:"package_name"`) 应用包名
	ProductId      string                 `protobuf:"bytes,4,opt,name=product_id,json=productId,proto3" json:"product_id"`                 //@go_tags(`json:"product_id"`) 商品ID或订阅ID
	PurchaseToken  string                 `protobuf:"bytes,5,opt,name=purchase_token,json=purchaseToken,proto3" json:"purchase_token"`     //@go_tags(`json:"purchase_token"`) 购买Token
	IsSubscription bool                   `protobuf:"varint,6,opt,name=is_subscription,json=isSubscription,proto3" json:"is_subscription"` //@go_tags(`json:"is_subscription"`) 是否为订阅类型
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PayGoogleIAPNotifyReq) Reset() {
	*x = PayGoogleIAPNotifyReq{}
	mi := &file_pay_pay_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayGoogleIAPNotifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayGoogleIAPNotifyReq) ProtoMessage() {}

func (x *PayGoogleIAPNotifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayGoogleIAPNotifyReq.ProtoReflect.Descriptor instead.
func (*PayGoogleIAPNotifyReq) Descriptor() ([]byte, []int) {
	return file_pay_pay_msg_proto_rawDescGZIP(), []int{19}
}

func (x *PayGoogleIAPNotifyReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *PayGoogleIAPNotifyReq) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PayGoogleIAPNotifyReq) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PayGoogleIAPNotifyReq) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *PayGoogleIAPNotifyReq) GetPurchaseToken() string {
	if x != nil {
		return x.PurchaseToken
	}
	return ""
}

func (x *PayGoogleIAPNotifyReq) GetIsSubscription() bool {
	if x != nil {
		return x.IsSubscription
	}
	return false
}

var File_pay_pay_msg_proto protoreflect.FileDescriptor

const file_pay_pay_msg_proto_rawDesc = "" +
	"\n" +
	"\x11pay/pay_msg.proto\x1a\bdb.proto\x1a\x10pay/pay_db.proto\"\x11\n" +
	"\x0fPayGetGoodssReq\"4\n" +
	"\x10PayGetGoodssResp\x12 \n" +
	"\x06goodss\x18\x01 \x03(\v2\b.DBGoodsR\x06goodss\"<\n" +
	"\x12PayGetOrderListReq\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"R\n" +
	"\x13PayGetOrderListResp\x12%\n" +
	"\aorderss\x18\x01 \x03(\v2\v.DBPayOrderR\aorderss\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xc0\x02\n" +
	"\x14PayCreatePayOrderReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x125\n" +
	"\x0epayment_method\x18\x05 \x01(\x0e2\x0e.PaymentMethodR\rpaymentMethod\x12\x1b\n" +
	"\tclient_ip\x18\x06 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"extra_data\x18\a \x01(\tR\textraData\x12\x1d\n" +
	"\n" +
	"notify_url\x18\b \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"return_url\x18\t \x01(\tR\treturnUrl\x12\x1d\n" +
	"\n" +
	"cancel_url\x18\n" +
	" \x01(\tR\tcancelUrl\"\xf9\x01\n" +
	"\x15PayCreatePayOrderResp\x12\x18\n" +
	"\aorderid\x18\x01 \x01(\tR\aorderid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12,\n" +
	"\n" +
	"pay_params\x18\x05 \x01(\v2\r.AppPayParamsR\tpayParams\x12*\n" +
	"\x11alipay_pay_params\x18\x06 \x01(\tR\x0falipayPayParams\x12*\n" +
	"\x11paypal_pay_params\x18\a \x01(\tR\x0fpaypalPayParams\"\xda\x02\n" +
	"\x11PayAskOrCancelReq\x12\x18\n" +
	"\aorderid\x18\x01 \x01(\tR\aorderid\x12,\n" +
	"\x12apple_receipt_data\x18\x02 \x01(\tR\x10appleReceiptData\x127\n" +
	"\x18apple_use_transaction_id\x18\x03 \x01(\bR\x15appleUseTransactionId\x12.\n" +
	"\x13google_package_name\x18\x05 \x01(\tR\x11googlePackageName\x12*\n" +
	"\x11google_product_id\x18\x06 \x01(\tR\x0fgoogleProductId\x122\n" +
	"\x15google_purchase_token\x18\a \x01(\tR\x13googlePurchaseToken\x124\n" +
	"\x16google_is_subscription\x18\b \x01(\bR\x14googleIsSubscription\"T\n" +
	"\x12PayPayOrderAskResp\x12!\n" +
	"\x05order\x18\x01 \x01(\v2\v.DBPayOrderR\x05order\x12\x1b\n" +
	"\x04user\x18\x02 \x01(\v2\a.DBUserR\x04user\"\xca\x01\n" +
	"\x12PayWeChatNotifyReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\tR\n" +
	"createTime\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12%\n" +
	"\bresource\x18\x06 \x01(\v2\t.ResourceR\bresource\"\x15\n" +
	"\x13PayWeChatNotifyResp\"\x87\x01\n" +
	"\bResource\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\tR\n" +
	"ciphertext\x12'\n" +
	"\x0fassociated_data\x18\x03 \x01(\tR\x0eassociatedData\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\"\x88\x04\n" +
	"\x10WxPayTransaction\x12 \n" +
	"\fout_trade_no\x18\x01 \x01(\tR\n" +
	"outTradeNo\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x14\n" +
	"\x05mchid\x18\x03 \x01(\tR\x05mchid\x12\x14\n" +
	"\x05appid\x18\x04 \x01(\tR\x05appid\x12\x1d\n" +
	"\n" +
	"trade_type\x18\x05 \x01(\tR\ttradeType\x12\x1f\n" +
	"\vtrade_state\x18\x06 \x01(\tR\n" +
	"tradeState\x12(\n" +
	"\x10trade_state_desc\x18\a \x01(\tR\x0etradeStateDesc\x12\x1f\n" +
	"\x06amount\x18\b \x01(\v2\a.AmountR\x06amount\x12\x1c\n" +
	"\x05payer\x18\t \x01(\v2\x06.PayerR\x05payer\x12!\n" +
	"\fsuccess_time\x18\n" +
	" \x01(\tR\vsuccessTime\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\tR\n" +
	"createTime\x12\x1d\n" +
	"\n" +
	"close_time\x18\f \x01(\tR\tcloseTime\x12\x16\n" +
	"\x06attach\x18\r \x01(\tR\x06attach\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x0e \x01(\tR\tnotifyUrl\x12\x1f\n" +
	"\vnotify_time\x18\x0f \x01(\tR\n" +
	"notifyTime\x12\x1b\n" +
	"\tnotify_id\x18\x10 \x01(\tR\bnotifyId\"\x82\x01\n" +
	"\x06Amount\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1f\n" +
	"\vpayer_total\x18\x02 \x01(\x03R\n" +
	"payerTotal\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayer_currency\x18\x04 \x01(\tR\rpayerCurrency\"\x1f\n" +
	"\x05Payer\x12\x16\n" +
	"\x06openid\x18\x01 \x01(\tR\x06openid\"\xae\x06\n" +
	"\x12PayAlipayNotifyReq\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1e\n" +
	"\vauth_app_id\x18\x02 \x01(\tR\tauthAppId\x12\x19\n" +
	"\bbuyer_id\x18\x03 \x01(\tR\abuyerId\x12$\n" +
	"\x0ebuyer_logon_id\x18\x04 \x01(\tR\fbuyerLogonId\x12(\n" +
	"\x10buyer_pay_amount\x18\x05 \x01(\tR\x0ebuyerPayAmount\x12\x18\n" +
	"\acharset\x18\x06 \x01(\tR\acharset\x12$\n" +
	"\x0efund_bill_list\x18\a \x01(\tR\ffundBillList\x12\x1d\n" +
	"\n" +
	"gmt_create\x18\b \x01(\tR\tgmtCreate\x12\x1f\n" +
	"\vgmt_payment\x18\t \x01(\tR\n" +
	"gmtPayment\x12%\n" +
	"\x0einvoice_amount\x18\n" +
	" \x01(\tR\rinvoiceAmount\x12\x1b\n" +
	"\tnotify_id\x18\v \x01(\tR\bnotifyId\x12\x1f\n" +
	"\vnotify_time\x18\f \x01(\tR\n" +
	"notifyTime\x12\x1f\n" +
	"\vnotify_type\x18\r \x01(\tR\n" +
	"notifyType\x12 \n" +
	"\fout_trade_no\x18\x0e \x01(\tR\n" +
	"outTradeNo\x12!\n" +
	"\fpoint_amount\x18\x0f \x01(\tR\vpointAmount\x12%\n" +
	"\x0ereceipt_amount\x18\x10 \x01(\tR\rreceiptAmount\x12!\n" +
	"\fseller_email\x18\x11 \x01(\tR\vsellerEmail\x12\x1b\n" +
	"\tseller_id\x18\x12 \x01(\tR\bsellerId\x12\x12\n" +
	"\x04sign\x18\x13 \x01(\tR\x04sign\x12\x1b\n" +
	"\tsign_type\x18\x14 \x01(\tR\bsignType\x12\x18\n" +
	"\asubject\x18\x15 \x01(\tR\asubject\x12!\n" +
	"\ftotal_amount\x18\x16 \x01(\tR\vtotalAmount\x12\x19\n" +
	"\btrade_no\x18\x17 \x01(\tR\atradeNo\x12!\n" +
	"\ftrade_status\x18\x18 \x01(\tR\vtradeStatus\x12\x18\n" +
	"\aversion\x18\x19 \x01(\tR\aversion\"\x15\n" +
	"\x13PayAlipayNotifyResp\"\x80\x02\n" +
	"\x12PayPayPalNotifyReq\x12'\n" +
	"\x0ftransmission_id\x18\x01 \x01(\tR\x0etransmissionId\x12+\n" +
	"\x11transmission_time\x18\x02 \x01(\tR\x10transmissionTime\x12\x19\n" +
	"\bcert_url\x18\x03 \x01(\tR\acertUrl\x12\x1b\n" +
	"\tauth_algo\x18\x04 \x01(\tR\bauthAlgo\x12)\n" +
	"\x10transmission_sig\x18\x05 \x01(\tR\x0ftransmissionSig\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x06 \x01(\tR\twebhookId\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\"C\n" +
	"\x13PayPayPalNotifyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcd\x01\n" +
	"\x14PayAppleIAPNotifyReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12!\n" +
	"\freceipt_data\x18\x04 \x01(\tR\vreceiptData\x12,\n" +
	"\x12use_transaction_id\x18\x05 \x01(\bR\x10useTransactionId\x12\x18\n" +
	"\asandbox\x18\x06 \x01(\bR\asandbox\"\xd6\x01\n" +
	"\x15PayGoogleIAPNotifyReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12\x1d\n" +
	"\n" +
	"product_id\x18\x04 \x01(\tR\tproductId\x12%\n" +
	"\x0epurchase_token\x18\x05 \x01(\tR\rpurchaseToken\x12'\n" +
	"\x0fis_subscription\x18\x06 \x01(\bR\x0eisSubscriptionB\x06Z\x04.;pbb\x06proto3"

var (
	file_pay_pay_msg_proto_rawDescOnce sync.Once
	file_pay_pay_msg_proto_rawDescData []byte
)

func file_pay_pay_msg_proto_rawDescGZIP() []byte {
	file_pay_pay_msg_proto_rawDescOnce.Do(func() {
		file_pay_pay_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pay_pay_msg_proto_rawDesc), len(file_pay_pay_msg_proto_rawDesc)))
	})
	return file_pay_pay_msg_proto_rawDescData
}

var file_pay_pay_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_pay_pay_msg_proto_goTypes = []any{
	(*PayGetGoodssReq)(nil),       // 0: PayGetGoodssReq
	(*PayGetGoodssResp)(nil),      // 1: PayGetGoodssResp
	(*PayGetOrderListReq)(nil),    // 2: PayGetOrderListReq
	(*PayGetOrderListResp)(nil),   // 3: PayGetOrderListResp
	(*PayCreatePayOrderReq)(nil),  // 4: PayCreatePayOrderReq
	(*PayCreatePayOrderResp)(nil), // 5: PayCreatePayOrderResp
	(*PayAskOrCancelReq)(nil),     // 6: PayAskOrCancelReq
	(*PayPayOrderAskResp)(nil),    // 7: PayPayOrderAskResp
	(*PayWeChatNotifyReq)(nil),    // 8: PayWeChatNotifyReq
	(*PayWeChatNotifyResp)(nil),   // 9: PayWeChatNotifyResp
	(*Resource)(nil),              // 10: Resource
	(*WxPayTransaction)(nil),      // 11: WxPayTransaction
	(*Amount)(nil),                // 12: Amount
	(*Payer)(nil),                 // 13: Payer
	(*PayAlipayNotifyReq)(nil),    // 14: PayAlipayNotifyReq
	(*PayAlipayNotifyResp)(nil),   // 15: PayAlipayNotifyResp
	(*PayPayPalNotifyReq)(nil),    // 16: PayPayPalNotifyReq
	(*PayPayPalNotifyResp)(nil),   // 17: PayPayPalNotifyResp
	(*PayAppleIAPNotifyReq)(nil),  // 18: PayAppleIAPNotifyReq
	(*PayGoogleIAPNotifyReq)(nil), // 19: PayGoogleIAPNotifyReq
	(*DBGoods)(nil),               // 20: DBGoods
	(*DBPayOrder)(nil),            // 21: DBPayOrder
	(PaymentMethod)(0),            // 22: PaymentMethod
	(*AppPayParams)(nil),          // 23: AppPayParams
	(*DBUser)(nil),                // 24: DBUser
}
var file_pay_pay_msg_proto_depIdxs = []int32{
	20, // 0: PayGetGoodssResp.goodss:type_name -> DBGoods
	21, // 1: PayGetOrderListResp.orderss:type_name -> DBPayOrder
	22, // 2: PayCreatePayOrderReq.payment_method:type_name -> PaymentMethod
	23, // 3: PayCreatePayOrderResp.pay_params:type_name -> AppPayParams
	21, // 4: PayPayOrderAskResp.order:type_name -> DBPayOrder
	24, // 5: PayPayOrderAskResp.user:type_name -> DBUser
	10, // 6: PayWeChatNotifyReq.resource:type_name -> Resource
	12, // 7: WxPayTransaction.amount:type_name -> Amount
	13, // 8: WxPayTransaction.payer:type_name -> Payer
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pay_pay_msg_proto_init() }
func file_pay_pay_msg_proto_init() {
	if File_pay_pay_msg_proto != nil {
		return
	}
	file_db_proto_init()
	file_pay_pay_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pay_pay_msg_proto_rawDesc), len(file_pay_pay_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pay_pay_msg_proto_goTypes,
		DependencyIndexes: file_pay_pay_msg_proto_depIdxs,
		MessageInfos:      file_pay_pay_msg_proto_msgTypes,
	}.Build()
	File_pay_pay_msg_proto = out.File
	file_pay_pay_msg_proto_goTypes = nil
	file_pay_pay_msg_proto_depIdxs = nil
}
