// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: pay/pay_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 支付订单状态
type PayOrderStatus int32

const (
	PayOrderStatus_PAY_ORDER_PENDING   PayOrderStatus = 0 //待支付
	PayOrderStatus_PAY_ORDER_PAID      PayOrderStatus = 1 //已支付
	PayOrderStatus_PAY_ORDER_CANCELLED PayOrderStatus = 2 //已取消
	PayOrderStatus_PAY_ORDER_EXPIRED   PayOrderStatus = 3 //已过期
	PayOrderStatus_PAY_ORDER_REFUNDED  PayOrderStatus = 4 //已退款
	PayOrderStatus_PAY_ORDER_FAILED    PayOrderStatus = 5 //支付失败
)

// Enum value maps for PayOrderStatus.
var (
	PayOrderStatus_name = map[int32]string{
		0: "PAY_ORDER_PENDING",
		1: "PAY_ORDER_PAID",
		2: "PAY_ORDER_CANCELLED",
		3: "PAY_ORDER_EXPIRED",
		4: "PAY_ORDER_REFUNDED",
		5: "PAY_ORDER_FAILED",
	}
	PayOrderStatus_value = map[string]int32{
		"PAY_ORDER_PENDING":   0,
		"PAY_ORDER_PAID":      1,
		"PAY_ORDER_CANCELLED": 2,
		"PAY_ORDER_EXPIRED":   3,
		"PAY_ORDER_REFUNDED":  4,
		"PAY_ORDER_FAILED":    5,
	}
)

func (x PayOrderStatus) Enum() *PayOrderStatus {
	p := new(PayOrderStatus)
	*p = x
	return p
}

func (x PayOrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayOrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_pay_db_proto_enumTypes[0].Descriptor()
}

func (PayOrderStatus) Type() protoreflect.EnumType {
	return &file_pay_pay_db_proto_enumTypes[0]
}

func (x PayOrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayOrderStatus.Descriptor instead.
func (PayOrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_pay_pay_db_proto_rawDescGZIP(), []int{0}
}

// 支付方式
type PaymentMethod int32

const (
	PaymentMethod_UnknownPaymentMethod PaymentMethod = 0
	PaymentMethod_WxJSAPI              PaymentMethod = 1 // 微信内网页支付
	PaymentMethod_WxNative             PaymentMethod = 2 // 微信扫码支付
	PaymentMethod_Alipay               PaymentMethod = 3 // 支付宝
	PaymentMethod_WxAPP                PaymentMethod = 4 // 微信APP支付
	PaymentMethod_PayPal               PaymentMethod = 5 // PayPal 支付
	PaymentMethod_AppleIAP             PaymentMethod = 6 // 苹果内购
	PaymentMethod_GoogleIAP            PaymentMethod = 7 // 谷歌内购
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "UnknownPaymentMethod",
		1: "WxJSAPI",
		2: "WxNative",
		3: "Alipay",
		4: "WxAPP",
		5: "PayPal",
		6: "AppleIAP",
		7: "GoogleIAP",
	}
	PaymentMethod_value = map[string]int32{
		"UnknownPaymentMethod": 0,
		"WxJSAPI":              1,
		"WxNative":             2,
		"Alipay":               3,
		"WxAPP":                4,
		"PayPal":               5,
		"AppleIAP":             6,
		"GoogleIAP":            7,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_pay_db_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_pay_pay_db_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_pay_pay_db_proto_rawDescGZIP(), []int{1}
}

// 支付订单数据
type DBPayOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id" gorm:"order_id:50;primaryKey"`                                       //@go_tags(`gorm:"order_id:50;primaryKey" json:"order_id"`) 订单ID
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid" gorm:"uid:50;index"`                                                              //@go_tags(`gorm:"uid:50;index" json:"uid"`) 用户ID
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id" gorm:"product_id:50;index"`                                 //@go_tags(`gorm:"product_id:50;index" json:"product_id"`) 商品ID
	ProductName   string                 `protobuf:"bytes,4,opt,name=product_name,json=productName,proto3" json:"product_name" gorm:"product_name:100"`                           //@go_tags(`gorm:"product_name:100" json:"product_name"`) 商品名称
	ProductDesc   string                 `protobuf:"bytes,5,opt,name=product_desc,json=productDesc,proto3" json:"product_desc" gorm:"product_desc:500"`                           //@go_tags(`gorm:"product_desc:500" json:"product_desc"`) 商品描述
	Amount        int64                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount" gorm:"amount"`                                                       //@go_tags(`gorm:"amount" json:"amount"`) 订单金额(分)
	PaymentMethod PaymentMethod          `protobuf:"varint,7,opt,name=payment_method,json=paymentMethod,proto3,enum=PaymentMethod" json:"payment_method" gorm:"payment_method"` //@go_tags(`gorm:"payment_method" json:"payment_method"`) 支付方式
	Status        PayOrderStatus         `protobuf:"varint,8,opt,name=status,proto3,enum=PayOrderStatus" json:"status" gorm:"status;index"`                                   //@go_tags(`gorm:"status;index" json:"status"`) 订单状态
	TransactionId string                 `protobuf:"bytes,9,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id" gorm:"transaction_id:100;index"`                     //@go_tags(`gorm:"transaction_id:100;index" json:"transaction_id"`) 第三方交易号
	PrepayId      string                 `protobuf:"bytes,10,opt,name=prepay_id,json=prepayId,proto3" json:"prepay_id" gorm:"prepay_id:100"`                                   //@go_tags(`gorm:"prepay_id:100" json:"prepay_id"`) 预支付ID
	CodeUrl       string                 `protobuf:"bytes,11,opt,name=code_url,json=codeUrl,proto3" json:"code_url" gorm:"code_url:500"`                                      //@go_tags(`gorm:"code_url:500" json:"code_url"`) 支付二维码URL
	CreateTime    int64                  `protobuf:"varint,12,opt,name=create_time,json=createTime,proto3" json:"create_time" gorm:"create_time;index"`                            //@go_tags(`gorm:"create_time;index" json:"create_time"`) 创建时间
	PayTime       int64                  `protobuf:"varint,13,opt,name=pay_time,json=payTime,proto3" json:"pay_time" gorm:"pay_time"`                                     //@go_tags(`gorm:"pay_time" json:"pay_time"`) 支付时间
	ExpireTime    int64                  `protobuf:"varint,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time" gorm:"expire_time"`                            //@go_tags(`gorm:"expire_time" json:"expire_time"`) 过期时间
	ClientIp      string                 `protobuf:"bytes,15,opt,name=client_ip,json=clientIp,proto3" json:"client_ip" gorm:"client_ip:50"`                                   //@go_tags(`gorm:"client_ip:50" json:"client_ip"`) 客户端IP
	NotifyUrl     string                 `protobuf:"bytes,16,opt,name=notify_url,json=notifyUrl,proto3" json:"notify_url" gorm:"notify_url:200"`                                //@go_tags(`gorm:"notify_url:200" json:"notify_url"`) 回调地址
	ExtraData     string                 `protobuf:"bytes,17,opt,name=extra_data,json=extraData,proto3" json:"extra_data" gorm:"extra_data:1000"`                                //@go_tags(`gorm:"extra_data:1000" json:"extra_data"`) 扩展数据
	Remark        string                 `protobuf:"bytes,18,opt,name=remark,proto3" json:"remark" gorm:"remark:500"`                                                       //@go_tags(`gorm:"remark:500" json:"remark"`) 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBPayOrder) Reset() {
	*x = DBPayOrder{}
	mi := &file_pay_pay_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBPayOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBPayOrder) ProtoMessage() {}

func (x *DBPayOrder) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBPayOrder.ProtoReflect.Descriptor instead.
func (*DBPayOrder) Descriptor() ([]byte, []int) {
	return file_pay_pay_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBPayOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DBPayOrder) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBPayOrder) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DBPayOrder) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *DBPayOrder) GetProductDesc() string {
	if x != nil {
		return x.ProductDesc
	}
	return ""
}

func (x *DBPayOrder) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *DBPayOrder) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_UnknownPaymentMethod
}

func (x *DBPayOrder) GetStatus() PayOrderStatus {
	if x != nil {
		return x.Status
	}
	return PayOrderStatus_PAY_ORDER_PENDING
}

func (x *DBPayOrder) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *DBPayOrder) GetPrepayId() string {
	if x != nil {
		return x.PrepayId
	}
	return ""
}

func (x *DBPayOrder) GetCodeUrl() string {
	if x != nil {
		return x.CodeUrl
	}
	return ""
}

func (x *DBPayOrder) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *DBPayOrder) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *DBPayOrder) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *DBPayOrder) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *DBPayOrder) GetNotifyUrl() string {
	if x != nil {
		return x.NotifyUrl
	}
	return ""
}

func (x *DBPayOrder) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *DBPayOrder) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 微信APP支付参数
type AppPayParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         string                 `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid"`         //@go_tags(`json:"appid"`) 应用ID
	Partnerid     string                 `protobuf:"bytes,2,opt,name=partnerid,proto3" json:"partnerid"` //@go_tags(`json:"partnerid"`) 商户号
	Prepayid      string                 `protobuf:"bytes,3,opt,name=prepayid,proto3" json:"prepayid"`   //@go_tags(`json:"prepayid"`) 预支付ID
	Package       string                 `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`     //@go_tags(`json:"package
	Noncestr      string                 `protobuf:"bytes,5,opt,name=noncestr,proto3" json:"noncestr"`   //@go_tags(`json:"noncestr"`) 随机字符串
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp"` //@go_tags(`json:"timestamp"`) 时间戳（秒）
	Sign          string                 `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign"`           //@go_tags(`json:"sign"`) 支付签名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppPayParams) Reset() {
	*x = AppPayParams{}
	mi := &file_pay_pay_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppPayParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppPayParams) ProtoMessage() {}

func (x *AppPayParams) ProtoReflect() protoreflect.Message {
	mi := &file_pay_pay_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppPayParams.ProtoReflect.Descriptor instead.
func (*AppPayParams) Descriptor() ([]byte, []int) {
	return file_pay_pay_db_proto_rawDescGZIP(), []int{1}
}

func (x *AppPayParams) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *AppPayParams) GetPartnerid() string {
	if x != nil {
		return x.Partnerid
	}
	return ""
}

func (x *AppPayParams) GetPrepayid() string {
	if x != nil {
		return x.Prepayid
	}
	return ""
}

func (x *AppPayParams) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *AppPayParams) GetNoncestr() string {
	if x != nil {
		return x.Noncestr
	}
	return ""
}

func (x *AppPayParams) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AppPayParams) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_pay_pay_db_proto protoreflect.FileDescriptor

const file_pay_pay_db_proto_rawDesc = "" +
	"\n" +
	"\x10pay/pay_db.proto\"\xc5\x04\n" +
	"\n" +
	"DBPayOrder\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12!\n" +
	"\fproduct_name\x18\x04 \x01(\tR\vproductName\x12!\n" +
	"\fproduct_desc\x18\x05 \x01(\tR\vproductDesc\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x03R\x06amount\x125\n" +
	"\x0epayment_method\x18\a \x01(\x0e2\x0e.PaymentMethodR\rpaymentMethod\x12'\n" +
	"\x06status\x18\b \x01(\x0e2\x0f.PayOrderStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\t \x01(\tR\rtransactionId\x12\x1b\n" +
	"\tprepay_id\x18\n" +
	" \x01(\tR\bprepayId\x12\x19\n" +
	"\bcode_url\x18\v \x01(\tR\acodeUrl\x12\x1f\n" +
	"\vcreate_time\x18\f \x01(\x03R\n" +
	"createTime\x12\x19\n" +
	"\bpay_time\x18\r \x01(\x03R\apayTime\x12\x1f\n" +
	"\vexpire_time\x18\x0e \x01(\x03R\n" +
	"expireTime\x12\x1b\n" +
	"\tclient_ip\x18\x0f \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"notify_url\x18\x10 \x01(\tR\tnotifyUrl\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x11 \x01(\tR\textraData\x12\x16\n" +
	"\x06remark\x18\x12 \x01(\tR\x06remark\"\xc6\x01\n" +
	"\fAppPayParams\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\tR\x05appid\x12\x1c\n" +
	"\tpartnerid\x18\x02 \x01(\tR\tpartnerid\x12\x1a\n" +
	"\bprepayid\x18\x03 \x01(\tR\bprepayid\x12\x18\n" +
	"\apackage\x18\x04 \x01(\tR\apackage\x12\x1a\n" +
	"\bnoncestr\x18\x05 \x01(\tR\bnoncestr\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04sign\x18\a \x01(\tR\x04sign*\x99\x01\n" +
	"\x0ePayOrderStatus\x12\x15\n" +
	"\x11PAY_ORDER_PENDING\x10\x00\x12\x12\n" +
	"\x0ePAY_ORDER_PAID\x10\x01\x12\x17\n" +
	"\x13PAY_ORDER_CANCELLED\x10\x02\x12\x15\n" +
	"\x11PAY_ORDER_EXPIRED\x10\x03\x12\x16\n" +
	"\x12PAY_ORDER_REFUNDED\x10\x04\x12\x14\n" +
	"\x10PAY_ORDER_FAILED\x10\x05*\x84\x01\n" +
	"\rPaymentMethod\x12\x18\n" +
	"\x14UnknownPaymentMethod\x10\x00\x12\v\n" +
	"\aWxJSAPI\x10\x01\x12\f\n" +
	"\bWxNative\x10\x02\x12\n" +
	"\n" +
	"\x06Alipay\x10\x03\x12\t\n" +
	"\x05WxAPP\x10\x04\x12\n" +
	"\n" +
	"\x06PayPal\x10\x05\x12\f\n" +
	"\bAppleIAP\x10\x06\x12\r\n" +
	"\tGoogleIAP\x10\aB\x06Z\x04.;pbb\x06proto3"

var (
	file_pay_pay_db_proto_rawDescOnce sync.Once
	file_pay_pay_db_proto_rawDescData []byte
)

func file_pay_pay_db_proto_rawDescGZIP() []byte {
	file_pay_pay_db_proto_rawDescOnce.Do(func() {
		file_pay_pay_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pay_pay_db_proto_rawDesc), len(file_pay_pay_db_proto_rawDesc)))
	})
	return file_pay_pay_db_proto_rawDescData
}

var file_pay_pay_db_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pay_pay_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pay_pay_db_proto_goTypes = []any{
	(PayOrderStatus)(0),  // 0: PayOrderStatus
	(PaymentMethod)(0),   // 1: PaymentMethod
	(*DBPayOrder)(nil),   // 2: DBPayOrder
	(*AppPayParams)(nil), // 3: AppPayParams
}
var file_pay_pay_db_proto_depIdxs = []int32{
	1, // 0: DBPayOrder.payment_method:type_name -> PaymentMethod
	0, // 1: DBPayOrder.status:type_name -> PayOrderStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pay_pay_db_proto_init() }
func file_pay_pay_db_proto_init() {
	if File_pay_pay_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pay_pay_db_proto_rawDesc), len(file_pay_pay_db_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pay_pay_db_proto_goTypes,
		DependencyIndexes: file_pay_pay_db_proto_depIdxs,
		EnumInfos:         file_pay_pay_db_proto_enumTypes,
		MessageInfos:      file_pay_pay_db_proto_msgTypes,
	}.Build()
	File_pay_pay_db_proto = out.File
	file_pay_pay_db_proto_goTypes = nil
	file_pay_pay_db_proto_depIdxs = nil
}
