// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: user/user_db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户设置相关
type DBUuserAppSetting struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户id
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 是否开启语音 flock
	EnableVoiceFlocking bool `protobuf:"varint,2,opt,name=enableVoiceFlocking,proto3" json:"enableVoiceFlocking,omitempty"`
	// 扬声器配置id
	SpeakerProfileId string `protobuf:"bytes,3,opt,name=speakerProfileId,proto3" json:"speakerProfileId,omitempty"`
	// 是否是坐席
	IsAgent bool `protobuf:"varint,4,opt,name=isAgent,proto3" json:"isAgent,omitempty"`
	// 是否是同时通话
	IsSimultaneous bool `protobuf:"varint,5,opt,name=isSimultaneous,proto3" json:"isSimultaneous,omitempty"`
	// 是否是语音通话
	IsCall bool `protobuf:"varint,6,opt,name=isCall,proto3" json:"isCall,omitempty"`
	// 是否是面对面通话
	IsFaceToFace  bool `protobuf:"varint,7,opt,name=isFaceToFace,proto3" json:"isFaceToFace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBUuserAppSetting) Reset() {
	*x = DBUuserAppSetting{}
	mi := &file_user_user_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBUuserAppSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBUuserAppSetting) ProtoMessage() {}

func (x *DBUuserAppSetting) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBUuserAppSetting.ProtoReflect.Descriptor instead.
func (*DBUuserAppSetting) Descriptor() ([]byte, []int) {
	return file_user_user_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBUuserAppSetting) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *DBUuserAppSetting) GetEnableVoiceFlocking() bool {
	if x != nil {
		return x.EnableVoiceFlocking
	}
	return false
}

func (x *DBUuserAppSetting) GetSpeakerProfileId() string {
	if x != nil {
		return x.SpeakerProfileId
	}
	return ""
}

func (x *DBUuserAppSetting) GetIsAgent() bool {
	if x != nil {
		return x.IsAgent
	}
	return false
}

func (x *DBUuserAppSetting) GetIsSimultaneous() bool {
	if x != nil {
		return x.IsSimultaneous
	}
	return false
}

func (x *DBUuserAppSetting) GetIsCall() bool {
	if x != nil {
		return x.IsCall
	}
	return false
}

func (x *DBUuserAppSetting) GetIsFaceToFace() bool {
	if x != nil {
		return x.IsFaceToFace
	}
	return false
}

var File_user_user_db_proto protoreflect.FileDescriptor

const file_user_user_db_proto_rawDesc = "" +
	"\n" +
	"\x12user/user_db.proto\"\x81\x02\n" +
	"\x11DBUuserAppSetting\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x120\n" +
	"\x13enableVoiceFlocking\x18\x02 \x01(\bR\x13enableVoiceFlocking\x12*\n" +
	"\x10speakerProfileId\x18\x03 \x01(\tR\x10speakerProfileId\x12\x18\n" +
	"\aisAgent\x18\x04 \x01(\bR\aisAgent\x12&\n" +
	"\x0eisSimultaneous\x18\x05 \x01(\bR\x0eisSimultaneous\x12\x16\n" +
	"\x06isCall\x18\x06 \x01(\bR\x06isCall\x12\"\n" +
	"\fisFaceToFace\x18\a \x01(\bR\fisFaceToFaceB\x06Z\x04.;pbb\x06proto3"

var (
	file_user_user_db_proto_rawDescOnce sync.Once
	file_user_user_db_proto_rawDescData []byte
)

func file_user_user_db_proto_rawDescGZIP() []byte {
	file_user_user_db_proto_rawDescOnce.Do(func() {
		file_user_user_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_db_proto_rawDesc), len(file_user_user_db_proto_rawDesc)))
	})
	return file_user_user_db_proto_rawDescData
}

var file_user_user_db_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_user_db_proto_goTypes = []any{
	(*DBUuserAppSetting)(nil), // 0: DBUuserAppSetting
}
var file_user_user_db_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_user_db_proto_init() }
func file_user_user_db_proto_init() {
	if File_user_user_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_db_proto_rawDesc), len(file_user_user_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_db_proto_goTypes,
		DependencyIndexes: file_user_user_db_proto_depIdxs,
		MessageInfos:      file_user_user_db_proto_msgTypes,
	}.Build()
	File_user_user_db_proto = out.File
	file_user_user_db_proto_goTypes = nil
	file_user_user_db_proto_depIdxs = nil
}
