// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: user/user_msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 登录请求
type UserSginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stype         SginTyoe               `protobuf:"varint,1,opt,name=stype,proto3,enum=SginTyoe" json:"stype" example:"0"`         //@go_tags(`json:"stype" example:"0" description:"登录方式“`) 登录方式
	Mail          string                 `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail" example:"" description:"邮箱地址"`                          //@go_tags(`json:"mail" example:"" description:"邮箱地址"`) 邮箱地址
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone" example:""`                        //@go_tags(`json:"phone" example:"" description:"手机号码“`) 手机号
	Ttoken        string                 `protobuf:"bytes,4,opt,name=ttoken,proto3" json:"ttoken" example:"" description:"第三方token"`                      //@go_tags(`json:"ttoken" example:"" description:"第三方token"`) 第三方token
	Vcode         string                 `protobuf:"bytes,5,opt,name=vcode,proto3" json:"vcode" example:"" description:"验证码"`                        //@go_tags(`json:"vcode" example:"" description:"验证码"`) 验证码
	Phonemodel    string                 `protobuf:"bytes,10,opt,name=phonemodel,proto3" json:"phonemodel" example:"" description:"设备型号"`             //@go_tags(`json:"phonemodel" example:"" description:"设备型号"`) 手机型号
	Phonemac      string                 `protobuf:"bytes,11,opt,name=phonemac,proto3" json:"phonemac" example:"" description:"手机硬件id"`                 //@go_tags(`json:"phonemac" example:"" description:"手机硬件id"`) 手机硬件id
	Name          string                 `protobuf:"bytes,20,opt,name=name,proto3" json:"name" gorm:"name:50" example:"" description:"用户名"`                         //@go_tags(`gorm:"name:50" json:"name" example:"" description:"用户名"`) 用户名
	Avatar        string                 `protobuf:"bytes,21,opt,name=avatar,proto3" json:"avatar" gorm:"avatar" example:"" description:"头像连接"`                     //@go_tags(`gorm:"avatar" json:"avatar" example:"" description:"头像连接"`) 头像连接
	Language      string                 `protobuf:"bytes,22,opt,name=language,proto3" json:"language" example:"en" description:"语言"`                 //@go_tags(`json:"language" example:"en" description:"语言"`)
	Channel       UserChannel            `protobuf:"varint,23,opt,name=channel,proto3,enum=UserChannel" json:"channel,omitempty"` //渠道
	Version       string                 `protobuf:"bytes,24,opt,name=version,proto3" json:"version,omitempty"`                   //版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSginReq) Reset() {
	*x = UserSginReq{}
	mi := &file_user_user_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginReq) ProtoMessage() {}

func (x *UserSginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginReq.ProtoReflect.Descriptor instead.
func (*UserSginReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{0}
}

func (x *UserSginReq) GetStype() SginTyoe {
	if x != nil {
		return x.Stype
	}
	return SginTyoe_Mail
}

func (x *UserSginReq) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *UserSginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserSginReq) GetTtoken() string {
	if x != nil {
		return x.Ttoken
	}
	return ""
}

func (x *UserSginReq) GetVcode() string {
	if x != nil {
		return x.Vcode
	}
	return ""
}

func (x *UserSginReq) GetPhonemodel() string {
	if x != nil {
		return x.Phonemodel
	}
	return ""
}

func (x *UserSginReq) GetPhonemac() string {
	if x != nil {
		return x.Phonemac
	}
	return ""
}

func (x *UserSginReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSginReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSginReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSginReq) GetChannel() UserChannel {
	if x != nil {
		return x.Channel
	}
	return UserChannel_UNKNOWN
}

func (x *UserSginReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type UserSginResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 认证token
	// 缓存在本地 可以通过token 登录
	// example: 认证token
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token" example:"认证token" description:"认证token"` //@go_tags(`json:"token" example:"认证token" description:"认证token"`)
	// 用户信息
	// example:
	User *DBUser `protobuf:"bytes,2,opt,name=user,proto3" json:"user" description:"用户信息"` //@go_tags(`json:"user" description:"用户信息"`)
	// 用户设备列表
	// example:
	Devices       []*DBUserDivice `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices" description:"用户设备列表"` //@go_tags(`json:"devices" description:"用户设备列表"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSginResp) Reset() {
	*x = UserSginResp{}
	mi := &file_user_user_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSginResp) ProtoMessage() {}

func (x *UserSginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSginResp.ProtoReflect.Descriptor instead.
func (*UserSginResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{1}
}

func (x *UserSginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserSginResp) GetUser() *DBUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserSginResp) GetDevices() []*DBUserDivice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 验证码请求
type UserVerificationReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码类型“
	// 选填，长度 11
	// example:  0 邮箱验证 1 手机验证
	Vtype int32 `protobuf:"varint,1,opt,name=vtype,proto3" json:"vtype" example:"0"` //@go_tags(`json:"vtype" example:"0" description:"验证码类型 0 手机验证 1 邮箱验证“`)
	// 目标地址
	// 选填，长度 11
	// example: 手机号/邮箱
	Addr          string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr" example:"" description:"手机号/邮箱"` //@go_tags(`json:"addr" example:"" description:"手机号/邮箱"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVerificationReq) Reset() {
	*x = UserVerificationReq{}
	mi := &file_user_user_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVerificationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVerificationReq) ProtoMessage() {}

func (x *UserVerificationReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVerificationReq.ProtoReflect.Descriptor instead.
func (*UserVerificationReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{2}
}

func (x *UserVerificationReq) GetVtype() int32 {
	if x != nil {
		return x.Vtype
	}
	return 0
}

func (x *UserVerificationReq) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

// 验证码请求
type UserVerificationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserVerificationResp) Reset() {
	*x = UserVerificationResp{}
	mi := &file_user_user_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserVerificationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserVerificationResp) ProtoMessage() {}

func (x *UserVerificationResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserVerificationResp.ProtoReflect.Descriptor instead.
func (*UserVerificationResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{3}
}

// 通过toke 登录 同意设备下可以持续登录，当更换设备后 登录会返回错误码，token已过期 需要转 sgin 登录请求
type UserGetInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                   //版本号
	Channel       UserChannel            `protobuf:"varint,2,opt,name=channel,proto3,enum=UserChannel" json:"channel,omitempty"` //渠道
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetInfoReq) Reset() {
	*x = UserGetInfoReq{}
	mi := &file_user_user_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoReq) ProtoMessage() {}

func (x *UserGetInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoReq.ProtoReflect.Descriptor instead.
func (*UserGetInfoReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{4}
}

func (x *UserGetInfoReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UserGetInfoReq) GetChannel() UserChannel {
	if x != nil {
		return x.Channel
	}
	return UserChannel_UNKNOWN
}

type UserGetInfoResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户信息
	// example:
	User *DBUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user" description:"用户信息"` //@go_tags(`json:"user" description:"用户信息"`)
	// 用户设备列表
	// example:
	Devices       []*DBUserDivice `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices" description:"用户设备列表"` //@go_tags(`json:"devices" description:"用户设备列表"`)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetInfoResp) Reset() {
	*x = UserGetInfoResp{}
	mi := &file_user_user_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetInfoResp) ProtoMessage() {}

func (x *UserGetInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetInfoResp.ProtoReflect.Descriptor instead.
func (*UserGetInfoResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{5}
}

func (x *UserGetInfoResp) GetUser() *DBUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserGetInfoResp) GetDevices() []*DBUserDivice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 设置请求 此接口由于需要上传头像 只能支持字符串类型的参数
type UserSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name" example:"" description:"用户名"`         //@go_tags(`json:"name" example:"" description:"用户名"`) 用户名
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language" example:"en" description:"语言"` //@go_tags(`json:"language" example:"en" description:"语言"`)
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image" example:"" description:"头像"`       //@go_tags(`json:"image" example:"" description:"头像"`) 头像连接
	Gender        string                 `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender" example:"1" description:"性别 1-男 2-女"`     //@go_tags(`json:"gender" example:"1" description:"性别 1-男 2-女"`) 性别 1-男 2-女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettingReq) Reset() {
	*x = UserSettingReq{}
	mi := &file_user_user_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingReq) ProtoMessage() {}

func (x *UserSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingReq.ProtoReflect.Descriptor instead.
func (*UserSettingReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{6}
}

func (x *UserSettingReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSettingReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSettingReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *UserSettingReq) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

type UserSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name" example:"用户名" description:"用户名"`         //@go_tags(`json:"name" example:"用户名" description:"用户名"`)
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language" example:"en" description:"语言"` //@go_tags(`json:"language" example:"en" description:"语言"`)
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar" example:"" description:"地址"`     //@go_tags(`json:"avatar" example:"" description:"地址"`) 头像连接
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender" example:"1" description:"性别 1-男 2-女"`    //@go_tags(`json:"gender" example:"1" description:"性别 1-男 2-女"`) 性别 1-男 2-女
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSettingResp) Reset() {
	*x = UserSettingResp{}
	mi := &file_user_user_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettingResp) ProtoMessage() {}

func (x *UserSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettingResp.ProtoReflect.Descriptor instead.
func (*UserSettingResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{7}
}

func (x *UserSettingResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSettingResp) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSettingResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserSettingResp) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

// 绑定耳机请求
type UserBindDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`              //产品id
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`             //授权码
	Devicename    string                 `protobuf:"bytes,3,opt,name=devicename,proto3" json:"devicename,omitempty"` //耳机名称
	Devicemac     string                 `protobuf:"bytes,4,opt,name=devicemac,proto3" json:"devicemac,omitempty"`   //耳机名称地址
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`       //版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBindDeviceReq) Reset() {
	*x = UserBindDeviceReq{}
	mi := &file_user_user_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBindDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBindDeviceReq) ProtoMessage() {}

func (x *UserBindDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBindDeviceReq.ProtoReflect.Descriptor instead.
func (*UserBindDeviceReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{8}
}

func (x *UserBindDeviceReq) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *UserBindDeviceReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserBindDeviceReq) GetDevicename() string {
	if x != nil {
		return x.Devicename
	}
	return ""
}

func (x *UserBindDeviceReq) GetDevicemac() string {
	if x != nil {
		return x.Devicemac
	}
	return ""
}

func (x *UserBindDeviceReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// 绑定耳机请求
type UserBindDeviceResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Device              *DBUserDivice          `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                            //绑定的耳机信息
	Isgiveaway          bool                   `protobuf:"varint,2,opt,name=isgiveaway,proto3" json:"isgiveaway" gorm:"isgiveaway"`                   //@go_tags(`gorm:"isgiveaway" json:"isgiveaway"`) 是否是第一次绑定
	Viplv               int32                  `protobuf:"varint,3,opt,name=viplv,proto3" json:"viplv" gorm:"viplv:50"`                             //@go_tags(`gorm:"viplv:50" json:"viplv"`) viplv
	Vipexptime          int64                  `protobuf:"varint,4,opt,name=vipexptime,proto3" json:"vipexptime" gorm:"vipexptime"`                   //@go_tags(`gorm:"vipexptime" json:"vipexptime"`) 会员过期时间
	Aichatintegral      int64                  `protobuf:"varint,5,opt,name=aichatintegral,proto3" json:"aichatintegral" gorm:"aichatintegral"`           //@go_tags(`gorm:"aichatintegral" json:"aichatintegral"`) ai聊天积分
	Aichattotalintegral int64                  `protobuf:"varint,6,opt,name=aichattotalintegral,proto3" json:"aichattotalintegral" gorm:"aichattotalintegral"` //@go_tags(`gorm:"aichattotalintegral" json:"aichattotalintegral"`) ai聊天总积分
	Tradeintegral       int64                  `protobuf:"varint,7,opt,name=tradeintegral,proto3" json:"tradeintegral" gorm:"tradeintegral"`             //@go_tags(`gorm:"tradeintegral" json:"tradeintegral"`) 翻译积分
	Tradetotalintegral  int64                  `protobuf:"varint,8,opt,name=tradetotalintegral,proto3" json:"tradetotalintegral" gorm:"tradetotalintegral"`   //@go_tags(`gorm:"tradetotalintegral" json:"tradetotalintegral"`) 翻译总积分
	Meetintegral        int64                  `protobuf:"varint,9,opt,name=meetintegral,proto3" json:"meetintegral" gorm:"meetintegral"`               //@go_tags(`gorm:"meetintegral" json:"meetintegral"`) 会议积分
	Meettotalintegral   int64                  `protobuf:"varint,10,opt,name=meettotalintegral,proto3" json:"meettotalintegral" gorm:"meettotalintegral"`    //@go_tags(`gorm:"meettotalintegral" json:"meettotalintegral"`) 会议总积分
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserBindDeviceResp) Reset() {
	*x = UserBindDeviceResp{}
	mi := &file_user_user_msg_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBindDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBindDeviceResp) ProtoMessage() {}

func (x *UserBindDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBindDeviceResp.ProtoReflect.Descriptor instead.
func (*UserBindDeviceResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{9}
}

func (x *UserBindDeviceResp) GetDevice() *DBUserDivice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *UserBindDeviceResp) GetIsgiveaway() bool {
	if x != nil {
		return x.Isgiveaway
	}
	return false
}

func (x *UserBindDeviceResp) GetViplv() int32 {
	if x != nil {
		return x.Viplv
	}
	return 0
}

func (x *UserBindDeviceResp) GetVipexptime() int64 {
	if x != nil {
		return x.Vipexptime
	}
	return 0
}

func (x *UserBindDeviceResp) GetAichatintegral() int64 {
	if x != nil {
		return x.Aichatintegral
	}
	return 0
}

func (x *UserBindDeviceResp) GetAichattotalintegral() int64 {
	if x != nil {
		return x.Aichattotalintegral
	}
	return 0
}

func (x *UserBindDeviceResp) GetTradeintegral() int64 {
	if x != nil {
		return x.Tradeintegral
	}
	return 0
}

func (x *UserBindDeviceResp) GetTradetotalintegral() int64 {
	if x != nil {
		return x.Tradetotalintegral
	}
	return 0
}

func (x *UserBindDeviceResp) GetMeetintegral() int64 {
	if x != nil {
		return x.Meetintegral
	}
	return 0
}

func (x *UserBindDeviceResp) GetMeettotalintegral() int64 {
	if x != nil {
		return x.Meettotalintegral
	}
	return 0
}

// 解绑定耳机请求
type UserUnBindDeviceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //设备id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnBindDeviceReq) Reset() {
	*x = UserUnBindDeviceReq{}
	mi := &file_user_user_msg_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnBindDeviceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnBindDeviceReq) ProtoMessage() {}

func (x *UserUnBindDeviceReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnBindDeviceReq.ProtoReflect.Descriptor instead.
func (*UserUnBindDeviceReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{10}
}

func (x *UserUnBindDeviceReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 解绑定耳机请求
type UserUnBindDeviceResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnBindDeviceResp) Reset() {
	*x = UserUnBindDeviceResp{}
	mi := &file_user_user_msg_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnBindDeviceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnBindDeviceResp) ProtoMessage() {}

func (x *UserUnBindDeviceResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnBindDeviceResp.ProtoReflect.Descriptor instead.
func (*UserUnBindDeviceResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{11}
}

// 扫激活码（厂家公码）领取奖励请求
// 新设计下激活码 = 厂家公码：每个用户一生仅可领取 1 次（任意厂家任意码均算）
type UserBindAuthCodeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`             //激活码/公码（必填）
	Devicename    string                 `protobuf:"bytes,2,opt,name=devicename,proto3" json:"devicename,omitempty"` //[已废弃] 旧的逐设备激活码遗留字段，公码场景下忽略
	Devicemac     string                 `protobuf:"bytes,3,opt,name=devicemac,proto3" json:"devicemac,omitempty"`   //[已废弃] 旧的逐设备激活码遗留字段，公码场景下忽略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserBindAuthCodeReq) Reset() {
	*x = UserBindAuthCodeReq{}
	mi := &file_user_user_msg_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBindAuthCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBindAuthCodeReq) ProtoMessage() {}

func (x *UserBindAuthCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBindAuthCodeReq.ProtoReflect.Descriptor instead.
func (*UserBindAuthCodeReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{12}
}

func (x *UserBindAuthCodeReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserBindAuthCodeReq) GetDevicename() string {
	if x != nil {
		return x.Devicename
	}
	return ""
}

func (x *UserBindAuthCodeReq) GetDevicemac() string {
	if x != nil {
		return x.Devicemac
	}
	return ""
}

// 扫激活码（厂家公码）领取奖励响应
type UserBindAuthCodeResp struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Device             *DBUserDivice          `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                          //[已废弃] 公码场景下为空
	Isgiveaway         bool                   `protobuf:"varint,2,opt,name=isgiveaway,proto3" json:"isgiveaway,omitempty"`                 //本次是否发放奖励
	Viplv              int32                  `protobuf:"varint,3,opt,name=viplv,proto3" json:"viplv,omitempty"`                           //VIP等级
	Vipexptime         int64                  `protobuf:"varint,4,opt,name=vipexptime,proto3" json:"vipexptime,omitempty"`                 //VIP过期时间
	Tradeintegral      int64                  `protobuf:"varint,5,opt,name=tradeintegral,proto3" json:"tradeintegral,omitempty"`           //翻译积分
	Tradetotalintegral int64                  `protobuf:"varint,6,opt,name=tradetotalintegral,proto3" json:"tradetotalintegral,omitempty"` //翻译总积分
	Meetintegral       int64                  `protobuf:"varint,7,opt,name=meetintegral,proto3" json:"meetintegral,omitempty"`             //会议积分
	Meettotalintegral  int64                  `protobuf:"varint,8,opt,name=meettotalintegral,proto3" json:"meettotalintegral,omitempty"`   //会议总积分
	Addvipday          int64                  `protobuf:"varint,9,opt,name=addvipday,proto3" json:"addvipday,omitempty"`                   //本次发放VIP天数
	Addtradesecond     int64                  `protobuf:"varint,10,opt,name=addtradesecond,proto3" json:"addtradesecond,omitempty"`        //本次发放翻译秒数
	Addmeetsecond      int64                  `protobuf:"varint,11,opt,name=addmeetsecond,proto3" json:"addmeetsecond,omitempty"`          //本次发放会议秒数
	Factoryid          uint32                 `protobuf:"varint,12,opt,name=factoryid,proto3" json:"factoryid,omitempty"`                  //奖励来源厂家id
	Productid          uint32                 `protobuf:"varint,13,opt,name=productid,proto3" json:"productid,omitempty"`                  //奖励来源产品id（公码上配置的分类标识）
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserBindAuthCodeResp) Reset() {
	*x = UserBindAuthCodeResp{}
	mi := &file_user_user_msg_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBindAuthCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBindAuthCodeResp) ProtoMessage() {}

func (x *UserBindAuthCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBindAuthCodeResp.ProtoReflect.Descriptor instead.
func (*UserBindAuthCodeResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{13}
}

func (x *UserBindAuthCodeResp) GetDevice() *DBUserDivice {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *UserBindAuthCodeResp) GetIsgiveaway() bool {
	if x != nil {
		return x.Isgiveaway
	}
	return false
}

func (x *UserBindAuthCodeResp) GetViplv() int32 {
	if x != nil {
		return x.Viplv
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetVipexptime() int64 {
	if x != nil {
		return x.Vipexptime
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetTradeintegral() int64 {
	if x != nil {
		return x.Tradeintegral
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetTradetotalintegral() int64 {
	if x != nil {
		return x.Tradetotalintegral
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetMeetintegral() int64 {
	if x != nil {
		return x.Meetintegral
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetMeettotalintegral() int64 {
	if x != nil {
		return x.Meettotalintegral
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetAddvipday() int64 {
	if x != nil {
		return x.Addvipday
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetAddtradesecond() int64 {
	if x != nil {
		return x.Addtradesecond
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetAddmeetsecond() int64 {
	if x != nil {
		return x.Addmeetsecond
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetFactoryid() uint32 {
	if x != nil {
		return x.Factoryid
	}
	return 0
}

func (x *UserBindAuthCodeResp) GetProductid() uint32 {
	if x != nil {
		return x.Productid
	}
	return 0
}

// 注销账号
type UserDelReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelReq) Reset() {
	*x = UserDelReq{}
	mi := &file_user_user_msg_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelReq) ProtoMessage() {}

func (x *UserDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelReq.ProtoReflect.Descriptor instead.
func (*UserDelReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{14}
}

type UserDelResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelResp) Reset() {
	*x = UserDelResp{}
	mi := &file_user_user_msg_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelResp) ProtoMessage() {}

func (x *UserDelResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelResp.ProtoReflect.Descriptor instead.
func (*UserDelResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{15}
}

// 用户反馈
type UserFeedbackReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedbackReq) Reset() {
	*x = UserFeedbackReq{}
	mi := &file_user_user_msg_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedbackReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedbackReq) ProtoMessage() {}

func (x *UserFeedbackReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedbackReq.ProtoReflect.Descriptor instead.
func (*UserFeedbackReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{16}
}

func (x *UserFeedbackReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserFeedbackResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFeedbackResp) Reset() {
	*x = UserFeedbackResp{}
	mi := &file_user_user_msg_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFeedbackResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFeedbackResp) ProtoMessage() {}

func (x *UserFeedbackResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFeedbackResp.ProtoReflect.Descriptor instead.
func (*UserFeedbackResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{17}
}

// 获取 app 的环境变量
type UserGetAppConfigReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppConfigReq) Reset() {
	*x = UserGetAppConfigReq{}
	mi := &file_user_user_msg_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppConfigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppConfigReq) ProtoMessage() {}

func (x *UserGetAppConfigReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppConfigReq.ProtoReflect.Descriptor instead.
func (*UserGetAppConfigReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{18}
}

type McpServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servername    string                 `protobuf:"bytes,1,opt,name=servername,proto3" json:"servername,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Type          MCPServerType          `protobuf:"varint,3,opt,name=type,proto3,enum=MCPServerType" json:"type"` //@go_tags(`json:"type"`) 服务类型
	Tools         string                 `protobuf:"bytes,4,opt,name=tools,proto3" json:"tools"`                   //@go_tags(`json:"tools"`) 工具列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpServer) Reset() {
	*x = McpServer{}
	mi := &file_user_user_msg_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpServer) ProtoMessage() {}

func (x *McpServer) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpServer.ProtoReflect.Descriptor instead.
func (*McpServer) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{19}
}

func (x *McpServer) GetServername() string {
	if x != nil {
		return x.Servername
	}
	return ""
}

func (x *McpServer) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *McpServer) GetType() MCPServerType {
	if x != nil {
		return x.Type
	}
	return MCPServerType_Http
}

func (x *McpServer) GetTools() string {
	if x != nil {
		return x.Tools
	}
	return ""
}

// 获取 app 的环境变量
type UserGetAppConfigResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   //@go_tags(`json:"env"`) 時間
	Agents        []*DBAgent             `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents"`                                                                       //@go_tags(`json:"agents"`) 時間
	Mcps          map[string]*McpServer  `protobuf:"bytes,3,rep,name=mcps,proto3" json:"mcps" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //@go_tags(`json:"mcps"`) 時間
	Products      []*DBProduct           `protobuf:"bytes,4,rep,name=products,proto3" json:"products"`                                                                   //@go_tags(`json:"products"`) 時間
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppConfigResp) Reset() {
	*x = UserGetAppConfigResp{}
	mi := &file_user_user_msg_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppConfigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppConfigResp) ProtoMessage() {}

func (x *UserGetAppConfigResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppConfigResp.ProtoReflect.Descriptor instead.
func (*UserGetAppConfigResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{20}
}

func (x *UserGetAppConfigResp) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UserGetAppConfigResp) GetAgents() []*DBAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *UserGetAppConfigResp) GetMcps() map[string]*McpServer {
	if x != nil {
		return x.Mcps
	}
	return nil
}

func (x *UserGetAppConfigResp) GetProducts() []*DBProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

// 获取设备信息 校验升级
type UserGetProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProductReq) Reset() {
	*x = UserGetProductReq{}
	mi := &file_user_user_msg_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProductReq) ProtoMessage() {}

func (x *UserGetProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProductReq.ProtoReflect.Descriptor instead.
func (*UserGetProductReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{21}
}

func (x *UserGetProductReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserGetProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *DBProduct             `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProductResp) Reset() {
	*x = UserGetProductResp{}
	mi := &file_user_user_msg_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProductResp) ProtoMessage() {}

func (x *UserGetProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProductResp.ProtoReflect.Descriptor instead.
func (*UserGetProductResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{22}
}

func (x *UserGetProductResp) GetProduct() *DBProduct {
	if x != nil {
		return x.Product
	}
	return nil
}

// 获取产品对应的固件版本列表
type UserGetProductVersionsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid"` //@go_tags(`json:"pid"`) 产品id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProductVersionsReq) Reset() {
	*x = UserGetProductVersionsReq{}
	mi := &file_user_user_msg_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProductVersionsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProductVersionsReq) ProtoMessage() {}

func (x *UserGetProductVersionsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProductVersionsReq.ProtoReflect.Descriptor instead.
func (*UserGetProductVersionsReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{23}
}

func (x *UserGetProductVersionsReq) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type UserGetProductVersionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*DBProductVersion    `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions"` //@go_tags(`json:"versions"`) 固件版本列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetProductVersionsResp) Reset() {
	*x = UserGetProductVersionsResp{}
	mi := &file_user_user_msg_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetProductVersionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetProductVersionsResp) ProtoMessage() {}

func (x *UserGetProductVersionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetProductVersionsResp.ProtoReflect.Descriptor instead.
func (*UserGetProductVersionsResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{24}
}

func (x *UserGetProductVersionsResp) GetVersions() []*DBProductVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

// 举报AI内容
type UserReportAIContentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reporttype    string                 `protobuf:"bytes,1,opt,name=reporttype,proto3" json:"reporttype,omitempty"`
	Describe      string                 `protobuf:"bytes,2,opt,name=describe,proto3" json:"describe,omitempty"`
	Message       []string               `protobuf:"bytes,3,rep,name=message,proto3" json:"message,omitempty"`
	ReportContent string                 `protobuf:"bytes,4,opt,name=reportContent,proto3" json:"reportContent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReportAIContentReq) Reset() {
	*x = UserReportAIContentReq{}
	mi := &file_user_user_msg_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReportAIContentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportAIContentReq) ProtoMessage() {}

func (x *UserReportAIContentReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportAIContentReq.ProtoReflect.Descriptor instead.
func (*UserReportAIContentReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{25}
}

func (x *UserReportAIContentReq) GetReporttype() string {
	if x != nil {
		return x.Reporttype
	}
	return ""
}

func (x *UserReportAIContentReq) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *UserReportAIContentReq) GetMessage() []string {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UserReportAIContentReq) GetReportContent() string {
	if x != nil {
		return x.ReportContent
	}
	return ""
}

type UserReportAIContentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReportAIContentResp) Reset() {
	*x = UserReportAIContentResp{}
	mi := &file_user_user_msg_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReportAIContentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReportAIContentResp) ProtoMessage() {}

func (x *UserReportAIContentResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReportAIContentResp.ProtoReflect.Descriptor instead.
func (*UserReportAIContentResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{26}
}

// 获取设备信息 校验升级
type UserGetChannelAppsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetChannelAppsReq) Reset() {
	*x = UserGetChannelAppsReq{}
	mi := &file_user_user_msg_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetChannelAppsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetChannelAppsReq) ProtoMessage() {}

func (x *UserGetChannelAppsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetChannelAppsReq.ProtoReflect.Descriptor instead.
func (*UserGetChannelAppsReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{27}
}

type UserGetChannelAppsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*DBChannelApp        `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetChannelAppsResp) Reset() {
	*x = UserGetChannelAppsResp{}
	mi := &file_user_user_msg_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetChannelAppsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetChannelAppsResp) ProtoMessage() {}

func (x *UserGetChannelAppsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetChannelAppsResp.ProtoReflect.Descriptor instead.
func (*UserGetChannelAppsResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{28}
}

func (x *UserGetChannelAppsResp) GetApps() []*DBChannelApp {
	if x != nil {
		return x.Apps
	}
	return nil
}

// 获取设备信息 校验升级
type UserGetChannelAppReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       int32                  `protobuf:"varint,1,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetChannelAppReq) Reset() {
	*x = UserGetChannelAppReq{}
	mi := &file_user_user_msg_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetChannelAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetChannelAppReq) ProtoMessage() {}

func (x *UserGetChannelAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetChannelAppReq.ProtoReflect.Descriptor instead.
func (*UserGetChannelAppReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{29}
}

func (x *UserGetChannelAppReq) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

type UserGetChannelAppResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *DBChannelApp          `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetChannelAppResp) Reset() {
	*x = UserGetChannelAppResp{}
	mi := &file_user_user_msg_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetChannelAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetChannelAppResp) ProtoMessage() {}

func (x *UserGetChannelAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetChannelAppResp.ProtoReflect.Descriptor instead.
func (*UserGetChannelAppResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{30}
}

func (x *UserGetChannelAppResp) GetApp() *DBChannelApp {
	if x != nil {
		return x.App
	}
	return nil
}

// 用户上报行为
type UserPushActionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       map[string]int32       `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //行为
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPushActionReq) Reset() {
	*x = UserPushActionReq{}
	mi := &file_user_user_msg_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPushActionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPushActionReq) ProtoMessage() {}

func (x *UserPushActionReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPushActionReq.ProtoReflect.Descriptor instead.
func (*UserPushActionReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{31}
}

func (x *UserPushActionReq) GetActions() map[string]int32 {
	if x != nil {
		return x.Actions
	}
	return nil
}

type UserPushActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPushActionResp) Reset() {
	*x = UserPushActionResp{}
	mi := &file_user_user_msg_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPushActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPushActionResp) ProtoMessage() {}

func (x *UserPushActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPushActionResp.ProtoReflect.Descriptor instead.
func (*UserPushActionResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{32}
}

// 获取设备信息 校验升级
type UserGetDevicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetDevicesReq) Reset() {
	*x = UserGetDevicesReq{}
	mi := &file_user_user_msg_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetDevicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetDevicesReq) ProtoMessage() {}

func (x *UserGetDevicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetDevicesReq.ProtoReflect.Descriptor instead.
func (*UserGetDevicesReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{33}
}

type UserGetDevicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DBUserDivice        `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetDevicesResp) Reset() {
	*x = UserGetDevicesResp{}
	mi := &file_user_user_msg_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetDevicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetDevicesResp) ProtoMessage() {}

func (x *UserGetDevicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetDevicesResp.ProtoReflect.Descriptor instead.
func (*UserGetDevicesResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{34}
}

func (x *UserGetDevicesResp) GetDevices() []*DBUserDivice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// 上传资源使用
type UserUsagesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usagetype     UsageType              `protobuf:"varint,1,opt,name=usagetype,proto3,enum=UsageType" json:"usagetype,omitempty"`                                                      //使用类型
	Usages        map[string]int64       `protobuf:"bytes,2,rep,name=usages,proto3" json:"usages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //用量统计数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUsagesReq) Reset() {
	*x = UserUsagesReq{}
	mi := &file_user_user_msg_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUsagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUsagesReq) ProtoMessage() {}

func (x *UserUsagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUsagesReq.ProtoReflect.Descriptor instead.
func (*UserUsagesReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{35}
}

func (x *UserUsagesReq) GetUsagetype() UsageType {
	if x != nil {
		return x.Usagetype
	}
	return UsageType_UsageNull
}

func (x *UserUsagesReq) GetUsages() map[string]int64 {
	if x != nil {
		return x.Usages
	}
	return nil
}

type UserUsagesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Usages        map[int32]int64        `protobuf:"bytes,1,rep,name=usages,proto3" json:"usages,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` //资源剩余使用量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUsagesResp) Reset() {
	*x = UserUsagesResp{}
	mi := &file_user_user_msg_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUsagesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUsagesResp) ProtoMessage() {}

func (x *UserUsagesResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUsagesResp.ProtoReflect.Descriptor instead.
func (*UserUsagesResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{36}
}

func (x *UserUsagesResp) GetUsages() map[int32]int64 {
	if x != nil {
		return x.Usages
	}
	return nil
}

// 获取唤醒词列表
type UserGetWakeupVoicesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetWakeupVoicesReq) Reset() {
	*x = UserGetWakeupVoicesReq{}
	mi := &file_user_user_msg_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetWakeupVoicesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetWakeupVoicesReq) ProtoMessage() {}

func (x *UserGetWakeupVoicesReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetWakeupVoicesReq.ProtoReflect.Descriptor instead.
func (*UserGetWakeupVoicesReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{37}
}

type UserGetWakeupVoicesResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Voices        []*DBWakeupVoice       `protobuf:"bytes,1,rep,name=voices,proto3" json:"voices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetWakeupVoicesResp) Reset() {
	*x = UserGetWakeupVoicesResp{}
	mi := &file_user_user_msg_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetWakeupVoicesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetWakeupVoicesResp) ProtoMessage() {}

func (x *UserGetWakeupVoicesResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetWakeupVoicesResp.ProtoReflect.Descriptor instead.
func (*UserGetWakeupVoicesResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{38}
}

func (x *UserGetWakeupVoicesResp) GetVoices() []*DBWakeupVoice {
	if x != nil {
		return x.Voices
	}
	return nil
}

// 获取统计数据
type UserGetStatisticsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetStatisticsReq) Reset() {
	*x = UserGetStatisticsReq{}
	mi := &file_user_user_msg_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetStatisticsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetStatisticsReq) ProtoMessage() {}

func (x *UserGetStatisticsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetStatisticsReq.ProtoReflect.Descriptor instead.
func (*UserGetStatisticsReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{39}
}

type UserGetStatisticsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statistics    *DBUserStatistics      `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetStatisticsResp) Reset() {
	*x = UserGetStatisticsResp{}
	mi := &file_user_user_msg_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetStatisticsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetStatisticsResp) ProtoMessage() {}

func (x *UserGetStatisticsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetStatisticsResp.ProtoReflect.Descriptor instead.
func (*UserGetStatisticsResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{40}
}

func (x *UserGetStatisticsResp) GetStatistics() *DBUserStatistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

// 获取应用设置
type UserGetAppSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppSettingReq) Reset() {
	*x = UserGetAppSettingReq{}
	mi := &file_user_user_msg_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppSettingReq) ProtoMessage() {}

func (x *UserGetAppSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppSettingReq.ProtoReflect.Descriptor instead.
func (*UserGetAppSettingReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{41}
}

type UserGetAppSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *DBUuserAppSetting     `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppSettingResp) Reset() {
	*x = UserGetAppSettingResp{}
	mi := &file_user_user_msg_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppSettingResp) ProtoMessage() {}

func (x *UserGetAppSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppSettingResp.ProtoReflect.Descriptor instead.
func (*UserGetAppSettingResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{42}
}

func (x *UserGetAppSettingResp) GetSetting() *DBUuserAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

// 更新应用设置
type UserUpdateAppSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Setting       *DBUuserAppSetting     `protobuf:"bytes,1,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateAppSettingReq) Reset() {
	*x = UserUpdateAppSettingReq{}
	mi := &file_user_user_msg_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateAppSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateAppSettingReq) ProtoMessage() {}

func (x *UserUpdateAppSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateAppSettingReq.ProtoReflect.Descriptor instead.
func (*UserUpdateAppSettingReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{43}
}

func (x *UserUpdateAppSettingReq) GetSetting() *DBUuserAppSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type UserUpdateAppSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateAppSettingResp) Reset() {
	*x = UserUpdateAppSettingResp{}
	mi := &file_user_user_msg_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateAppSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateAppSettingResp) ProtoMessage() {}

func (x *UserUpdateAppSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateAppSettingResp.ProtoReflect.Descriptor instead.
func (*UserUpdateAppSettingResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{44}
}

// 更新设备设置
type UserUpdateDeviceSettingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lxsetting     string                 `protobuf:"bytes,2,opt,name=lxsetting,proto3" json:"lxsetting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateDeviceSettingReq) Reset() {
	*x = UserUpdateDeviceSettingReq{}
	mi := &file_user_user_msg_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateDeviceSettingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateDeviceSettingReq) ProtoMessage() {}

func (x *UserUpdateDeviceSettingReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateDeviceSettingReq.ProtoReflect.Descriptor instead.
func (*UserUpdateDeviceSettingReq) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{45}
}

func (x *UserUpdateDeviceSettingReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdateDeviceSettingReq) GetLxsetting() string {
	if x != nil {
		return x.Lxsetting
	}
	return ""
}

type UserUpdateDeviceSettingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lxsetting     string                 `protobuf:"bytes,2,opt,name=lxsetting,proto3" json:"lxsetting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateDeviceSettingResp) Reset() {
	*x = UserUpdateDeviceSettingResp{}
	mi := &file_user_user_msg_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateDeviceSettingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateDeviceSettingResp) ProtoMessage() {}

func (x *UserUpdateDeviceSettingResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateDeviceSettingResp.ProtoReflect.Descriptor instead.
func (*UserUpdateDeviceSettingResp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_proto_rawDescGZIP(), []int{46}
}

func (x *UserUpdateDeviceSettingResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserUpdateDeviceSettingResp) GetLxsetting() string {
	if x != nil {
		return x.Lxsetting
	}
	return ""
}

var File_user_user_msg_proto protoreflect.FileDescriptor

const file_user_user_msg_proto_rawDesc = "" +
	"\n" +
	"\x13user/user_msg.proto\x1a\x12user/user_db.proto\x1a\bdb.proto\x1a\n" +
	"enum.proto\"\xcc\x02\n" +
	"\vUserSginReq\x12\x1f\n" +
	"\x05stype\x18\x01 \x01(\x0e2\t.SginTyoeR\x05stype\x12\x12\n" +
	"\x04mail\x18\x02 \x01(\tR\x04mail\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06ttoken\x18\x04 \x01(\tR\x06ttoken\x12\x14\n" +
	"\x05vcode\x18\x05 \x01(\tR\x05vcode\x12\x1e\n" +
	"\n" +
	"phonemodel\x18\n" +
	" \x01(\tR\n" +
	"phonemodel\x12\x1a\n" +
	"\bphonemac\x18\v \x01(\tR\bphonemac\x12\x12\n" +
	"\x04name\x18\x14 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x15 \x01(\tR\x06avatar\x12\x1a\n" +
	"\blanguage\x18\x16 \x01(\tR\blanguage\x12&\n" +
	"\achannel\x18\x17 \x01(\x0e2\f.UserChannelR\achannel\x12\x18\n" +
	"\aversion\x18\x18 \x01(\tR\aversion\"j\n" +
	"\fUserSginResp\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\x04user\x18\x02 \x01(\v2\a.DBUserR\x04user\x12'\n" +
	"\adevices\x18\x03 \x03(\v2\r.DBUserDiviceR\adevices\"?\n" +
	"\x13UserVerificationReq\x12\x14\n" +
	"\x05vtype\x18\x01 \x01(\x05R\x05vtype\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\"\x16\n" +
	"\x14UserVerificationResp\"R\n" +
	"\x0eUserGetInfoReq\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12&\n" +
	"\achannel\x18\x02 \x01(\x0e2\f.UserChannelR\achannel\"W\n" +
	"\x0fUserGetInfoResp\x12\x1b\n" +
	"\x04user\x18\x01 \x01(\v2\a.DBUserR\x04user\x12'\n" +
	"\adevices\x18\x02 \x03(\v2\r.DBUserDiviceR\adevices\"n\n" +
	"\x0eUserSettingReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\"q\n" +
	"\x0fUserSettingResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\"\x91\x01\n" +
	"\x11UserBindDeviceReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"devicename\x18\x03 \x01(\tR\n" +
	"devicename\x12\x1c\n" +
	"\tdevicemac\x18\x04 \x01(\tR\tdevicemac\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\x93\x03\n" +
	"\x12UserBindDeviceResp\x12%\n" +
	"\x06device\x18\x01 \x01(\v2\r.DBUserDiviceR\x06device\x12\x1e\n" +
	"\n" +
	"isgiveaway\x18\x02 \x01(\bR\n" +
	"isgiveaway\x12\x14\n" +
	"\x05viplv\x18\x03 \x01(\x05R\x05viplv\x12\x1e\n" +
	"\n" +
	"vipexptime\x18\x04 \x01(\x03R\n" +
	"vipexptime\x12&\n" +
	"\x0eaichatintegral\x18\x05 \x01(\x03R\x0eaichatintegral\x120\n" +
	"\x13aichattotalintegral\x18\x06 \x01(\x03R\x13aichattotalintegral\x12$\n" +
	"\rtradeintegral\x18\a \x01(\x03R\rtradeintegral\x12.\n" +
	"\x12tradetotalintegral\x18\b \x01(\x03R\x12tradetotalintegral\x12\"\n" +
	"\fmeetintegral\x18\t \x01(\x03R\fmeetintegral\x12,\n" +
	"\x11meettotalintegral\x18\n" +
	" \x01(\x03R\x11meettotalintegral\"%\n" +
	"\x13UserUnBindDeviceReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\x16\n" +
	"\x14UserUnBindDeviceResp\"g\n" +
	"\x13UserBindAuthCodeReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1e\n" +
	"\n" +
	"devicename\x18\x02 \x01(\tR\n" +
	"devicename\x12\x1c\n" +
	"\tdevicemac\x18\x03 \x01(\tR\tdevicemac\"\xe3\x03\n" +
	"\x14UserBindAuthCodeResp\x12%\n" +
	"\x06device\x18\x01 \x01(\v2\r.DBUserDiviceR\x06device\x12\x1e\n" +
	"\n" +
	"isgiveaway\x18\x02 \x01(\bR\n" +
	"isgiveaway\x12\x14\n" +
	"\x05viplv\x18\x03 \x01(\x05R\x05viplv\x12\x1e\n" +
	"\n" +
	"vipexptime\x18\x04 \x01(\x03R\n" +
	"vipexptime\x12$\n" +
	"\rtradeintegral\x18\x05 \x01(\x03R\rtradeintegral\x12.\n" +
	"\x12tradetotalintegral\x18\x06 \x01(\x03R\x12tradetotalintegral\x12\"\n" +
	"\fmeetintegral\x18\a \x01(\x03R\fmeetintegral\x12,\n" +
	"\x11meettotalintegral\x18\b \x01(\x03R\x11meettotalintegral\x12\x1c\n" +
	"\taddvipday\x18\t \x01(\x03R\taddvipday\x12&\n" +
	"\x0eaddtradesecond\x18\n" +
	" \x01(\x03R\x0eaddtradesecond\x12$\n" +
	"\raddmeetsecond\x18\v \x01(\x03R\raddmeetsecond\x12\x1c\n" +
	"\tfactoryid\x18\f \x01(\rR\tfactoryid\x12\x1c\n" +
	"\tproductid\x18\r \x01(\rR\tproductid\"\f\n" +
	"\n" +
	"UserDelReq\"\r\n" +
	"\vUserDelResp\"+\n" +
	"\x0fUserFeedbackReq\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x12\n" +
	"\x10UserFeedbackResp\"\x15\n" +
	"\x13UserGetAppConfigReq\"w\n" +
	"\tMcpServer\x12\x1e\n" +
	"\n" +
	"servername\x18\x01 \x01(\tR\n" +
	"servername\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\"\n" +
	"\x04type\x18\x03 \x01(\x0e2\x0e.MCPServerTypeR\x04type\x12\x14\n" +
	"\x05tools\x18\x04 \x01(\tR\x05tools\"\xc4\x02\n" +
	"\x14UserGetAppConfigResp\x120\n" +
	"\x03env\x18\x01 \x03(\v2\x1e.UserGetAppConfigResp.EnvEntryR\x03env\x12 \n" +
	"\x06agents\x18\x02 \x03(\v2\b.DBAgentR\x06agents\x123\n" +
	"\x04mcps\x18\x03 \x03(\v2\x1f.UserGetAppConfigResp.McpsEntryR\x04mcps\x12&\n" +
	"\bproducts\x18\x04 \x03(\v2\n" +
	".DBProductR\bproducts\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\tMcpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".McpServerR\x05value:\x028\x01\"#\n" +
	"\x11UserGetProductReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x12UserGetProductResp\x12$\n" +
	"\aproduct\x18\x01 \x01(\v2\n" +
	".DBProductR\aproduct\"-\n" +
	"\x19UserGetProductVersionsReq\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\"K\n" +
	"\x1aUserGetProductVersionsResp\x12-\n" +
	"\bversions\x18\x01 \x03(\v2\x11.DBProductVersionR\bversions\"\x94\x01\n" +
	"\x16UserReportAIContentReq\x12\x1e\n" +
	"\n" +
	"reporttype\x18\x01 \x01(\tR\n" +
	"reporttype\x12\x1a\n" +
	"\bdescribe\x18\x02 \x01(\tR\bdescribe\x12\x18\n" +
	"\amessage\x18\x03 \x03(\tR\amessage\x12$\n" +
	"\rreportContent\x18\x04 \x01(\tR\rreportContent\"\x19\n" +
	"\x17UserReportAIContentResp\"\x17\n" +
	"\x15UserGetChannelAppsReq\";\n" +
	"\x16UserGetChannelAppsResp\x12!\n" +
	"\x04apps\x18\x01 \x03(\v2\r.DBChannelAppR\x04apps\"0\n" +
	"\x14UserGetChannelAppReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\x05R\achannel\"8\n" +
	"\x15UserGetChannelAppResp\x12\x1f\n" +
	"\x03app\x18\x01 \x01(\v2\r.DBChannelAppR\x03app\"\x8a\x01\n" +
	"\x11UserPushActionReq\x129\n" +
	"\aactions\x18\x01 \x03(\v2\x1f.UserPushActionReq.ActionsEntryR\aactions\x1a:\n" +
	"\fActionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x14\n" +
	"\x12UserPushActionResp\"\x13\n" +
	"\x11UserGetDevicesReq\"=\n" +
	"\x12UserGetDevicesResp\x12'\n" +
	"\adevices\x18\x01 \x03(\v2\r.DBUserDiviceR\adevices\"\xa8\x01\n" +
	"\rUserUsagesReq\x12(\n" +
	"\tusagetype\x18\x01 \x01(\x0e2\n" +
	".UsageTypeR\tusagetype\x122\n" +
	"\x06usages\x18\x02 \x03(\v2\x1a.UserUsagesReq.UsagesEntryR\x06usages\x1a9\n" +
	"\vUsagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x80\x01\n" +
	"\x0eUserUsagesResp\x123\n" +
	"\x06usages\x18\x01 \x03(\v2\x1b.UserUsagesResp.UsagesEntryR\x06usages\x1a9\n" +
	"\vUsagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\x18\n" +
	"\x16UserGetWakeupVoicesReq\"A\n" +
	"\x17UserGetWakeupVoicesResp\x12&\n" +
	"\x06voices\x18\x01 \x03(\v2\x0e.DBWakeupVoiceR\x06voices\"\x16\n" +
	"\x14UserGetStatisticsReq\"J\n" +
	"\x15UserGetStatisticsResp\x121\n" +
	"\n" +
	"statistics\x18\x01 \x01(\v2\x11.DBUserStatisticsR\n" +
	"statistics\"\x16\n" +
	"\x14UserGetAppSettingReq\"E\n" +
	"\x15UserGetAppSettingResp\x12,\n" +
	"\asetting\x18\x01 \x01(\v2\x12.DBUuserAppSettingR\asetting\"G\n" +
	"\x17UserUpdateAppSettingReq\x12,\n" +
	"\asetting\x18\x01 \x01(\v2\x12.DBUuserAppSettingR\asetting\"\x1a\n" +
	"\x18UserUpdateAppSettingResp\"J\n" +
	"\x1aUserUpdateDeviceSettingReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tlxsetting\x18\x02 \x01(\tR\tlxsetting\"K\n" +
	"\x1bUserUpdateDeviceSettingResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1c\n" +
	"\tlxsetting\x18\x02 \x01(\tR\tlxsettingB\x06Z\x04.;pbb\x06proto3"

var (
	file_user_user_msg_proto_rawDescOnce sync.Once
	file_user_user_msg_proto_rawDescData []byte
)

func file_user_user_msg_proto_rawDescGZIP() []byte {
	file_user_user_msg_proto_rawDescOnce.Do(func() {
		file_user_user_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_msg_proto_rawDesc), len(file_user_user_msg_proto_rawDesc)))
	})
	return file_user_user_msg_proto_rawDescData
}

var file_user_user_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 52)
var file_user_user_msg_proto_goTypes = []any{
	(*UserSginReq)(nil),                 // 0: UserSginReq
	(*UserSginResp)(nil),                // 1: UserSginResp
	(*UserVerificationReq)(nil),         // 2: UserVerificationReq
	(*UserVerificationResp)(nil),        // 3: UserVerificationResp
	(*UserGetInfoReq)(nil),              // 4: UserGetInfoReq
	(*UserGetInfoResp)(nil),             // 5: UserGetInfoResp
	(*UserSettingReq)(nil),              // 6: UserSettingReq
	(*UserSettingResp)(nil),             // 7: UserSettingResp
	(*UserBindDeviceReq)(nil),           // 8: UserBindDeviceReq
	(*UserBindDeviceResp)(nil),          // 9: UserBindDeviceResp
	(*UserUnBindDeviceReq)(nil),         // 10: UserUnBindDeviceReq
	(*UserUnBindDeviceResp)(nil),        // 11: UserUnBindDeviceResp
	(*UserBindAuthCodeReq)(nil),         // 12: UserBindAuthCodeReq
	(*UserBindAuthCodeResp)(nil),        // 13: UserBindAuthCodeResp
	(*UserDelReq)(nil),                  // 14: UserDelReq
	(*UserDelResp)(nil),                 // 15: UserDelResp
	(*UserFeedbackReq)(nil),             // 16: UserFeedbackReq
	(*UserFeedbackResp)(nil),            // 17: UserFeedbackResp
	(*UserGetAppConfigReq)(nil),         // 18: UserGetAppConfigReq
	(*McpServer)(nil),                   // 19: McpServer
	(*UserGetAppConfigResp)(nil),        // 20: UserGetAppConfigResp
	(*UserGetProductReq)(nil),           // 21: UserGetProductReq
	(*UserGetProductResp)(nil),          // 22: UserGetProductResp
	(*UserGetProductVersionsReq)(nil),   // 23: UserGetProductVersionsReq
	(*UserGetProductVersionsResp)(nil),  // 24: UserGetProductVersionsResp
	(*UserReportAIContentReq)(nil),      // 25: UserReportAIContentReq
	(*UserReportAIContentResp)(nil),     // 26: UserReportAIContentResp
	(*UserGetChannelAppsReq)(nil),       // 27: UserGetChannelAppsReq
	(*UserGetChannelAppsResp)(nil),      // 28: UserGetChannelAppsResp
	(*UserGetChannelAppReq)(nil),        // 29: UserGetChannelAppReq
	(*UserGetChannelAppResp)(nil),       // 30: UserGetChannelAppResp
	(*UserPushActionReq)(nil),           // 31: UserPushActionReq
	(*UserPushActionResp)(nil),          // 32: UserPushActionResp
	(*UserGetDevicesReq)(nil),           // 33: UserGetDevicesReq
	(*UserGetDevicesResp)(nil),          // 34: UserGetDevicesResp
	(*UserUsagesReq)(nil),               // 35: UserUsagesReq
	(*UserUsagesResp)(nil),              // 36: UserUsagesResp
	(*UserGetWakeupVoicesReq)(nil),      // 37: UserGetWakeupVoicesReq
	(*UserGetWakeupVoicesResp)(nil),     // 38: UserGetWakeupVoicesResp
	(*UserGetStatisticsReq)(nil),        // 39: UserGetStatisticsReq
	(*UserGetStatisticsResp)(nil),       // 40: UserGetStatisticsResp
	(*UserGetAppSettingReq)(nil),        // 41: UserGetAppSettingReq
	(*UserGetAppSettingResp)(nil),       // 42: UserGetAppSettingResp
	(*UserUpdateAppSettingReq)(nil),     // 43: UserUpdateAppSettingReq
	(*UserUpdateAppSettingResp)(nil),    // 44: UserUpdateAppSettingResp
	(*UserUpdateDeviceSettingReq)(nil),  // 45: UserUpdateDeviceSettingReq
	(*UserUpdateDeviceSettingResp)(nil), // 46: UserUpdateDeviceSettingResp
	nil,                                 // 47: UserGetAppConfigResp.EnvEntry
	nil,                                 // 48: UserGetAppConfigResp.McpsEntry
	nil,                                 // 49: UserPushActionReq.ActionsEntry
	nil,                                 // 50: UserUsagesReq.UsagesEntry
	nil,                                 // 51: UserUsagesResp.UsagesEntry
	(SginTyoe)(0),                       // 52: SginTyoe
	(UserChannel)(0),                    // 53: UserChannel
	(*DBUser)(nil),                      // 54: DBUser
	(*DBUserDivice)(nil),                // 55: DBUserDivice
	(MCPServerType)(0),                  // 56: MCPServerType
	(*DBAgent)(nil),                     // 57: DBAgent
	(*DBProduct)(nil),                   // 58: DBProduct
	(*DBProductVersion)(nil),            // 59: DBProductVersion
	(*DBChannelApp)(nil),                // 60: DBChannelApp
	(UsageType)(0),                      // 61: UsageType
	(*DBWakeupVoice)(nil),               // 62: DBWakeupVoice
	(*DBUserStatistics)(nil),            // 63: DBUserStatistics
	(*DBUuserAppSetting)(nil),           // 64: DBUuserAppSetting
}
var file_user_user_msg_proto_depIdxs = []int32{
	52, // 0: UserSginReq.stype:type_name -> SginTyoe
	53, // 1: UserSginReq.channel:type_name -> UserChannel
	54, // 2: UserSginResp.user:type_name -> DBUser
	55, // 3: UserSginResp.devices:type_name -> DBUserDivice
	53, // 4: UserGetInfoReq.channel:type_name -> UserChannel
	54, // 5: UserGetInfoResp.user:type_name -> DBUser
	55, // 6: UserGetInfoResp.devices:type_name -> DBUserDivice
	55, // 7: UserBindDeviceResp.device:type_name -> DBUserDivice
	55, // 8: UserBindAuthCodeResp.device:type_name -> DBUserDivice
	56, // 9: McpServer.type:type_name -> MCPServerType
	47, // 10: UserGetAppConfigResp.env:type_name -> UserGetAppConfigResp.EnvEntry
	57, // 11: UserGetAppConfigResp.agents:type_name -> DBAgent
	48, // 12: UserGetAppConfigResp.mcps:type_name -> UserGetAppConfigResp.McpsEntry
	58, // 13: UserGetAppConfigResp.products:type_name -> DBProduct
	58, // 14: UserGetProductResp.product:type_name -> DBProduct
	59, // 15: UserGetProductVersionsResp.versions:type_name -> DBProductVersion
	60, // 16: UserGetChannelAppsResp.apps:type_name -> DBChannelApp
	60, // 17: UserGetChannelAppResp.app:type_name -> DBChannelApp
	49, // 18: UserPushActionReq.actions:type_name -> UserPushActionReq.ActionsEntry
	55, // 19: UserGetDevicesResp.devices:type_name -> DBUserDivice
	61, // 20: UserUsagesReq.usagetype:type_name -> UsageType
	50, // 21: UserUsagesReq.usages:type_name -> UserUsagesReq.UsagesEntry
	51, // 22: UserUsagesResp.usages:type_name -> UserUsagesResp.UsagesEntry
	62, // 23: UserGetWakeupVoicesResp.voices:type_name -> DBWakeupVoice
	63, // 24: UserGetStatisticsResp.statistics:type_name -> DBUserStatistics
	64, // 25: UserGetAppSettingResp.setting:type_name -> DBUuserAppSetting
	64, // 26: UserUpdateAppSettingReq.setting:type_name -> DBUuserAppSetting
	19, // 27: UserGetAppConfigResp.McpsEntry.value:type_name -> McpServer
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_user_user_msg_proto_init() }
func file_user_user_msg_proto_init() {
	if File_user_user_msg_proto != nil {
		return
	}
	file_user_user_db_proto_init()
	file_db_proto_init()
	file_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_msg_proto_rawDesc), len(file_user_user_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   52,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_msg_proto_goTypes,
		DependencyIndexes: file_user_user_msg_proto_depIdxs,
		MessageInfos:      file_user_user_msg_proto_msgTypes,
	}.Build()
	File_user_user_msg_proto = out.File
	file_user_user_msg_proto_goTypes = nil
	file_user_user_msg_proto_depIdxs = nil
}
