// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.1
// source: user/user_msg_v2.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取 app 的环境变量
type UserGetAppConfigV2Req struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppConfigV2Req) Reset() {
	*x = UserGetAppConfigV2Req{}
	mi := &file_user_user_msg_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppConfigV2Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppConfigV2Req) ProtoMessage() {}

func (x *UserGetAppConfigV2Req) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppConfigV2Req.ProtoReflect.Descriptor instead.
func (*UserGetAppConfigV2Req) Descriptor() ([]byte, []int) {
	return file_user_user_msg_v2_proto_rawDescGZIP(), []int{0}
}

// 获取 app 的环境变量
type UserGetAppConfigV2Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           map[string]string      `protobuf:"bytes,1,rep,name=env,proto3" json:"env" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`   //@go_tags(`json:"env"`) 時間
	Agents        []*DBAgent             `protobuf:"bytes,2,rep,name=agents,proto3" json:"agents"`                                                                       //@go_tags(`json:"agents"`) 時間
	Mcps          map[string]*McpServer  `protobuf:"bytes,3,rep,name=mcps,proto3" json:"mcps" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //@go_tags(`json:"mcps"`) 時間
	Products      []*DBProduct           `protobuf:"bytes,4,rep,name=products,proto3" json:"products"`                                                                   //@go_tags(`json:"products"`) 時間
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserGetAppConfigV2Resp) Reset() {
	*x = UserGetAppConfigV2Resp{}
	mi := &file_user_user_msg_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetAppConfigV2Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetAppConfigV2Resp) ProtoMessage() {}

func (x *UserGetAppConfigV2Resp) ProtoReflect() protoreflect.Message {
	mi := &file_user_user_msg_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetAppConfigV2Resp.ProtoReflect.Descriptor instead.
func (*UserGetAppConfigV2Resp) Descriptor() ([]byte, []int) {
	return file_user_user_msg_v2_proto_rawDescGZIP(), []int{1}
}

func (x *UserGetAppConfigV2Resp) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *UserGetAppConfigV2Resp) GetAgents() []*DBAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *UserGetAppConfigV2Resp) GetMcps() map[string]*McpServer {
	if x != nil {
		return x.Mcps
	}
	return nil
}

func (x *UserGetAppConfigV2Resp) GetProducts() []*DBProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_user_user_msg_v2_proto protoreflect.FileDescriptor

const file_user_user_msg_v2_proto_rawDesc = "" +
	"\n" +
	"\x16user/user_msg_v2.proto\x1a\x13user/user_msg.proto\x1a\bdb.proto\"\x17\n" +
	"\x15UserGetAppConfigV2Req\"\xca\x02\n" +
	"\x16UserGetAppConfigV2Resp\x122\n" +
	"\x03env\x18\x01 \x03(\v2 .UserGetAppConfigV2Resp.EnvEntryR\x03env\x12 \n" +
	"\x06agents\x18\x02 \x03(\v2\b.DBAgentR\x06agents\x125\n" +
	"\x04mcps\x18\x03 \x03(\v2!.UserGetAppConfigV2Resp.McpsEntryR\x04mcps\x12&\n" +
	"\bproducts\x18\x04 \x03(\v2\n" +
	".DBProductR\bproducts\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\tMcpsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".McpServerR\x05value:\x028\x01B\x06Z\x04.;pbb\x06proto3"

var (
	file_user_user_msg_v2_proto_rawDescOnce sync.Once
	file_user_user_msg_v2_proto_rawDescData []byte
)

func file_user_user_msg_v2_proto_rawDescGZIP() []byte {
	file_user_user_msg_v2_proto_rawDescOnce.Do(func() {
		file_user_user_msg_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_user_msg_v2_proto_rawDesc), len(file_user_user_msg_v2_proto_rawDesc)))
	})
	return file_user_user_msg_v2_proto_rawDescData
}

var file_user_user_msg_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_user_user_msg_v2_proto_goTypes = []any{
	(*UserGetAppConfigV2Req)(nil),  // 0: UserGetAppConfigV2Req
	(*UserGetAppConfigV2Resp)(nil), // 1: UserGetAppConfigV2Resp
	nil,                            // 2: UserGetAppConfigV2Resp.EnvEntry
	nil,                            // 3: UserGetAppConfigV2Resp.McpsEntry
	(*DBAgent)(nil),                // 4: DBAgent
	(*DBProduct)(nil),              // 5: DBProduct
	(*McpServer)(nil),              // 6: McpServer
}
var file_user_user_msg_v2_proto_depIdxs = []int32{
	2, // 0: UserGetAppConfigV2Resp.env:type_name -> UserGetAppConfigV2Resp.EnvEntry
	4, // 1: UserGetAppConfigV2Resp.agents:type_name -> DBAgent
	3, // 2: UserGetAppConfigV2Resp.mcps:type_name -> UserGetAppConfigV2Resp.McpsEntry
	5, // 3: UserGetAppConfigV2Resp.products:type_name -> DBProduct
	6, // 4: UserGetAppConfigV2Resp.McpsEntry.value:type_name -> McpServer
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_user_user_msg_v2_proto_init() }
func file_user_user_msg_v2_proto_init() {
	if File_user_user_msg_v2_proto != nil {
		return
	}
	file_user_user_msg_proto_init()
	file_db_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_user_msg_v2_proto_rawDesc), len(file_user_user_msg_v2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_user_msg_v2_proto_goTypes,
		DependencyIndexes: file_user_user_msg_v2_proto_depIdxs,
		MessageInfos:      file_user_user_msg_v2_proto_msgTypes,
	}.Build()
	File_user_user_msg_v2_proto = out.File
	file_user_user_msg_v2_proto_goTypes = nil
	file_user_user_msg_v2_proto_depIdxs = nil
}
